class HDCurrawong:HDWeapon{
	default{
		+hdweapon.fitsinbackpack
		weapon.selectionorder 20;
		weapon.slotnumber 4;
		weapon.slotpriority 2;
		inventory.pickupsound "misc/w_pkup";
		inventory.pickupmessage "$PICKUP_CURRAWONG";
		scale 0.7;
		weapon.bobrangex 0.2;
		weapon.bobrangey 0.8;
		obituary "$OB_CURRAWONG";
		hdweapon.refid HDLD_CURRAWONG;
		tag "$TAG_CURRAWONG";
		inventory.icon "CWRPA0";

		hdweapon.ammo1 "HD10mMag30",1;

		hdweapon.loadoutcodes "
			\cunoshot - 0/1, whether it has a 4-gauge shotgun
			\cusemi - 0/1, whether it has a fire selector enabled
			\cufiremode - 0-2, semi/auto/burst
			\cudot - 0-5";
	}
	override void tick(){
		super.tick();
		drainheat(CURWS_HEAT,9);
	}
	override bool AddSpareWeapon(actor newowner){return AddSpareWeaponRegular(newowner);}
	override hdweapon GetSpareWeapon(actor newowner,bool reverse,bool doselect){return GetSpareWeaponRegular(newowner,reverse,doselect);}
	override void postbeginplay(){
		super.postbeginplay();
		barrellength=18;
		if(weaponstatus[0]&CUWF_NOSHOTGUN){
			barrelwidth=0.5;
			barreldepth=1;
			weaponstatus[0]&=~(CUWF_SHOTMODE|CURWF_4GAUGELOADED);
		}else{
			barrelwidth=1;
			barreldepth=3;
			bobrangex*=1.05;
			bobrangey*=1.2;
		}
	}
	override double gunmass(){
		if(weaponstatus[0]&CUWF_NOSHOTGUN){
			return 5.5+weaponstatus[CURWS_MAG]*0.02;
		}else{
			return 6.9+weaponstatus[CURWS_MAG]*0.01+(weaponstatus[0]&CURWF_4GAUGELOADED?0.82:0.);
		}
	}
	override void GunBounce(){
		super.GunBounce();
		if(!random(0,5))weaponstatus[0]&=~CURWF_CHAMBERBROKEN;
	}
	override void OnPlayerDrop(){
		if(
			weaponstatus[0]&CURWF_CHAMBER
			&&!random(0,15)
		)weaponstatus[0]|=CURWF_CHAMBERBROKEN;
	}
	override string,double getpickupsprite(bool usespare){
		string spr;

		int wep0=GetSpareWeaponValue(0,usespare);

		if(wep0&CUWF_NOSHOTGUN){
			if(wep0&CURWF_NOFIRESELECT)
				spr="CWRP";
			else spr="CWRP";
		}else{
			if(wep0&CURWF_NOFIRESELECT)
				spr="CWRP";
			else spr="CWRP";
		}

		//set to no-mag frame
		if(GetSpareWeaponValue(CURWS_MAG,usespare)<0)spr=spr.."D";
		else spr=spr.."A";

		return spr.."0",1.;
	}
	override void DrawHUDStuff(HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl){
		if(sb.hudlevel==1){
			int nextmagloaded=sb.GetNextLoadMag(hdmagammo(hpl.findinventory("HD10mMag30")));
            if(nextmagloaded>30){
                sb.drawimage("CWNMA0",(-46,-3),sb.DI_SCREEN_CENTER_BOTTOM);
            }else if(nextmagloaded<1){
                sb.drawimage("CWNMB0",(-46,-3),sb.DI_SCREEN_CENTER_BOTTOM,alpha:nextmagloaded?0.6:1.);
            }else sb.drawbar(
                "CWNMA0","CWNMGREY",
                nextmagloaded,30,
                (-46,-3),-1,
                sb.SHADER_VERT,sb.DI_SCREEN_CENTER_BOTTOM
            );
			sb.drawnum(hpl.countinv("HD10mMag30"),-43,-8,sb.DI_SCREEN_CENTER_BOTTOM);
			if(!(hdw.weaponstatus[0]&CUWF_NOSHOTGUN)){
				sb.drawimage("4GSIA0",(-62,-4),sb.DI_SCREEN_CENTER_BOTTOM,scale:(0.6,0.6));
				sb.drawnum(hpl.countinv("HD4GBAmmo"),-56,-8,sb.DI_SCREEN_CENTER_BOTTOM);
			}
		}

		if(!(hdw.weaponstatus[0]&CURWF_NOFIRESELECT))
		sb.drawwepcounter(hdw.weaponstatus[CURWS_AUTO],
			-22,-10,"RBRSA3A7","STFULAUT","STBURAUT"
		);
		if(hdw.weaponstatus[0]&CURWF_4GAUGELOADED)sb.drawrect(-20,-14,4,2.6);
		int lod=clamp(hdw.weaponstatus[CURWS_MAG]%100,0,30);
		sb.drawwepnum(lod,30);
		if(hdw.weaponstatus[0]&CURWF_CHAMBER){
			sb.drawrect(-19,-10,3,1);
			lod++;
		}
		if(hdw.weaponstatus[CURWS_MAG]>100)lod=random[shitgun](10,99);
		sb.drawnum(lod,-16,-22,sb.DI_SCREEN_CENTER_BOTTOM|sb.DI_TEXT_ALIGN_RIGHT,Font.CR_RED);
		/*if(hdw.weaponstatus[0]&CUWF_SHOTMODE){
			DrawRifleGrenadeStatus(sb,hdw);
		}*/
	}
	override string gethelptext(){
		bool gl=!(weaponstatus[0]&CUWF_NOSHOTGUN);
		bool glmode=gl&&(weaponstatus[0]&CUWF_SHOTMODE);
		LocalizeHelp();
		return
		LWPHELP_FIRESHOOT
		..(gl?(LWPHELP_ALTFIRE..(glmode?(StringTable.Localize("$ZMWH_ALTFIRE1")):(StringTable.Localize("$ZMWH_ALTFIRE2")))):"")
		..LWPHELP_RELOAD..StringTable.Localize("$ZMWH_RELOAD")
		..(gl?(LWPHELP_ALTRELOAD..StringTable.Localize("$ZMWH_ALTRELOAD")):"")
		..(glmode?(LWPHELP_FIREMODE.."+"..LWPHELP_UPDOWN..StringTable.Localize("$ZMWH_FMODPUD"))
			:(
			((weaponstatus[0]&CURWF_NOFIRESELECT)?"":LWPHELP_FIREMODE..StringTable.Localize("$ZMWH_FMODE"))
			..LWPHELP_ZOOM.."+"..LWPHELP_FIREMODE.."+"..LWPHELP_UPDOWN..StringTable.Localize("$ZMWH_ZPFMOD")))
		..LWPHELP_MAGMANAGER
		..LWPHELP_UNLOAD..StringTable.Localize("$ZMWH_UNLOAD")..(glmode?StringTable.Localize("$ZMWH_GL"):StringTable.Localize("$ZMWH_MAG"))
		;
	}
	override void DrawSightPicture(
		HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl,
		bool sightbob,vector2 bob,double fov,bool scopeview,actor hpc
	){
		int scaledyoffset=47;
		if(hdw.weaponstatus[0]&CUWF_SHOTMODE){
			int cx,cy,cw,ch;
			[cx,cy,cw,ch]=screen.GetClipRect();
			sb.SetClipRect(
				-16+bob.x,-32+bob.y,32,40,
				sb.DI_SCREEN_CENTER
			);
			vector2 bobb=bob*1.1;
			sb.drawimage(
				"frntsite",(0,0)+bobb,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP,
				scale:(0.8,1.1)
			);
			sb.SetClipRect(cx,cy,cw,ch);

			sb.drawimage(
				"sgbaksit",(0,0)+bob,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP,
				alpha:0.9,
				scale:(1.7,1.0)
			);
		}
		else{
			double dotoff=max(abs(bob.x),abs(bob.y));
			if(dotoff<40){
				string whichdot=sb.ChooseReflexReticle(hdw.weaponstatus[CURWS_DOT]);
				sb.drawimage(
					whichdot,(0,0)+bob*1.1,sb.DI_SCREEN_CENTER|sb.DI_ITEM_CENTER,
					alpha:0.8-dotoff*0.01,
					col:0xFF000000|sb.crosshaircolor.GetInt()
				);
			}
			sb.drawimage(
				"z66site",(0,0)+bob,sb.DI_SCREEN_CENTER|sb.DI_ITEM_CENTER
			);
		}
	}
    //returns the power of the load just fired
    static double FireShell(actor caller){
        double shotpower=1.0;
        HDBulletActor.FireBullet(caller,"HDB_4wad");
        let p=HDBulletActor.FireBullet(caller,"HDB_400",spread:6.0,speedfactor:frandom(0.94,1.02),amount:40);
        caller.A_StartSound("weapons/cur4gaugeshot",9,CHANF_DEFAULT);
        return shotpower;
    }
	override void SetReflexReticle(int which){weaponstatus[CURWS_DOT]=which;}
	override double weaponbulk(){
		double blx=97;
		if(!(weaponstatus[0]&CUWF_NOSHOTGUN)){
			blx+=19;
			if(weaponstatus[0]&CURWF_4GAUGELOADED)blx+=ENC_4GBLOADED;
		}
		int mgg=weaponstatus[CURWS_MAG];
		return blx+(mgg<0?0:(ENC_10MAG_LOADED+mgg*ENC_10_LOADED));
	}
	override void failedpickupunload(){
		failedpickupunloadmag(CURWS_MAG,"HD10mMag30");
	}
	override void DropOneAmmo(int amt){
		if(owner){
			amt=clamp(amt,1,10);
			if(owner.countinv("HD10mAmmo"))owner.A_DropInventory("HD10mAmmo",amt*30);
			else{
				double angchange=(weaponstatus[0]&CUWF_NOSHOTGUN)?0:-10;
				if(angchange)owner.angle-=angchange;
				owner.A_DropInventory("HD10mMag30",amt);
				if(angchange){
					owner.angle+=angchange*2;
					owner.A_DropInventory("HD4GBAmmo",amt);
					owner.angle-=angchange;
				}
			}
		}
	}
	override void ForceBasicAmmo(){
		owner.A_TakeInventory("HD10mAmmo");
		if(weaponstatus[0]&CUWF_NOSHOTGUN)hdammotype2=null;
		else owner.A_SetInventory("HD4GBAmmo",1);
		ForceOneBasicAmmo("HD10mMag30");
	}
	action bool brokenround(){
		if(!(invoker.weaponstatus[CURWS_FLAGS]&CURWF_CHAMBERBROKEN)){
			int hht=invoker.weaponstatus[CURWS_HEAT];
			if(hht>140)invoker.weaponstatus[CURWS_BORESTRETCHED]++;
			hht*=hht;hht>>=10;
			int rnd=
				(invoker.owner?1:10)
				+max(invoker.weaponstatus[CURWS_AUTO],hht)
				+invoker.weaponstatus[CURWS_BORESTRETCHED]
				+(invoker.weaponstatus[CURWS_MAG]>100?10:0);
			if(random(0,250)<rnd){
				invoker.weaponstatus[CURWS_FLAGS]|=CURWF_CHAMBERBROKEN;
			}
		}return invoker.weaponstatus[CURWS_FLAGS]&CURWF_CHAMBERBROKEN;
	}
	states{
	ready:
		CURW A 1{
			A_WeaponReady(WRF_ALL);
			if(invoker.weaponstatus[CURWS_AUTO]>2)invoker.weaponstatus[CURWS_AUTO]=2;
		}goto readyend;
	firemode:
		CURW A 1{
			if(invoker.weaponstatus[0]&CURWF_NOFIRESELECT){
				invoker.weaponstatus[CURWS_AUTO]=0;
				return;
			}
			if(invoker.weaponstatus[CURWS_AUTO]>=2)invoker.weaponstatus[CURWS_AUTO]=0;
			else invoker.weaponstatus[CURWS_AUTO]++;
			A_WeaponReady(WRF_NOFIRE);
		}goto nope;


	select0:
		CURW A 0{
			A_CheckDefaultReflexReticle(CURWS_DOT);
			if(!countinv("NulledWeapon"))invoker.weaponstatus[0]&=~CUWF_SHOTMODE;
			if(invoker.weaponstatus[0]&CUWF_NOSHOTGUN){
				invoker.weaponstatus[0]&=~CURWF_4GAUGELOADED;
				setweaponstate("select0small");
			}
		}goto select0big;
	deselect0:
		CURW A 0{
			if(invoker.weaponstatus[0]&CUWF_NOSHOTGUN)setweaponstate("deselect0small");
		}goto deselect0big;
	flash:
		CURW F 1 bright{
            int heat = min(50, invoker.weaponStatus[CURWS_HEAT]);
			A_Light1();
			HDFlashAlpha(-16);
			A_StartSound("weapons/currawong",CHAN_WEAPON);
			A_ZoomRecoil(max(0.95,1.-0.05*min(invoker.weaponstatus[CURWS_AUTO],3)));

			double brnd=max(invoker.weaponstatus[CURWS_HEAT],invoker.weaponstatus[CURWS_BORESTRETCHED])*0.01;
			let bbb=HDBulletActor.FireBullet(self,"HDB_10",speedfactor:frandom(1.13,1.31),spread:brnd>1.2?brnd:0);

			A_MuzzleClimb(
				-frandom(0.1,0.1),-frandom(0,0.1),
				-0.2,-frandom(0.3,0.4),
				-frandom(0.4,1.4),-frandom(1.3,2.6)
			);

            A_EjectCasing("HDSpent10mm",
                frandom(-1,2),
                (frandom(0.2,0.3),-frandom(7,7.5),frandom(0,0.2)),
                (0,0,-2)
            );

			invoker.weaponstatus[CURWS_FLAGS]&=~CURWF_CHAMBER;
			invoker.weaponstatus[CURWS_HEAT]+=random(3,5);
			A_AlertMonsters(HDCONST_ONEMETRE * (22 + heat));
		}
		goto lightdone;


	fire:
		CURW A 2{
			if(invoker.weaponstatus[CURWS_FLAGS]&CUWF_SHOTMODE)setweaponstate("firefrag");
			else if(invoker.weaponstatus[CURWS_AUTO]>0)A_SetTics(3);
		}goto shootgun;
	hold:
		CURW A 0 A_JumpIf(invoker.weaponstatus[0]&CUWF_SHOTMODE,"FireFrag");
		CURW A 0 A_JumpIf(invoker.weaponstatus[0]&CURWF_NOFIRESELECT,"nope");
		CURW A 0 A_JumpIf(invoker.weaponstatus[CURWS_AUTO]>4,"nope");
		CURW A 0 A_JumpIf(invoker.weaponstatus[CURWS_AUTO],"shootgun");
	althold:
		---- A 0 A_Refire();
		goto ready;
	jam:
		CURW B 1 offset(-1,36){
			A_StartSound("weapons/currawongjam",CHAN_WEAPON,CHANF_OVERLAP);
			invoker.weaponstatus[0]|=CURWF_CHAMBERBROKEN;
			invoker.weaponstatus[CURWS_FLAGS]&=~CURWF_CHAMBER;
		}
		CURW B 1 offset(1,30) A_StartSound("weapons/currawongjam",CHAN_WEAPON,CHANF_OVERLAP);
		goto nope;

	shootgun:
		CURW A 1{
			if(invoker.weaponstatus[CURWS_AUTO]>0)
			{
				A_SetTics((invoker.WeaponStatus[CURWS_WEIRDFIRE]*invoker.WeaponStatus[CURWS_HEAT]/5)+1);
                if(invoker.WeaponStatus[CURWS_WEIRDFIRE]<2)invoker.WeaponStatus[CURWS_WEIRDFIRE]++;
                else invoker.WeaponStatus[CURWS_WEIRDFIRE]--;
			}
			if(
				//can neither shoot nor chamber
				invoker.weaponstatus[0]&CURWF_CHAMBERBROKEN
				||(
					!(invoker.weaponstatus[CURWS_FLAGS]&CURWF_CHAMBER)
					&&invoker.weaponstatus[CURWS_MAG]<1
				)
			){
				setweaponstate("nope");
			}else if(!(invoker.weaponstatus[CURWS_FLAGS]&CURWF_CHAMBER)){
				//no shot but can chamber
				setweaponstate("chamber_manual");
			}else{
				A_GunFlash();
				A_WeaponReady(WRF_NOFIRE);
				if(invoker.weaponstatus[CURWS_AUTO]>=2)invoker.weaponstatus[CURWS_AUTO]++;
			}
		}
	chamber:
		CURW B 0 offset(0,32){
			if(invoker.weaponstatus[CURWS_MAG]<1){
				setweaponstate("nope");
				return;
			}
			if(invoker.weaponstatus[CURWS_MAG]%100>0){
				if(invoker.weaponstatus[CURWS_MAG]==31)invoker.weaponstatus[CURWS_MAG]=30;
				invoker.weaponstatus[CURWS_MAG]--;
				invoker.weaponstatus[CURWS_FLAGS]|=CURWF_CHAMBER;
			}else{
				invoker.weaponstatus[CURWS_MAG]=min(invoker.weaponstatus[CURWS_MAG],0);
				A_StartSound("weapons/currawongchamber",CHAN_WEAPON,CHANF_OVERLAP);
			}
			if(brokenround()){
				setweaponstate("jam");
				return;
			}
			A_WeaponReady(WRF_NONE);
		}
		CURW B 0 A_JumpIf(invoker.weaponstatus[CURWS_AUTO]<1,"nope");
		CURW B 0 A_JumpIf(invoker.weaponstatus[CURWS_AUTO]>4,"nope");
		CURW B 2 A_JumpIf(invoker.weaponstatus[CURWS_AUTO]>1,1);
		CURW B 0 A_Refire();
		goto ready;

	user3:
		CURW A 0 A_MagManager("HD10mMag30");
		goto ready;

	user4:
	unload:
		CURW A 0{
			invoker.weaponstatus[CURWS_FLAGS]|=CURWF_UNLOADONLY;
			if(
				invoker.weaponstatus[CURWS_FLAGS]&CUWF_SHOTMODE
			){
				setweaponstate("unloadgrenade");
			}else if(
				invoker.weaponstatus[CURWS_MAG]>=0
			){
				setweaponstate("unloadmag");
			}else if(
				invoker.weaponstatus[CURWS_FLAGS]&CURWF_CHAMBER
				||invoker.weaponstatus[CURWS_FLAGS]&CURWF_CHAMBERBROKEN
			){
				setweaponstate("unloadchamber");
			}else{
				setweaponstate("unloadmag");
			}
		}
	reload:
		CURW A 0{
			invoker.weaponstatus[CURWS_FLAGS]&=~CURWF_UNLOADONLY;
			if(	//full mag, no jam, not unload-only - why hit reload at all?
				!(invoker.weaponstatus[0]&CURWF_CHAMBERBROKEN)
				&&invoker.weaponstatus[CURWS_MAG]%100>=30
				&&!(invoker.weaponstatus[CURWS_FLAGS]&CURWF_UNLOADONLY)
			){
				setweaponstate("nope");
			}else if(	//if jammed, treat as unloading
				invoker.weaponstatus[CURWS_MAG]<0
				&&invoker.weaponstatus[0]&CURWF_CHAMBERBROKEN
			){
				invoker.weaponstatus[CURWS_FLAGS]|=CURWF_UNLOADONLY;
				setweaponstate("unloadchamber");
			}else if(!HDMagAmmo.NothingLoaded(self,"HD10mMag30")){
				setweaponstate("unloadmag");
			}
		}goto nope;
	unloadmag:
		CURW A 1 offset(0,33);
		CURW A 1 offset(-3,34);
		CURW A 1 offset(-8,37);
		CURW B 2 offset(-11,39){
			if(	//no mag, skip unload
				invoker.weaponstatus[CURWS_MAG]<0
			){
				setweaponstate("magout");
			}
			if(invoker.weaponstatus[0]&CURWF_CHAMBERBROKEN)
				invoker.weaponstatus[CURWS_FLAGS]|=CURWF_UNLOADONLY;
			A_MuzzleClimb(-0.3,-0.3,wepdot:false);
			A_StartSound("weapons/currawongmagmove",CHAN_WEAPON,CHANF_OVERLAP);
		}
		CURW B 4 offset(-12,40){
			A_MuzzleClimb(-0.3,-0.3,wepdot:false);
			A_StartSound("weapons/currawongmagout",CHAN_WEAPON);
		}
		CURW B 20 offset(-14,44){
			int inmag=invoker.weaponstatus[CURWS_MAG];
			if(inmag>31)inmag=min(30,inmag%100);
			invoker.weaponstatus[CURWS_MAG]=-1;
			if(
				!PressingUnload()&&!PressingReload()
				||A_JumpIfInventory("HD10mMag30",0,"null")
			){
				HDMagAmmo.SpawnMag(self,"HD10mMag30",inmag);
				A_SetTics(1);
			}else{
				HDMagAmmo.GiveMag(self,"HD10mMag30",inmag);
				A_StartSound("weapons/pocket",CHAN_WEAPON);
				if(inmag<31)A_Log(StringTable.Localize("$10MMAGMSG"),true);
			}
		}
	magout:
		CURW B 0{
			if(
				invoker.weaponstatus[CURWS_FLAGS]&CURWF_UNLOADONLY
				||!countinv("HD10mMag30")
			)setweaponstate("reloadend");
		} //fallthrough to loadmag
	loadmag:
		---- A 12 offset(-15,44){
			let zmag=HD10mMag30(findinventory("HD10mMag30"));
			if(!zmag){setweaponstate("reloadend");return;}
			A_StartSound("weapons/pocket",CHAN_WEAPON);
			if(zmag.DirtyMagsOnly())invoker.weaponstatus[0]|=CURWF_LOADINGDIRTY;
			else{
				invoker.weaponstatus[0]&=~CURWF_LOADINGDIRTY;
				A_SetTics(10);
			}
		}
		---- A 2 offset(-15,44) A_JumpIf(invoker.weaponstatus[0]&CURWF_LOADINGDIRTY,"loadmagdirty");
	loadmagclean:
		CURW B 8 offset(-15,45)A_StartSound("weapons/currawongmagin",CHAN_WEAPON);
		CURW B 1 offset(-14,44){
			let zmag=HD10mMag30(findinventory("HD10mMag30"));
			if(!zmag){setweaponstate("reloadend");return;}
			if(zmag.DirtyMagsOnly()){
				setweaponstate("loadmagdirty");
				return;
			}
			invoker.weaponstatus[CURWS_MAG]=zmag.TakeMag(true);
			A_StartSound("weapons/rifleclick2",CHAN_WEAPON);
		}goto reloadend;
	loadmagdirty:
		CURW B 0{
			if(PressingReload())invoker.weaponstatus[0]|=CURWF_STILLPRESSINGRELOAD;
			else invoker.weaponstatus[0]&=~CURWF_STILLPRESSINGRELOAD;
		}
		CURW B 3 offset(-15,45)A_StartSound("weapons/currawongmagin",CHAN_WEAPON);
		CURW B 1 offset(-15,42)A_WeaponMessage(StringTable.Localize("$CUR10MMAGMSG"),70);
		CURW BBBBBBBAAAA 1 offset(-15,41){
			bool prr=PressingReload();
			if(
				prr
				&&!(invoker.weaponstatus[0]&CURWF_STILLPRESSINGRELOAD)
			){
				setweaponstate("reallyloadmagdirty");
			}
			else if(!PressingReload())invoker.weaponstatus[0]&=~CURWF_STILLPRESSINGRELOAD;
		}
		goto nope;
	reallyloadmagdirty:
		CURW B 1 offset(-14,44)A_StartSound("weapons/currawongmagmove",CHAN_WEAPON);
		CURW A 8 offset(-18,50){
			let zmag=HD10mMag30(findinventory("HD10mMag30"));
			if(!zmag){setweaponstate("reloadend");return;}
			invoker.weaponstatus[CURWS_MAG]=zmag.TakeMag(true)+100;
			A_MuzzleClimb(
				-frandom(0.4,0.6),frandom(2.,3.)
				-frandom(0.2,0.3),frandom(1.,1.6),
				wepdot:false
			);
			A_StartSound("weapons/currawongmagmove",CHAN_WEAPON,CHANF_OVERLAP);
			A_StartSound("weapons/smack",CHAN_WEAPON,CHANF_OVERLAP);

			string realmessage=StringTable.Localize("$10MMAGMSG");
			realmessage=realmessage.left(random(13,20));
			realmessage.appendformat(StringTable.Localize("$ZMRELERROR")..random(0,9999)..StringTable.Localize("$ZMNOCARRIER"));
			A_WeaponMessage(realmessage,70);
		}
		CURW A 4 offset(-17,49);
		goto chamber_manual;

	reloadend:
		CURW B 2 offset(-11,39);
		CURW A 1 offset(-8,37) A_MuzzleClimb(frandom(0.2,-2.4),frandom(0.2,-1.4),wepdot:false);
		CURW A 1 offset(-3,34);
		goto chamber_manual;

	chamber_manual:
		CURW A 0 A_JumpIf(invoker.weaponstatus[CURWS_FLAGS]&CURWF_CHAMBER,"nope");
		CURW A 3 offset(-1,36)A_WeaponBusy();
		CURW B 4 offset(-3,42){
			if(!invoker.weaponstatus[CURWS_MAG]%100)invoker.weaponstatus[CURWS_MAG]=0;
			if(
				!(invoker.weaponstatus[CURWS_FLAGS]&CURWF_CHAMBER)
				&& !(invoker.weaponstatus[CURWS_FLAGS]&CURWF_CHAMBER)
				&& invoker.weaponstatus[CURWS_MAG]%100>0
			){
				A_StartSound("weapons/currawongchamber",CHAN_WEAPON);
				if(invoker.weaponstatus[CURWS_MAG]==31)invoker.weaponstatus[CURWS_MAG]=29;
				else invoker.weaponstatus[CURWS_MAG]--;
				invoker.weaponstatus[CURWS_FLAGS]|=CURWF_CHAMBER;
				brokenround();
			}else setweaponstate("nope");
		}
		CURW A 2 offset(-1,36);
		CURW A 0 offset(0,34);
		goto nope;


	unloadchamber:
		CURW A 1 offset(-3,34);
		CURW A 1 offset(-9,39);
		CURW B 3 offset(-19,44) A_MuzzleClimb(frandom(-0.4,0.4),frandom(-0.4,0.4),wepdot:false);
		CURW A 2 offset(-16,42){
			A_MuzzleClimb(frandom(-0.4,0.4),frandom(-0.4,0.4),wepdot:false);
			if(
				invoker.weaponstatus[CURWS_FLAGS]&CURWF_CHAMBER
				&&!(invoker.weaponstatus[0]&CURWF_CHAMBERBROKEN)
			){
				A_SpawnItemEx("HDCrushed10mm",0,0,20,
					random(4,7),random(-2,2),random(-2,1),0,
					SXF_NOCHECKPOSITION
				);
				invoker.weaponstatus[CURWS_FLAGS]&=~CURWF_CHAMBER;
				A_StartSound("weapons/currawongmagmove",CHAN_WEAPON,CHANF_OVERLAP);
			}else if(!random(0,4)){
				invoker.weaponstatus[0]&=~CURWF_CHAMBERBROKEN;
				invoker.weaponstatus[CURWS_FLAGS]&=~CURWF_CHAMBER;
				A_StartSound("weapons/currawongchamber",CHAN_WEAPON,CHANF_OVERLAP);
				for(int i=0;i<5;i++)A_SpawnItemEx("HDSpent10mm",0,0,20,
					random(4,7),random(-2,2),random(-2,1),0,SXF_NOCHECKPOSITION
				);
				if(!random(0,5))A_SpawnItemEx("HDSmokeChunk",12,0,gunheight()-10,4,frandom(-2,2),frandom(2,4));
			}else if(invoker.weaponstatus[0]&CURWF_CHAMBERBROKEN){
				A_StartSound("weapons/smack",CHAN_WEAPON,CHANF_OVERLAP);
			}
		}goto reloadend;

    firefrag:
        #### B 2{
            if(!(invoker.weaponstatus[CURWS_FLAGS]&CURWF_4GAUGELOADED)){
                setweaponstate("nope");
                return;
            }
            invoker.FireShell(Self);
            invoker.weaponstatus[CURWS_FLAGS]&=~CURWF_4GAUGELOADED;
            A_StartSound("weapons/cur4gshot",CHAN_WEAPON);
        }
        #### B 3{
            A_ZoomRecoil(0.95);
            A_MuzzleClimb(-frandom(5.5, 10.25), -frandom(9.5, 11.75), -frandom(8.5, 10.25), -frandom(9.5, 11.75));
            if(!gunbraced()){
                A_ChangeVelocity(cos(pitch)*-frandom(0.375,0.75),0,sin(pitch)*frandom(0.375,0.75),CVF_RELATIVE);
            }
            A_ChangeVelocity(cos(pitch)*-frandom(0.125,0.25),0,sin(pitch)*frandom(0.125,0.25),CVF_RELATIVE);
            GiveBody (max(0,11-health));
            DamageMobJ (invoker, self, 10, "bashing");
        }
        goto nope;


	altfire:
		CURW A 1 offset(0,34){
			if(invoker.weaponstatus[0]&CUWF_NOSHOTGUN)return;
			invoker.weaponstatus[0]^=CUWF_SHOTMODE;
			A_SetCrosshair(21);
			A_SetHelpText();
		}goto nope;


	altreload:
		CURW A 0{
			invoker.weaponstatus[CURWS_FLAGS]&=~CURWF_UNLOADONLY;
			if(
				!(invoker.weaponstatus[CURWS_FLAGS]&CUWF_NOSHOTGUN)
				&&!(invoker.weaponstatus[CURWS_FLAGS]&CURWF_4GAUGELOADED)
				&&countinv("HD4GBAmmo")
			)setweaponstate("unloadgrenade");
		}goto nope;
	unloadgrenade:
		CURW B 0{
			A_SetCrosshair(21);
			A_MuzzleClimb(-0.3,-0.3,wepdot:false);
		}
		CURW B 2 offset(0,34);
		CURW B 1 offset(4,38){
			A_MuzzleClimb(-0.3,-0.3,wepdot:false);
		}
		CURW B 2 offset(8,48){
			A_StartSound("weapons/cur4gaugeopen",CHAN_WEAPon,CHANF_OVERLAP);
			A_MuzzleClimb(-0.3,-0.3,wepdot:false);
			if(invoker.weaponstatus[CURWS_FLAGS]&CURWF_4GAUGELOADED)A_StartSound("weapons/cur4gaugereload",CHAN_WEAPON);
		}
		CURW B 10 offset(10,49){
			if(!(invoker.weaponstatus[CURWS_FLAGS]&CURWF_4GAUGELOADED)){
				if(!(invoker.weaponstatus[CURWS_FLAGS]&CURWF_UNLOADONLY))A_SetTics(3);
				return;
			}
			invoker.weaponstatus[CURWS_FLAGS]&=~CURWF_4GAUGELOADED;
			if(
				!PressingUnload()
				||A_JumpIfInventory("HD4GBAmmo",0,"null")
			){
				A_SpawnItemEx("HD4GBAmmo",
					cos(pitch)*10,0,gunheight()-2-10*sin(pitch),vel.x,vel.y,vel.z,0,
					SXF_ABSOLUTEMOMENTUM|SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH
				);
			}else{
				A_StartSound("weapons/pocket",CHAN_WEAPON,CHANF_OVERLAP);
				A_GiveInventory("HD4GBAmmo",1);
				A_MuzzleClimb(frandom(0.8,-0.2),frandom(0.4,-0.2),wepdot:false);
			}
		}
		CURW B 0 A_JumpIf(invoker.weaponstatus[CURWS_FLAGS]&CURWF_UNLOADONLY,"greloadend");
	loadgrenade:
		CURW B 4 offset(10,50) A_StartSound("weapons/pocket",CHAN_WEAPON,CHANF_OVERLAP);
		CURW BBB 8 offset(10,50) A_MuzzleClimb(frandom(-0.2,0.8),frandom(-0.2,0.4),wepdot:false);
		CURW B 18 offset(8,50){
			if(!countinv("HD4GBAmmo"))return;
			A_TakeInventory("HD4GBAmmo",1,TIF_NOTAKEINFINITE);
			invoker.weaponstatus[CURWS_FLAGS]|=CURWF_4GAUGELOADED;
			A_StartSound("weapons/cur4gaugereload",CHAN_WEAPON);
		}
	greloadend:
		CURW B 4 offset(4,44) A_StartSound("weapons/cur4gaugeopen",CHAN_WEAPON);
		CURW B 1 offset(0,40);
		CURW A 1 offset(0,34) A_MuzzleClimb(frandom(-2.4,0.2),frandom(-1.4,0.2),wepdot:false);
		goto nope;

	spawn:
		RIFL DCBA 0;
		RIGL DCBA 0;
		RIFS DCBA 0;
		RIGS DA 0;
		---- A 0{
			//don't jam just because
			if(
				!(invoker.weaponstatus[0]&CURWF_CHAMBER)
				&&!(invoker.weaponstatus[0]&CURWF_CHAMBERBROKEN)
				&&invoker.weaponstatus[CURWS_MAG]>0
				&&invoker.weaponstatus[CURWS_MAG]<31
			){
				invoker.weaponstatus[CURWS_MAG]--;
				invoker.weaponstatus[0]|=CURWF_CHAMBER;
				brokenround();
			}
		}
	spawn2:
		---- A -1{
			//set sprite
			if(invoker.weaponstatus[0]&CUWF_NOSHOTGUN){
				if(invoker.weaponstatus[0]&CURWF_NOFIRESELECT)
					sprite=getspriteindex("RIFSA0");
				else sprite=getspriteindex("RIFLA0");
			}else{
				if(invoker.weaponstatus[0]&CURWF_NOFIRESELECT)
					sprite=getspriteindex("RIGSA0");
				else sprite=getspriteindex("RIGLA0");
			}

			//set to no-mag frame
			if(invoker.weaponstatus[CURWS_MAG]<0){
				frame=3;
			}
		}
	}

	override inventory CreateTossable(int amt){
		let owner=self.owner;
		let zzz=HDCurrawong(super.createtossable());
		if(!zzz)return null;
		zzz.target=owner;
		return zzz;
	}

	override void InitializeWepStats(bool idfa){
		if(!(weaponstatus[0]&CUWF_NOSHOTGUN))weaponstatus[0]|=CURWF_4GAUGELOADED;
		weaponstatus[CURWS_MAG]=31;
		if(!idfa && !owner){
			weaponstatus[CURWS_AUTO]=0;
			weaponstatus[CURWS_HEAT]=0;
		}
		if(idfa)weaponstatus[0]&=~CURWF_CHAMBERBROKEN;
	}
	override void loadoutconfigure(string input){
		int noshot=getloadoutvar(input,"noshot",1);
		if(!noshot){
			weaponstatus[0]&=~CUWF_NOSHOTGUN;
		}else if(noshot>0){
			weaponstatus[0]|=CUWF_NOSHOTGUN;
			weaponstatus[0]&=~CURWF_4GAUGELOADED;
		}
		if(!(weaponstatus[0]&CUWF_NOSHOTGUN)){
			weaponstatus[0]|=CURWF_4GAUGELOADED;
			hdammotype2=null;
		}
		int xhdot=getloadoutvar(input,"dot",3);
		if(xhdot>=0)weaponstatus[CURWS_DOT]=xhdot;

		int semi=getloadoutvar(input,"semi",1);
		if(semi>0){
			weaponstatus[CURWS_AUTO]=-1;
			weaponstatus[0]|=CURWF_NOFIRESELECT;
		}else{
			int firemode=getloadoutvar(input,"firemode",1);
			if(firemode>=0){
				weaponstatus[0]&=~CURWF_NOFIRESELECT;
				weaponstatus[CURWS_AUTO]=clamp(firemode,0,2);
			}
		}
		if(
			!(weaponstatus[0]&CURWF_CHAMBER)
			&&weaponstatus[CURWS_MAG]>0
		){
			weaponstatus[0]|=CURWF_CHAMBER;
			if(weaponstatus[CURWS_MAG]==31)weaponstatus[CURWS_MAG]=29;
			else weaponstatus[CURWS_MAG]--;
		}
	}
}
enum currawongstatus{
	CURWF_CHAMBER=1,
	CURWF_CHAMBERBROKEN=2,
	CURWF_DIRTYMAG=4,
	CURWF_4GAUGELOADED=8,
	CUWF_NOSHOTGUN=16,
	CURWF_NOFIRESELECT=32,
	CUWF_SHOTMODE=64,
	CURWF_UNLOADONLY=128,
	CURWF_STILLPRESSINGRELOAD=256,
	CURWF_LOADINGDIRTY=512,

	CURWS_FLAGS=0,
	CURWS_MAG=1, //-1 is empty
	CURWS_AUTO=2, //2 is burst, 2-5 counts ratchet
	CURWS_HEAT=3,
	CURWS_BORESTRETCHED=4,
	CURWS_DOT=5,
	CURWS_WEIRDFIRE=6,
};

class HDCurrawongRandom:IdleDummy{
	states{
	spawn:
		TNT1 A 0 nodelay{
			let zzz=HDCurrawong(spawn("HDCurrawong",pos,ALLOW_REPLACE));
			if(!zzz)return;
			zzz.special=special;
			for(int i=0;i<5;i++)zzz.args[i]=args[i];
			if(!random(0,2)){
				zzz.weaponstatus[0]|=CUWF_NOSHOTGUN;
				if(!random(0,3))zzz.weaponstatus[0]|=CURWF_NOFIRESELECT;
			}
			if(zzz.weaponstatus[0]&CUWF_NOSHOTGUN){
				spawn("HD10mMag30",pos+(7,0,0),ALLOW_REPLACE);
				spawn("HD10mMag30",pos+(5,0,0),ALLOW_REPLACE);
			}else{
				spawn("HD4GBAmmo",pos+(10,0,0),ALLOW_REPLACE);
				spawn("HD4GBAmmo",pos+(8,0,0),ALLOW_REPLACE);
				spawn("HD10mMag30",pos+(5,0,0),ALLOW_REPLACE);
			}
		}stop;
	}
}

class HD10mMag30:HDMagAmmo{
    default{
        //$Category "Ammo/Hideous Destructor/"
        //$Title "4.26mm UAC Standard Mag"
        //$Sprite "CLIPB0"

        hdmagammo.maxperunit 31;  //NOTE: *only* the guns do the "+100 for dirty mag" thing
        hdmagammo.roundtype "HD10mAmmo";
        hdmagammo.roundbulk ENC_10_LOADED;
        hdmagammo.magbulk ENC_10MAG_EMPTY;
        hdmagammo.extracttime 4;

        tag "$TAG_10M30MAG";
        hdpickup.refid HDLD_CURRAWONGMAG;
        inventory.pickupmessage "$PICKUP_10M30MAG";
    }
    override void postbeginplay(){
        super.postbeginplay();
        sealtimer=0;
        breakchance=0;
    }
    int breakchance;
    int sealtimer;
    bool reseal;
    override void doeffect(){
        if(sealtimer>0)sealtimer--;
        if(breakchance>0)breakchance--;
        super.doeffect();
        reseal = owner && owner.player && owner.player.cmd.buttons&BT_USE;
    }
    override string pickupmessage(){
        string pms=super.pickupmessage();
        if(mags[0]<31)pms.appendformat(" %s",StringTable.Localize("$10MMAGMSG"));
        return pms;
    }
    override string,string,name,double getmagsprite(int thismagamt){
        string magsprite;
        if(thismagamt>=31)magsprite="CWNMA0";
        else if(thismagamt>0)magsprite="CWNMB0";
        else magsprite="CWNMC0";
        return magsprite,"PBRSA0","HD10mAmmo",0.6;
    }
    override int GetMagHudCount(int input){
        if(input==31)return 30;
        return input;
    }
    bool DirtyMagsOnly(){
        if(mags.size()!=amount)return false;
        for(int i=0;i<amount;i++){
            if(mags[i]>=31)return false;
        }
        return true;
    }
    override void DrawRoundCount(HDStatusBar sb,HDPlayerPawn hpl,name roundsprite,double scl,int offx,int offy,MagManager magman){
		offx+=40;
		scl=1.6;
		sb.drawstring(
			sb.pSmallFont,sb.FormatNumber(hpl.countinv(roundtype)),
			(offx+2,offy),sb.DI_SCREEN_CENTER|sb.DI_TEXT_ALIGN_LEFT,
			font.CR_BROWN
		);


		if(!!magman){
			int rounddir=magman.weaponstatus[MMSS_ROUNDDIR];
			if(rounddir!=0){
				int broffx=offx;
				int broffy=offy;
				if(rounddir<0)broffx+=rounddir;
				else broffx=rounddir+offx-40;
				if(bseesdaggers){
					broffy+=20;
					if(
						rounddir<-20
						||(
							rounddir>0
							&&rounddir<20
						)
					){
						broffy+=((broffx-offx)>>1);
					}
				}
				broffy+=abs(abs(rounddir)-20)-20;
				sb.drawimage(roundsprite,(broffx,broffy),
					sb.DI_SCREEN_CENTER|sb.DI_ITEM_RIGHT_TOP,
					scale:(scl,scl)
				);
			}
		}

		sb.drawimage(roundsprite,(offx,offy),
			sb.DI_SCREEN_CENTER|sb.DI_ITEM_RIGHT_TOP,
			scale:(scl,scl)
		);
		if(!!hpl.countinv("MM_4mmSealant")){
			offy+=14;
			sb.drawstring(
				sb.pSmallFont,sb.FormatNumber(hpl.countinv("MM_4mmSealant")).." \cu[Use] Reseal Full Mag",
				(offx+2,offy),sb.DI_SCREEN_CENTER|sb.DI_TEXT_ALIGN_LEFT,
				font.CR_BROWN
			);
			sb.drawimage("SEALA0",(offx,offy),
				sb.DI_SCREEN_CENTER|sb.DI_ITEM_RIGHT_TOP,
				scale:(scl,scl)
			);
		}
	}
    override bool Extract(){
        SyncAmount();
        int mindex=mags.size()-1;
        if(
            mags.size()<1
            ||mags[mindex]<1
            ||owner.A_JumpIfInventory(roundtype,0,"null")
        )return false;
        if(mags[mindex]==31){
            if(sealtimer<1){
                owner.A_Log(string.format(StringTable.Localize("$426MAGREALLY"),StringTable.Localize("$10MMAGMSG")),true);
                sealtimer=10;
                extracttime=9;
                return false;
            }else{
                mags[mindex]=30;
                extracttime=12;
                owner.A_StartSound("magmanager/426open",CHAN_WEAPON,CHANF_OVERLAP);
                return false;
            }
        }else extracttime=default.extracttime;
        int totake=min(random(1,9),mags[mindex]);
        if(totake<HDPickup.MaxGive(owner,roundtype,roundbulk))HDF.Give(owner,roundtype,totake);
        else HDPickup.DropItem(owner,roundtype,totake);
        owner.A_StartSound("magmanager/extract",CHAN_WEAPON);
        owner.A_StartSound("magmanager/extract426",CHAN_WEAPON,CHANF_OVERLAP,0.4);
        mags[mindex]-=totake;
        return true;
    }
    override bool Insert(){
        SyncAmount();
        if(reseal && mags[mags.size()-1]==30 && owner.countinv("MM_4mmSealant"))
        {
            mags[mags.size()-1]++;
            owner.A_StartSound("magmanager/insert",16);
            owner.A_TakeInventory("MM_4mmSealant",1,TIF_NOTAKEINFINITE);
        }
        if(
            mags.size()<1
            ||mags[mags.size()-1]>=30
            ||!owner.countinv(roundtype)
        )return false;
        owner.A_TakeInventory(roundtype,1,TIF_NOTAKEINFINITE);
        owner.A_StartSound("magmanager/insert",8);
        owner.A_StartSound("weapons/pocket",9,volume:frandom(0.1,0.6));
        mags[mags.size()-1]++;
        return true;
    }
    override void Consolidate(){
        SyncAmount();
        if(amount<2)return;
        int totalrounds=0;
        int howmanymags=0;
        for(int i=0;i<amount;i++){
            int thismag=mags[i];
            if(
                !thismag
                ||thismag>=30
            )continue;
            howmanymags++;
            totalrounds+=mags[i]%30;
            mags[i]=0; //keep the empties, do NOT call clear()!
        }
        if(howmanymags>1)totalrounds=int(totalrounds*frandom(0.9,1.));
        for(int i=0;i<amount;i++){
            if(mags[i]>=30)continue;
            int toinsert=clamp(totalrounds,mags[i],30);
            mags[i]=toinsert;
            totalrounds-=toinsert;
            if(totalrounds<1)break;
        }
    }
    states(actor){
    spawn:
        CWNM AB -1 nodelay{
            if(!mags.size()){destroy();return;}
            int mmm=mags[0];
            if(mmm>31)mags[0]=min(30,mmm%100);
            if(mmm<31)frame=1;
        }stop;
    spawnempty:
        CWNM C -1 A_SpawnEmpty();
        stop;
    }
}

class HDCrushed10mm : HDSpent10mm{}