// ------------------------------------------------------------
// SMG
// ------------------------------------------------------------
class HDCurrawong:HDWeapon{
    default{
        //$Category "Weapons/Hideous Destructor"
        //$Title "SMG"
        //$Sprite "CURNA0"

        +hdweapon.fitsinbackpack
        obituary "$OB_CURRAWONG";
        weapon.selectionorder 34;
        weapon.slotnumber 2;
        weapon.slotpriority 4;
        weapon.kickback 30;
        weapon.bobrangex 0.5;
        weapon.bobrangey 0.9;
        weapon.bobspeed 2.5;
        scale 0.55;
        inventory.pickupmessage "$PICKUP_CURRAWONG";
        hdweapon.barrelsize 36,1.5,2;
        hdweapon.refid HDLD_CURRAWONG;
        tag "$TAG_CURRAAWONG";
        inventory.icon "CWRPA0";

        hdweapon.ammo1 "HD10mMag25",1;

        hdweapon.loadoutcodes "
            \cufiremode - 0-2, semi/burst/auto
            \cufireswitch - 0-4, default/semi/auto/full/all";
    }
    override bool AddSpareWeapon(actor newowner){return AddSpareWeaponRegular(newowner);}
    override hdweapon GetSpareWeapon(actor newowner,bool reverse,bool doselect){return GetSpareWeaponRegular(newowner,reverse,doselect);}
    override double gunmass(){
        return 5+((weaponstatus[CURS_MAG]<0)?-0.5:(weaponstatus[CURS_MAG]*0.05));
    }
	override void GunBounce(){
		super.GunBounce();
		if(!random(0,5))weaponstatus[0]&=~CURS_CHAMBERBROKEN;
	}
    override void tick()
    {
        super.tick();
        drainheat(CURS_HEAT, 1);
    }
    override double weaponbulk(){
        int mg=weaponstatus[CURS_MAG];
        if(mg<0)return 110;
        else return (110+ENC_9MAG30_LOADED)+mg*enc_10_loaded;
    }
    override void failedpickupunload(){
        failedpickupunloadmag(CURS_MAG,"HD10mMag25");
    }
    override void DropOneAmmo(int amt){
        if(owner){
            amt=clamp(amt,1,10);
            if(owner.countinv("HD10mAmmo"))owner.A_DropInventory("HD10mAmmo",amt*25);
            else owner.A_DropInventory("HD10mMag25",amt);
        }
    }
    override void postbeginplay(){
        super.postbeginplay();
        if(weaponstatus[CURS_AUTO]>0){
        switch(weaponstatus[CURS_SWITCHTYPE]){
        case 1:
            weaponstatus[CURS_AUTO]=0;
            break;
        case 2:
            weaponstatus[CURS_AUTO]=1;
            break;
        case 3:
            weaponstatus[CURS_AUTO]=2;
            break;
        default:
            break;
        }}
    }
    override void ForceBasicAmmo(){
        owner.A_TakeInventory("HD10mAmmo");
        ForceOneBasicAmmo("HD10mMag25");
    }
    override string,double getpickupsprite(bool usespare){
        int wep0=GetSpareWeaponValue(0,usespare);
        return ("CWRP")..((GetSpareWeaponValue(CURS_MAG,usespare)<0)?"B":"A").."0",1.;
    }

	override void DrawHUDStuff(HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl){
		if(sb.hudlevel==1){
			int nextmagloaded=sb.GetNextLoadMag(hdmagammo(hpl.findinventory("HD10mMag25")));
			if(nextmagloaded>25){
				sb.drawimage("CWNMA0",(-46,-3),sb.DI_SCREEN_CENTER_BOTTOM,scale:(2,2));
			}else if(nextmagloaded<1){
				sb.drawimage("CWNMC0",(-46,-3),sb.DI_SCREEN_CENTER_BOTTOM,alpha:nextmagloaded?0.6:1.,scale:(2,2));
			}else sb.drawbar(
				"CWNMA0","CWNMGREY",
				nextmagloaded,25,
				(-46,-3),-1,
				sb.SHADER_VERT,sb.DI_SCREEN_CENTER_BOTTOM
			);
			sb.drawnum(hpl.countinv("HD10mMag25"),-43,-8,sb.DI_SCREEN_CENTER_BOTTOM);
            sb.drawimage("4GSIA0",(-62,-4),sb.DI_SCREEN_CENTER_BOTTOM,scale:(0.6,0.6));
			sb.drawnum(hpl.countinv("HD4GBAmmo"),-56,-8,sb.DI_SCREEN_CENTER_BOTTOM);
		}

        if(weaponstatus[CURS_SWITCHTYPE]!=1)sb.drawwepcounter(hdw.weaponstatus[CURS_AUTO],
            -22,-10,"RBRSA3A7","STBURAUT","STFULAUT"
        );
		if(hdw.weaponstatus[0]&CURF_4GAUGELOADED)sb.drawrect(-20,-14,4,2.6);
		int lod=clamp(hdw.weaponstatus[CURS_MAG]%100,0,25);
		sb.drawwepnum(lod,25);
		if(hdw.weaponstatus[0]&CURS_CHAMBER){
			sb.drawrect(-19,-10,3,1);
			lod++;
		}
		if(hdw.weaponstatus[CURS_MAG]>75)lod=random[shitgun](10,99);
		sb.drawnum(lod,-16,-22,sb.DI_SCREEN_CENTER_BOTTOM|sb.DI_TEXT_ALIGN_RIGHT,Font.CR_RED);
	}
    override string gethelptext(){
        LocalizeHelp();
        return
        LWPHELP_FIRESHOOT
        ..LWPHELP_RELOAD..StringTable.Localize("$SMGWH_FIRE")
        ..LWPHELP_USE.."+"..LWPHELP_RELOAD..StringTable.Localize("$SMGWH_UPRELOAD")
        ..LWPHELP_FIREMODE..StringTable.Localize("$SMGWH_FMODE")
        ..LWPHELP_MAGMANAGER
        ..LWPHELP_UNLOADUNLOAD;
    }
    override void DrawSightPicture(
        HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl,
        bool sightbob,vector2 bob,double fov,bool scopeview,actor hpc
    ){
        vector2 bobb=bob*1.18;
        int cx,cy,cw,ch;
        [cx,cy,cw,ch]=screen.GetClipRect();
        sb.SetClipRect(
            -16+bob.x,-4+bob.y,32,16,
            sb.DI_SCREEN_CENTER
        );
        sb.drawimage(
            "smgfrntsit",(0,0)+bobb,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP
        );
        sb.SetClipRect(cx,cy,cw,ch);
        sb.drawimage(
            "smgbaksit",(0,0)+bob,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP,
            alpha:0.9
        );
    }
    //returns the power of the load just fired
	static double FireShell(actor caller){
		double shotpower=1.0;
		HDBulletActor.FireBullet(caller,"HDB_4wad");
		let p=HDBulletActor.FireBullet(caller,"HDB_400",spread:6.0,speedfactor:0.98,amount:40);
		caller.A_StartSound("weapons/cur4gaugeshot",9,CHANF_DEFAULT);
		return shotpower;
	}

	action bool brokenround(){
		if(!(invoker.weaponstatus[CURS_FLAGS]&CURS_CHAMBERBROKEN)){
			int hht=invoker.weaponstatus[CURS_HEAT];
			if(hht>240)invoker.weaponstatus[CURS_BORESTRETCHED]++;
			hht*=hht;hht>>=10;
			int rnd=
				(invoker.owner?1:10)
				+max(invoker.weaponstatus[CURS_AUTO],hht)
				+invoker.weaponstatus[CURS_BORESTRETCHED]
				+(invoker.weaponstatus[CURS_MAG]>75?10:0);
			if(random(0,2000)<rnd){
				invoker.weaponstatus[CURS_FLAGS]|=CURS_CHAMBERBROKEN;
			}
		}return invoker.weaponstatus[CURS_FLAGS]&CURS_CHAMBERBROKEN;
	}
    states{
    select0:
        CURW A 0;
        goto select0small;
    deselect0:
        CURW A 0;
        goto deselect0small;
        CURW A 0;

    ready:
        #### A 1{
            A_SetCrosshair(21);
            invoker.weaponstatus[CURS_RATCHET]=0;
            A_WeaponReady(WRF_ALL);
            if(invoker.weaponstatus[CURS_AUTO]>2)invoker.weaponstatus[CURS_AUTO]=2;
        }
        goto readyend;
    user3:
        ---- A 0 A_MagManager("HD10mMag25");
        goto ready;

    althold:
        goto nope;
    hold:
        #### A 0{
            if(
                invoker.weaponstatus[CURS_CHAMBER]==2  //live round chambered
                &&(
                    invoker.weaponstatus[CURS_AUTO]==2  //full auto
                    ||(
                        invoker.weaponstatus[CURS_AUTO]==1  //burst
                        &&invoker.weaponstatus[CURS_RATCHET]<=2
                    )
                )
            )setweaponstate("fire");
        }goto nope;
    user2:
    firemode:
        ---- A 1{
            int canaut=invoker.weaponstatus[CURS_SWITCHTYPE];
            if(canaut==1){
                invoker.weaponstatus[CURS_AUTO]=0;
                return;
            }
            int maxmode=(canaut>0)?(canaut-1):2;
            int aut=invoker.weaponstatus[CURS_AUTO];
            if(aut>=maxmode)invoker.weaponstatus[CURS_AUTO]=0;
            else if(aut<0)invoker.weaponstatus[CURS_AUTO]=0;
            else if(canaut>0)invoker.weaponstatus[CURS_AUTO]=maxmode;
            else invoker.weaponstatus[CURS_AUTO]++;
        }goto nope;
	jam:
		#### B 1 offset(-1,36){
			A_StartSound("weapons/riflejam",CHAN_WEAPON,CHANF_OVERLAP);
			invoker.weaponstatus[0]|=CURS_CHAMBERBROKEN;
			invoker.weaponstatus[CURS_FLAGS]&=~CURS_CHAMBER;
		}
		#### B 1 offset(1,30) A_StartSound("weapons/riflejam",CHAN_WEAPON,CHANF_OVERLAP);
		goto nope;

    fire:
        #### B 1{
            if(invoker.weaponstatus[CURS_CHAMBER]==2)A_GunFlash();
            else setweaponstate("chamber_manual");
        }
        #### A 1;
        #### A 0{
            if(invoker.weaponstatus[CURS_CHAMBER]==1){
                A_EjectCasing("HDSpent10mm",
                    frandom(-1,2),
                    (frandom(0.2,0.3),-frandom(7,7.5),frandom(0,0.2)),
                    (0,0,-2)
                );
                invoker.weaponstatus[CURS_CHAMBER]=0;
            }
            if(invoker.weaponstatus[CURS_MAG]>0){
                invoker.weaponstatus[CURS_MAG]--;
                invoker.weaponstatus[CURS_CHAMBER]=2;
            }
            if(invoker.weaponstatus[CURS_AUTO]==2 || invoker.weaponstatus[CURS_AUTO]==1)
            {
                A_SetTics((invoker.WeaponStatus[CURS_WEIRDFIRE]*invoker.WeaponStatus[CURS_HEAT]/5)+1);
                if(invoker.WeaponStatus[CURS_WEIRDFIRE]<2)invoker.WeaponStatus[CURS_WEIRDFIRE]++;
                else invoker.WeaponStatus[CURS_WEIRDFIRE]--;
            }
            invoker.WeaponStatus[CURS_HEAT] += random(3, 5);

            //don't allow firing if supposed to be lowered
            A_WeaponReady(WRF_NOFIRE);
        }
        #### A 0 A_ReFire();
        goto ready;
    flash:
        #### F 0 bright{
            double brnd=max(invoker.weaponstatus[CURS_HEAT],invoker.weaponstatus[CURS_BORESTRETCHED])*0.01;
            let bbb=HDBulletActor.FireBullet(self,"HDB_10",speedfactor:1.25,spread:brnd>1.2?brnd:0);
            A_Log("Mag: "..invoker.WeaponStatus[CURS_MAG]);
            if(
                frandom(16,ceilingz-floorz)<bbb.speed*0.1
            )A_AlertMonsters(HDCONST_ONEMETRE * (15));

            A_ZoomRecoil(0.985);
            A_StartSound("weapons/currawong",CHAN_WEAPON,volume:0.7);
            invoker.weaponstatus[CURS_RATCHET]++;
            invoker.weaponstatus[CURS_CHAMBER]=1;
        }
        CURF F 1 bright{
            HDFlashAlpha(-200);
            A_Light1();
        }
        TNT1 A 0 A_MuzzleClimb(-frandom(0.4,0.44),-frandom(0.5,0.56),-frandom(0.4,0.44),-frandom(0.5,0.56));
        goto lightdone;

    unloadchamber:
        #### A 1 offset(-3,34);
        #### A 1 offset(-9,39);
        #### B 3 offset(-19,44) A_MuzzleClimb(frandom(-0.4,0.4),frandom(-0.4,0.4),wepdot:false);
        #### A 2 offset(-16,42){
            A_MuzzleClimb(frandom(-0.4,0.4),frandom(-0.4,0.4),wepdot:false);
            if(
                invoker.weaponstatus[CURS_FLAGS]&CURS_CHAMBER
                &&!(invoker.weaponstatus[0]&CURS_CHAMBERBROKEN)
            ){
                A_SpawnItemEx("ZM66DroppedRound",0,0,20,
                    random(4,7),random(-2,2),random(-2,1),0,
                    SXF_NOCHECKPOSITION
                );
                invoker.weaponstatus[CURS_FLAGS]&=~CURS_CHAMBER;
                A_StartSound("weapons/rifleclick2",CHAN_WEAPON,CHANF_OVERLAP);
            }else if(!random(0,4)){
                invoker.weaponstatus[0]&=~CURS_CHAMBERBROKEN;
                invoker.weaponstatus[CURS_FLAGS]&=~CURS_CHAMBER;
                A_StartSound("weapons/rifleclick",CHAN_WEAPON,CHANF_OVERLAP);
                for(int i=0;i<5;i++)A_SpawnItemEx("FourMilChunk",0,0,20,
                    random(4,7),random(-2,2),random(-2,1),0,SXF_NOCHECKPOSITION
                );
                if(!random(0,5))A_SpawnItemEx("HDSmokeChunk",12,0,gunheight()-10,4,frandom(-2,2),frandom(2,4));
            }else if(invoker.weaponstatus[0]&CURS_CHAMBERBROKEN){
                A_StartSound("weapons/smack",CHAN_WEAPON,CHANF_OVERLAP);
            }
        }goto reloadend;
	chamber:
		#### B 0 offset(0,32){
			if(invoker.weaponstatus[CURS_MAG]<1){
				setweaponstate("nope");
				return;
			}
			if(invoker.weaponstatus[CURS_MAG]%100>0){
				if(invoker.weaponstatus[CURS_MAG]==26)invoker.weaponstatus[CURS_MAG]=25;
				invoker.weaponstatus[CURS_MAG]--;
				invoker.weaponstatus[CURS_FLAGS]|=CURS_CHAMBER;
			}else{
				invoker.weaponstatus[CURS_MAG]=min(invoker.weaponstatus[CURS_MAG],0);
				A_StartSound("weapons/rifchamber",CHAN_WEAPON,CHANF_OVERLAP);
			}
			if(brokenround()){
				setweaponstate("jam");
				return;
			}
			A_WeaponReady(WRF_NONE);
		}
		#### B 0 A_JumpIf(invoker.weaponstatus[CURS_AUTO]<1,"nope");
		#### B 0 A_JumpIf(invoker.weaponstatus[CURS_AUTO]>4,"nope");
		#### B 2 A_JumpIf(invoker.weaponstatus[CURS_AUTO]>1,1);
		#### B 0 A_Refire();
		goto ready;
    user4:
	unload:
		#### A 0{
			invoker.weaponstatus[CURF_FLAGS]|=CURF_UNLOADONLY;
            if(
				invoker.weaponstatus[CURS_MAG]>=0
			){
				setweaponstate("unloadmag");
			}else if(
				invoker.weaponstatus[CURF_FLAGS]&CURS_CHAMBER
				||invoker.weaponstatus[CURF_FLAGS]&CURS_CHAMBERBROKEN
			){
				setweaponstate("unloadchamber");
			}else{
				setweaponstate("unloadmag");
			}
		}
	reload:
		#### A 0{
			invoker.weaponstatus[CURF_FLAGS]&=~CURF_UNLOADONLY;
			if(	//full mag, no jam, not unload-only - why hit reload at all?
				!(invoker.weaponstatus[0]&CURS_CHAMBERBROKEN)
				&&invoker.weaponstatus[CURS_MAG]%100>=25
				&&!(invoker.weaponstatus[CURF_FLAGS]&CURF_UNLOADONLY)
			){
				setweaponstate("nope");
			}else if(	//if jammed, treat as unloading
				invoker.weaponstatus[CURS_MAG]<0
				&&invoker.weaponstatus[0]&CURS_CHAMBERBROKEN
			){
				invoker.weaponstatus[CURF_FLAGS]|=CURF_UNLOADONLY;
				setweaponstate("unloadchamber");
			}else if(!HDMagAmmo.NothingLoaded(self,"HD10mMag25")){
				setweaponstate("unloadmag");
			}
		}goto nope;
	unloadmag:
		#### A 1 offset(0,33);
		#### A 1 offset(-3,34);
		#### A 1 offset(-8,37);
		#### B 2 offset(-11,39){
			if(	//no mag, skip unload
				invoker.weaponstatus[CURS_MAG]<0
			){
				setweaponstate("magout");
			}
			if(invoker.weaponstatus[0]&CURS_CHAMBERBROKEN)
				invoker.weaponstatus[CURF_FLAGS]|=CURF_UNLOADONLY;
			A_MuzzleClimb(-0.3,-0.3,wepdot:false);
			A_StartSound("weapons/rifleclick2",CHAN_WEAPON,CHANF_OVERLAP);
		}
		#### B 4 offset(-12,40){
			A_MuzzleClimb(-0.3,-0.3,wepdot:false);
			A_StartSound("weapons/rifleunload",CHAN_WEAPON);
		}
		#### B 20 offset(-14,44){
			int inmag=invoker.weaponstatus[CURS_MAG];
			if(inmag>26)inmag=min(25,inmag%100);
			invoker.weaponstatus[CURS_MAG]=-1;
			if(
				!PressingUnload()&&!PressingReload()
				||A_JumpIfInventory("HD10mMag25",0,"null")
			){
				HDMagAmmo.SpawnMag(self,"HD10mMag25",inmag);
				A_SetTics(1);
			}else{
				HDMagAmmo.GiveMag(self,"HD10mMag25",inmag);
				A_StartSound("weapons/pocket",CHAN_WEAPON);
				if(inmag<26)A_Log(StringTable.Localize("$426MAGMSG"),true);
			}
		}
	magout:
		#### B 0{
			if(
				invoker.weaponstatus[CURF_FLAGS]&CURF_UNLOADONLY
				||!countinv("HD10mMag25")
			)setweaponstate("reloadend");
		} //fallthrough to loadmag
	loadmag:
		---- A 12 offset(-15,44){
			let cmag=HD10mMag25(findinventory("HD10mMag25"));
			if(!cmag){setweaponstate("reloadend");return;}
			A_StartSound("weapons/pocket",CHAN_WEAPON);
			if(cmag.DirtyMagsOnly())invoker.weaponstatus[0]|=CURF_LOADINGDIRTY;
			else{
				invoker.weaponstatus[0]&=~CURF_LOADINGDIRTY;
				A_SetTics(10);
			}
		}
		---- A 2 offset(-15,44) A_JumpIf(invoker.weaponstatus[0]&CURF_LOADINGDIRTY,"loadmagdirty");
	loadmagclean:
		#### B 8 offset(-15,45)A_StartSound("weapons/rifleload",CHAN_WEAPON);
		#### B 1 offset(-14,44){
			let cmag=HD10mMag25(findinventory("HD10mMag25"));
			if(!cmag){setweaponstate("reloadend");return;}
			if(cmag.DirtyMagsOnly()){
				setweaponstate("loadmagdirty");
				return;
			}
			invoker.weaponstatus[CURS_MAG]=cmag.TakeMag(true);
			A_StartSound("weapons/rifleclick2",CHAN_WEAPON);
		}goto reloadend;
	loadmagdirty:
		#### B 0{
			if(PressingReload())invoker.weaponstatus[0]|=CURF_STILLPRESSINGRELOAD;
			else invoker.weaponstatus[0]&=~CURF_STILLPRESSINGRELOAD;
		}
		#### B 3 offset(-15,45)A_StartSound("weapons/rifleload",CHAN_WEAPON);
		#### B 1 offset(-15,42)A_WeaponMessage(StringTable.Localize("$ZM426MAGMSG"),70);
		#### BBBBBBBAAAA 1 offset(-15,41){
			bool prr=PressingReload();
			if(
				prr
				&&!(invoker.weaponstatus[0]&CURF_STILLPRESSINGRELOAD)
			){
				setweaponstate("reallyloadmagdirty");
			}
			else if(!PressingReload())invoker.weaponstatus[0]&=~CURF_STILLPRESSINGRELOAD;
		}
		goto nope;
	reallyloadmagdirty:
		#### B 1 offset(-14,44)A_StartSound("weapons/rifleclick2",CHAN_WEAPON);
		#### A 8 offset(-18,50){
			let cmag=HD10mMag25(findinventory("HD10mMag25"));
			if(!cmag){setweaponstate("reloadend");return;}
			invoker.weaponstatus[CURS_MAG]=cmag.TakeMag(true)+50;
			A_MuzzleClimb(
				-frandom(0.4,0.6),frandom(2.,3.)
				-frandom(0.2,0.3),frandom(1.,1.6),
				wepdot:false
			);
			A_StartSound("weapons/rifleclick2",CHAN_WEAPON,CHANF_OVERLAP);
			A_StartSound("weapons/smack",CHAN_WEAPON,CHANF_OVERLAP);

			string realmessage=StringTable.Localize("$426MAGMSG");
			realmessage=realmessage.left(random(13,20));
			realmessage.appendformat(StringTable.Localize("$ZMRELERROR")..random(0,9999)..StringTable.Localize("$ZMNOCARRIER"));
			A_WeaponMessage(realmessage,70);
		}
		#### A 4 offset(-17,49);
		goto chamber_manual;

	reloadend:
		#### B 2 offset(-11,39);
		#### A 1 offset(-8,37) A_MuzzleClimb(frandom(0.2,-2.4),frandom(0.2,-1.4),wepdot:false);
		#### A 1 offset(-3,34);
		goto chamber_manual;

	chamber_manual:
		#### A 0 A_JumpIf(invoker.weaponstatus[CURS_FLAGS]&CURS_CHAMBER,"nope");
		#### A 3 offset(-1,36)A_WeaponBusy();
		#### B 4 offset(-3,42){
			if(!invoker.weaponstatus[CURS_MAG]%100)invoker.weaponstatus[CURS_MAG]=0;
			if(
				!(invoker.weaponstatus[CURS_FLAGS]&CURS_CHAMBER)
				&& !(invoker.weaponstatus[CURS_FLAGS]&CURS_CHAMBER)
				&& invoker.weaponstatus[CURS_MAG]%100>0
			){
				A_StartSound("weapons/rifleclick",CHAN_WEAPON);
				if(invoker.weaponstatus[CURS_MAG]==26)invoker.weaponstatus[CURS_MAG]=24;
				else invoker.weaponstatus[CURS_MAG]--;
				invoker.weaponstatus[CURS_FLAGS]|=CURS_CHAMBER;
				brokenround();
			}else setweaponstate("nope");
		}
		#### A 2 offset(-1,36);
		#### A 0 offset(0,34);
		goto nope;


	unloadchamber:
		#### A 1 offset(-3,34);
		#### A 1 offset(-9,39);
		#### B 3 offset(-19,44) A_MuzzleClimb(frandom(-0.4,0.4),frandom(-0.4,0.4),wepdot:false);
		#### A 2 offset(-16,42){
			A_MuzzleClimb(frandom(-0.4,0.4),frandom(-0.4,0.4),wepdot:false);
			if(
				invoker.weaponstatus[CURS_FLAGS]&CURS_CHAMBER
				&&!(invoker.weaponstatus[0]&CURS_CHAMBERBROKEN)
			){
				A_SpawnItemEx("ZM66DroppedRound",0,0,20,
					random(4,7),random(-2,2),random(-2,1),0,
					SXF_NOCHECKPOSITION
				);
				invoker.weaponstatus[CURS_FLAGS]&=~CURS_CHAMBER;
				A_StartSound("weapons/rifleclick2",CHAN_WEAPON,CHANF_OVERLAP);
			}else if(!random(0,4)){
				invoker.weaponstatus[0]&=~CURS_CHAMBERBROKEN;
				invoker.weaponstatus[CURS_FLAGS]&=~CURS_CHAMBER;
				A_StartSound("weapons/rifleclick",CHAN_WEAPON,CHANF_OVERLAP);
				for(int i=0;i<5;i++)A_SpawnItemEx("FourMilChunk",0,0,20,
					random(4,7),random(-2,2),random(-2,1),0,SXF_NOCHECKPOSITION
				);
				if(!random(0,5))A_SpawnItemEx("HDSmokeChunk",12,0,gunheight()-10,4,frandom(-2,2),frandom(2,4));
			}else if(invoker.weaponstatus[0]&CURS_CHAMBERBROKEN){
				A_StartSound("weapons/smack",CHAN_WEAPON,CHANF_OVERLAP);
			}
		}goto reloadend;

	firefrag:
		#### B 2{
			if(!(invoker.weaponstatus[CURS_FLAGS]&CURF_4GAUGELOADED)){
				setweaponstate("nope");
				return;
			}
            invoker.FireShell(Self);
			invoker.weaponstatus[CURS_FLAGS]&=~CURF_4GAUGELOADED;
			A_StartSound("weapons/cur4gshot",CHAN_WEAPON);
		}
		#### B 3{
			A_ZoomRecoil(0.95);
            A_MuzzleClimb(-frandom(5.5, 10.25), -frandom(9.5, 11.75), -frandom(8.5, 10.25), -frandom(9.5, 11.75));
            if(!gunbraced()){
                A_ChangeVelocity(cos(pitch)*-frandom(0.375,0.75),0,sin(pitch)*frandom(0.375,0.75),CVF_RELATIVE);
            }
            A_ChangeVelocity(cos(pitch)*-frandom(0.125,0.25),0,sin(pitch)*frandom(0.125,0.25),CVF_RELATIVE);
            GiveBody (max(0,11-health));
            DamageMobJ (invoker, self, 10, "bashing");
		}
		goto nope;

	altfire:
		#### A 1 A_JumpIf(invoker.weaponstatus[CURS_FLAGS]&CURF_4GAUGELOADED,1);
		goto nope;
		#### A 1;
		#### A 3 {
		invoker.airburst=0;
		A_Gunflash("firefrag");
		}
		goto nope;

	altreload:
		#### A 0{
			invoker.weaponstatus[CURS_FLAGS]&=~CURF_UNLOADONLY;
			if(
				!(invoker.weaponstatus[CURS_FLAGS]&CURF_4GAUGELOADED)
				&&countinv("HD4GBAmmo")
			)setweaponstate("unloadshell");
		}goto nope;
	unloadshell:
		#### B 0{
			A_SetCrosshair(21);
			A_MuzzleClimb(-0.3,-0.3,wepdot:false);
		}
		#### B 2 offset(0,34);
		#### B 1 offset(4,38){
			A_MuzzleClimb(-0.3,-0.3,wepdot:false);
		}
		#### B 2 offset(8,48){
			A_StartSound("weapons/cur4gaugeopen",CHAN_WEAPON);
			A_MuzzleClimb(-0.3,-0.3,wepdot:false);
			if(invoker.weaponstatus[CURS_FLAGS]&CURF_4GAUGELOADED)A_StartSound("weapons/grenreload",CHAN_WEAPON);
		}
		#### B 10 offset(10,49){
			if(!(invoker.weaponstatus[CURS_FLAGS]&CURF_4GAUGELOADED)){
				if(!(invoker.weaponstatus[CURS_FLAGS]&CURF_UNLOADONLY))A_SetTics(3);
				return;
			}
			invoker.weaponstatus[CURS_FLAGS]&=~CURF_4GAUGELOADED;
			if(
				!PressingUnload()
				||A_JumpIfInventory("HD4GBAmmo",0,"null")
			){
				A_SpawnItemEx("HD4GBAmmo",
					cos(pitch)*10,0,gunheight()-2-10*sin(pitch),vel.x,vel.y,vel.z,0,
					SXF_ABSOLUTEMOMENTUM|SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH
				);
			}else{
				A_StartSound("weapons/pocket",CHAN_WEAPON,CHANF_OVERLAP);
				A_GiveInventory("HD4GBAmmo",1);
				A_MuzzleClimb(frandom(0.8,-0.2),frandom(0.4,-0.2),wepdot:false);
			}
		}
		#### B 0 A_JumpIf(invoker.weaponstatus[CURS_FLAGS]&CURF_UNLOADONLY,"greloadend");

	loadgrenade:
		#### B 4 offset(10,50) A_StartSound("weapons/pocket",CHAN_WEAPON,CHANF_OVERLAP);
		#### BBB 8 offset(10,50) A_MuzzleClimb(frandom(-0.2,0.8),frandom(-0.2,0.4),wepdot:false);
		#### B 18 offset(8,50){
			if(!countinv("HD4GBAmmo"))return;
			A_TakeInventory("HD4GBAmmo",1,TIF_NOTAKEINFINITE);
			invoker.weaponstatus[CURS_FLAGS]|=CURF_4GAUGELOADED;
			A_StartSound("weapons/cur4gaugereload",CHAN_WEAPON);
		}
	greloadend:
		#### B 4 offset(4,44) A_StartSound("weapons/cur4gaugeopen",CHAN_WEAPON);
		#### B 1 offset(0,40);
		#### A 1 offset(0,34) A_MuzzleClimb(frandom(-2.4,0.2),frandom(-1.4,0.2),wepdot:false);
		goto nope;

    spawn:
        CWRP A -1{if(invoker.weaponstatus[CURS_MAG]<0)frame=1;}
        CWRP # -1;
        stop;
    }
    override void initializewepstats(bool idfa){
        weaponstatus[CURS_MAG]=25;
        weaponstatus[CURS_CHAMBER]=2;
        weaponstatus[CURF_4GAUGELOADED]=0;
    }
    override void loadoutconfigure(string input){
        int firemode=getloadoutvar(input,"firemode",1);
        if(firemode>=0)weaponstatus[CURS_AUTO]=clamp(firemode,0,2);

        int fireswitch=getloadoutvar(input,"fireswitch",1);
        if(fireswitch>3)weaponstatus[CURS_SWITCHTYPE]=0;
        else if(fireswitch>0)weaponstatus[CURS_SWITCHTYPE]=clamp(fireswitch,0,3);
    }
}

enum CurrawongStatus{
    CURF_FLAGS=1,
    CURS_CHAMBERBROKEN=2,
    CURF_4GAUGELOADED=4,
    CURF_UNLOADONLY=8,
    CURF_STILLPRESSINGRELOAD=16,
    CURF_LOADINGDIRTY=32,
    CURF_JUSTUNLOAD=64,

    CURN_SEMIONLY=1,
    CURN_BURSTONLY=2,
    CURN_FULLONLY=3,

    CURS_FLAGS=0,
    CURS_MAG=1,
    CURS_AUTO=2, //0 semi, 1 burst, 2 auto
    CURS_RATCHET=3,
    CURS_SWITCHTYPE=4,
    CURS_BORESTRETCHED=5,
    CURS_HEAT=6,
    CURS_WEIRDFIRE=7,
    CURS_CHAMBER=8
};

class HDCurrawongRandom:IdleDummy{
    states{
    spawn:
        TNT1 A 0 nodelay{
            let lll=HDCurrawong(spawn("HDCurrawong",pos,ALLOW_REPLACE));
            if(!lll)return;
            lll.special=special;
            lll.vel=vel;
            for(int i=0;i<5;i++)lll.args[i]=args[i];
            if(!random(0,2))lll.weaponstatus[CURS_SWITCHTYPE]=random(0,3);
        }stop;
    }
}

class HD10mMag25:HDMagAmmo{
    default{
        hdmagammo.maxperunit 26; // + 50 for dirty. - [Ted]
        hdmagammo.roundtype "HD10mAmmo";
        hdmagammo.roundbulk ENC_10_LOADED;
        hdmagammo.magbulk ENC_9MAG_EMPTY;
        hdmagammo.extracttime 4;

        tag "$TAG_10MAG25";
        inventory.pickupmessage "$PICKUP_10MMAG25";
        hdpickup.refid HDLD_CURRAWONGMAG;
    }
	override string,string,name,double getmagsprite(int thismagamt){
		string magsprite;
		if(thismagamt>=51)magsprite="CWNMA0";
		else if(thismagamt>0)magsprite="CWNMB0";
		else magsprite="CWNMC0";
		return magsprite,"PBRSA0","HD10mAmmo",0.6;
	}
	override void postbeginplay(){
		super.postbeginplay();
		sealtimer=0;
		breakchance=0;
	}
	int breakchance;
	int sealtimer;
	override void doeffect(){
		if(sealtimer>0)sealtimer--;
		if(breakchance>0)breakchance--;
		super.doeffect();
	}
	override string pickupmessage(){
		string pms=super.pickupmessage();
		if(mags[0]<26)pms.appendformat(" %s",StringTable.Localize("$426MAGMSG"));
		return pms;
	}
	override int GetMagHudCount(int input){
		if(input==26)return 25;
		return input;
	}
	bool DirtyMagsOnly(){
		if(mags.size()!=amount)return false;
		for(int i=0;i<amount;i++){
			if(mags[i]>=26)return false;
		}
		return true;
	}
	override bool Extract(){
		SyncAmount();
		int mindex=mags.size()-1;
		if(
			mags.size()<1
			||mags[mindex]<1
			||owner.A_JumpIfInventory(roundtype,0,"null")
		)return false;
		if(mags[mindex]==26){
			if(sealtimer<1){
				owner.A_Log(string.format(StringTable.Localize("$426MAGREALLY"),StringTable.Localize("$426MAGMSG")),true);
				sealtimer=10;
				extracttime=9;
				return false;
			}else{
				mags[mindex]=25;
				extracttime=12;
				owner.A_StartSound("magmanager/426open",CHAN_WEAPON,CHANF_OVERLAP);
				return false;
			}
		}else extracttime=default.extracttime;
		int totake=min(random(1,6),mags[mindex]);
		if(totake<HDPickup.MaxGive(owner,roundtype,roundbulk))HDF.Give(owner,roundtype,totake);
		else HDPickup.DropItem(owner,roundtype,totake);
		owner.A_StartSound("magmanager/extract",CHAN_WEAPON);
		mags[mindex]-=totake;
		return true;
	}
	override bool Insert(){
		SyncAmount();
		if(
			mags.size()<1
			||mags[mags.size()-1]>=25
			||!owner.countinv(roundtype)
		)return false;
		owner.A_TakeInventory(roundtype,1,TIF_NOTAKEINFINITE);
		owner.A_StartSound("magmanager/insert",8);
		owner.A_StartSound("weapons/pocket",9,volume:frandom(0.1,0.6));
		mags[mags.size()-1]++;
		return true;
	}
	override void Consolidate(){
		SyncAmount();
		if(amount<2)return;
		int totalrounds=0;
		int howmanymags=0;
		for(int i=0;i<amount;i++){
			int thismag=mags[i];
			if(
				!thismag
				||thismag>=25
			)continue;
			howmanymags++;
			totalrounds+=mags[i]%25;
			mags[i]=0; //keep the empties, do NOT call clear()!
		}
		if(howmanymags>1)totalrounds=int(totalrounds*frandom(0.9,1.));
		for(int i=0;i<amount;i++){
			if(mags[i]>=25)continue;
			int toinsert=clamp(totalrounds,mags[i],25);
			mags[i]=toinsert;
			totalrounds-=toinsert;
			if(totalrounds<1)break;
		}
	}
    states(actor){
    spawn:
        CWNM A -1 nodelay{
			if(!mags.size()){destroy();return;}
			int mmm=mags[0];
			if(mmm>26)mags[0]=min(25,mmm%100);
			if(mmm<26)frame=1;
		}stop;
    spawnempty:
        CWNM A -1 A_SpawnEmpty();
        stop;
    }
}