// ------------------------------------------------------------
// SMG
// ------------------------------------------------------------
class HDCurrawong:HDWeapon{
    default{
        //$Category "Weapons/Hideous Destructor"
        //$Title "SMG"
        //$Sprite "CURNA0"

        +hdweapon.fitsinbackpack
        obituary "$OB_CURRAWONG";
        weapon.selectionorder 34;
        weapon.slotnumber 2;
        weapon.slotpriority 4;
        weapon.kickback 30;
        weapon.bobrangex 0.5;
        weapon.bobrangey 0.9;
        weapon.bobspeed 2.5;
        scale 0.55;
        inventory.pickupmessage "$PICKUP_CURRAWONG";
        hdweapon.barrelsize 36,1.5,2;
        hdweapon.refid HDLD_CURRAWONG;
        tag "$TAG_CURRAAWONG";
        inventory.icon "CWRPA0";

        hdweapon.ammo1 "HD10mMag25",1;

        hdweapon.loadoutcodes "
            \cufiremode - 0-2, semi/burst/auto
            \cufireswitch - 0-4, default/semi/auto/full/all";
    }
    override bool AddSpareWeapon(actor newowner){return AddSpareWeaponRegular(newowner);}
    override hdweapon GetSpareWeapon(actor newowner,bool reverse,bool doselect){return GetSpareWeaponRegular(newowner,reverse,doselect);}
    override double gunmass(){
        return 5+((weaponstatus[CURS_MAG]<0)?-0.5:(weaponstatus[CURS_MAG]*0.05));
    }
    override void tick()
    {
        super.tick();
        drainheat(CURS_HEAT, 1);
    }
    override double weaponbulk(){
        int mg=weaponstatus[CURS_MAG];
        if(mg<0)return 110;
        else return (110+ENC_9MAG30_LOADED)+mg*enc_10_loaded;
    }
    override void failedpickupunload(){
        failedpickupunloadmag(CURS_MAG,"HD10mMag25");
    }
    override void DropOneAmmo(int amt){
        if(owner){
            amt=clamp(amt,1,10);
            if(owner.countinv("HD10mAmmo"))owner.A_DropInventory("HD10mAmmo",amt*25);
            else owner.A_DropInventory("HD10mMag25",amt);
        }
    }
    override void postbeginplay(){
        super.postbeginplay();
        if(weaponstatus[CURS_AUTO]>0){
        switch(weaponstatus[CURS_SWITCHTYPE]){
        case 1:
            weaponstatus[CURS_AUTO]=0;
            break;
        case 2:
            weaponstatus[CURS_AUTO]=1;
            break;
        case 3:
            weaponstatus[CURS_AUTO]=2;
            break;
        default:
            break;
        }}
    }
    override void ForceBasicAmmo(){
        owner.A_TakeInventory("HD10mAmmo");
        ForceOneBasicAmmo("HD10mMag25");
    }
    override string,double getpickupsprite(bool usespare){
        int wep0=GetSpareWeaponValue(0,usespare);
        return ("CWRP")..((GetSpareWeaponValue(CURS_MAG,usespare)<0)?"B":"A").."0",1.;
    }
    override void DrawHUDStuff(HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl){
        if(sb.hudlevel==1){
            int nextmagloaded=sb.GetNextLoadMag(hdmagammo(hpl.findinventory("HD10mMag25")));
            if(nextmagloaded>=25){
                sb.drawimage("CWNMA0",(-46,-3),sb.DI_SCREEN_CENTER_BOTTOM);
            }else if(nextmagloaded<1){
                sb.drawimage("CWNMB0",(-46,-3),sb.DI_SCREEN_CENTER_BOTTOM,alpha:nextmagloaded?0.6:1.);
            }else sb.drawbar(
                "CWNMA0","CWNMGREY",
                nextmagloaded,25,
                (-46,-3),-1,
                sb.SHADER_VERT,sb.DI_SCREEN_CENTER_BOTTOM
            );
            sb.drawnum(hpl.countinv("HD10mMag25"),-43,-8,sb.DI_SCREEN_CENTER_BOTTOM);
			sb.drawimage("4GSIA0",(-62,-4),sb.DI_SCREEN_CENTER_BOTTOM);
			sb.drawnum(hpl.countinv("HD4GBAmmo"),-56,-8,sb.DI_SCREEN_CENTER_BOTTOM);
        }
        if(weaponstatus[CURS_SWITCHTYPE]!=1)sb.drawwepcounter(hdw.weaponstatus[CURS_AUTO],
            -22,-10,"RBRSA3A7","STBURAUT","STFULAUT"
        );
        sb.drawwepnum(hdw.weaponstatus[CURS_MAG],25);
        if(hdw.weaponstatus[CURS_CHAMBER]==2)sb.drawrect(-19,-11,3,1);
		if(hdw.weaponstatus[0]&CURF_4GAUGELOADED)sb.drawrect(-20,-15,4,2.6);
    }
    override string gethelptext(){
        LocalizeHelp();
        return
        LWPHELP_FIRESHOOT
        ..LWPHELP_RELOAD..StringTable.Localize("$SMGWH_FIRE")
        ..LWPHELP_USE.."+"..LWPHELP_RELOAD..StringTable.Localize("$SMGWH_UPRELOAD")
        ..LWPHELP_FIREMODE..StringTable.Localize("$SMGWH_FMODE")
        ..LWPHELP_MAGMANAGER
        ..LWPHELP_UNLOADUNLOAD;
    }
    override void DrawSightPicture(
        HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl,
        bool sightbob,vector2 bob,double fov,bool scopeview,actor hpc
    ){
        vector2 bobb=bob*1.18;
        int cx,cy,cw,ch;
        [cx,cy,cw,ch]=screen.GetClipRect();
        sb.SetClipRect(
            -16+bob.x,-4+bob.y,32,16,
            sb.DI_SCREEN_CENTER
        );
        sb.drawimage(
            "smgfrntsit",(0,0)+bobb,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP
        );
        sb.SetClipRect(cx,cy,cw,ch);
        sb.drawimage(
            "smgbaksit",(0,0)+bob,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP,
            alpha:0.9
        );
    }
    //returns the power of the load just fired
	static double FireShell(actor caller){
		double shotpower=1.0;
		HDBulletActor.FireBullet(caller,"HDB_4wad");
		let p=HDBulletActor.FireBullet(caller,"HDB_400",spread:6.0,speedfactor:0.98,amount:40);
		caller.A_StartSound("weapons/cur4gaugeshot",9,CHANF_DEFAULT);
		return shotpower;
	}
    states{
    select0:
        CURW A 0;
        goto select0small;
    deselect0:
        CURW A 0;
        goto deselect0small;
        CURW A 0;

    ready:
        #### A 1{
            A_SetCrosshair(21);
            invoker.weaponstatus[CURS_RATCHET]=0;
            A_WeaponReady(WRF_ALL);
        }
        goto readyend;
    user3:
        ---- A 0 A_MagManager("HD10mMag25");
        goto ready;

	nadeflash:
		TNT1 A 0 A_JumpIf(invoker.weaponstatus[CURS_FLAGS]&CURF_4GAUGELOADED,1);
		stop;
		TNT1 A 2{
            invoker.FireShell(Self);
			invoker.weaponstatus[CURS_FLAGS]&=~CURF_4GAUGELOADED;
			A_ZoomRecoil(0.995);
		}
		TNT1 A 2 {
            A_MuzzleClimb(-frandom(5.5, 10.25), -frandom(9.5, 11.75), -frandom(8.5, 10.25), -frandom(9.5, 11.75));
            if(!gunbraced()){
                A_ChangeVelocity(cos(pitch)*-frandom(0.375,0.75),0,sin(pitch)*frandom(0.375,0.75),CVF_RELATIVE);
            }
            A_ChangeVelocity(cos(pitch)*-frandom(0.125,0.25),0,sin(pitch)*frandom(0.125,0.25),CVF_RELATIVE);
            GiveBody (max(0,11-health));
            DamageMobJ (invoker, self, 10, "bashing");
        }
		stop;

	altfire:
		#### A 1 A_JumpIf(invoker.weaponstatus[CURS_FLAGS]&CURF_4GAUGELOADED,1);
		goto nope;
		#### A 1;
		#### A 3 {
		invoker.airburst=0;
		A_Gunflash("nadeflash");
		}
		goto nope;

	altreload:
		#### A 0{
			invoker.weaponstatus[CURS_FLAGS]&=~CURF_FLAGS;
			if(
				!(invoker.weaponstatus[CURS_FLAGS]&CURF_4GAUGELOADED)
				&&countinv("HD4GBAmmo")
			)setweaponstate("unloadgrenade");
		}goto nope;
	unloadgrenade:
		#### A 0{
			A_SetCrosshair(21);
			A_MuzzleClimb(-0.3,-0.3);
		}
		#### A 3 offset(0,34);
		#### A 2 offset(4,38){
			A_MuzzleClimb(-0.3,-0.3);
		}
		#### A 3 offset(8,48){
			A_StartSound("weapons/cur4gaugeopen",CHAN_WEAPON,CHANF_OVERLAP);
			A_MuzzleClimb(-0.3,-0.3);
			if(invoker.weaponstatus[CURS_FLAGS]&CURF_4GAUGELOADED)A_StartSound("weapons/cur4gaugereload",CHAN_WEAPON);
		}
		#### A 11 offset(10,49){
			if(!(invoker.weaponstatus[CURS_FLAGS]&CURF_4GAUGELOADED)){
				if(!(invoker.weaponstatus[CURS_FLAGS]&CURF_FLAGS))A_SetTics(3);
				return;
			}
			invoker.weaponstatus[CURS_FLAGS]&=~CURF_4GAUGELOADED;
			if(
				!PressingUnload()
				||A_JumpIfInventory("HD4GBAmmo",0,"null")
			){
				A_SpawnItemEx("HD4GBAmmo",
					cos(pitch)*10,0,height-10-10*sin(pitch),vel.x,vel.y,vel.z,0,
					SXF_ABSOLUTEMOMENTUM|SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH
				);
			}else{
				A_StartSound("weapons/pocket",CHAN_WEAPON,CHANF_OVERLAP);
				A_GiveInventory("HD4GBAmmo",1);
				A_MuzzleClimb(frandom(0.8,-0.2),frandom(0.4,-0.2));
			}
		}
		#### A 0 A_JumpIf(invoker.weaponstatus[CURS_FLAGS]&CURF_FLAGS,"greloadend");
	loadgrenade:
		#### A 3 offset(10,50) A_StartSound("weapons/pocket",CHAN_WEAPON,CHANF_OVERLAP);
		#### ABB 6 offset(10,50) A_MuzzleClimb(frandom(-0.2,0.8),frandom(-0.2,0.4));
		#### A 23 offset(8,50){
			A_TakeInventory("HD4GBAmmo",1,TIF_NOTAKEINFINITE);
			invoker.weaponstatus[CURS_FLAGS]|=CURF_4GAUGELOADED;
			A_StartSound("weapons/cur4gaugereload",CHAN_WEAPON);
		}
	greloadend:
		#### A 5 offset(4,44) A_StartSound("weapons/cur4gaugeopen",CHAN_WEAPON);
		#### A 2 offset(0,40);
		#### A 1 offset(0,34) A_MuzzleClimb(frandom(-2.4,0.2),frandom(-1.4,0.2));
		goto nope;

    althold:
        goto nope;
    hold:
        #### A 0{
            if(
                invoker.weaponstatus[CURS_CHAMBER]==2  //live round chambered
                &&(
                    invoker.weaponstatus[CURS_AUTO]==2  //full auto
                    ||(
                        invoker.weaponstatus[CURS_AUTO]==1  //burst
                        &&invoker.weaponstatus[CURS_RATCHET]<=2
                    )
                )
            )setweaponstate("fire");
        }goto nope;
    user2:
    firemode:
        ---- A 1{
            int canaut=invoker.weaponstatus[CURS_SWITCHTYPE];
            if(canaut==1){
                invoker.weaponstatus[CURS_AUTO]=0;
                return;
            }
            int maxmode=(canaut>0)?(canaut-1):2;
            int aut=invoker.weaponstatus[CURS_AUTO];
            if(aut>=maxmode)invoker.weaponstatus[CURS_AUTO]=0;
            else if(aut<0)invoker.weaponstatus[CURS_AUTO]=0;
            else if(canaut>0)invoker.weaponstatus[CURS_AUTO]=maxmode;
            else invoker.weaponstatus[CURS_AUTO]++;
        }goto nope;
    fire:
        #### B 1{
            if(invoker.weaponstatus[CURS_CHAMBER]==2)A_GunFlash();
            else setweaponstate("chamber_manual");
        }
        #### A 1;
        #### A 0{
            if(invoker.weaponstatus[CURS_CHAMBER]==1){
                A_EjectCasing("HDSpent10mm",
                    frandom(-1,2),
                    (frandom(0.2,0.3),-frandom(7,7.5),frandom(0,0.2)),
                    (0,0,-2)
                );
                invoker.weaponstatus[CURS_CHAMBER]=0;
            }
            if(invoker.weaponstatus[CURS_MAG]>0){
                invoker.weaponstatus[CURS_MAG]--;
                invoker.weaponstatus[CURS_CHAMBER]=2;
            }
            if(invoker.weaponstatus[CURS_AUTO]==2 || invoker.weaponstatus[CURS_AUTO]==1)
            {
                A_SetTics((invoker.WeaponStatus[CURS_WEIRDFIRE]*invoker.WeaponStatus[CURS_HEAT]/5)+1);
                if(invoker.WeaponStatus[CURS_WEIRDFIRE]<2)invoker.WeaponStatus[CURS_WEIRDFIRE]++;
                else invoker.WeaponStatus[CURS_WEIRDFIRE]--;
            }
            invoker.WeaponStatus[CURS_HEAT] += random(3, 5);

            //don't allow firing if supposed to be lowered
            A_WeaponReady(WRF_NOFIRE);
        }
        #### A 0 A_ReFire();
        goto ready;
    flash:
        #### F 0 bright{
            let bbb=HDBulletActor.FireBullet(self,"HDB_10",speedfactor:1.25);
            if(
                frandom(16,ceilingz-floorz)<bbb.speed*0.1
            )A_AlertMonsters(HDCONST_ONEMETRE * (15));

            A_ZoomRecoil(0.985);
            A_StartSound("weapons/currawong",CHAN_WEAPON,volume:0.7);
            invoker.weaponstatus[CURS_RATCHET]++;
            invoker.weaponstatus[CURS_CHAMBER]=1;
        }
        CURF F 1 bright{
            HDFlashAlpha(-200);
            A_Light1();
        }
        TNT1 A 0 A_MuzzleClimb(-frandom(0.4,0.44),-frandom(0.5,0.56),-frandom(0.4,0.44),-frandom(0.5,0.56));
        goto lightdone;

    unloadchamber:
        #### B 4 A_JumpIf(invoker.weaponstatus[CURS_CHAMBER]<1,"nope");
        #### B 10{
            class<actor>which=invoker.weaponstatus[CURS_CHAMBER]>1?"HD10mAmmo":"HDSpent10mm";
            invoker.weaponstatus[CURS_CHAMBER]=0;
            A_SpawnItemEx(which,
                cos(pitch)*10,0,height*0.82-sin(pitch)*10,
                vel.x,vel.y,vel.z,
                0,SXF_ABSOLUTEMOMENTUM|SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH
            );
        }goto readyend;
    loadchamber:
        ---- A 0 A_JumpIf(invoker.weaponstatus[CURS_CHAMBER]>0,"nope");
        ---- A 0 A_JumpIf(!countinv("HD10mAmmo"),"nope");
        ---- A 1 offset(0,34) A_StartSound("weapons/pocket",9);
        ---- A 1 offset(2,36);
        ---- A 1 offset(2,44);
        #### B 1 offset(5,58);
        #### B 2 offset(7,70);
        #### B 6 offset(8,80);
        #### A 10 offset(8,87){
            if(countinv("HD10mAmmo")){
                A_TakeInventory("HD10mAmmo",1,TIF_NOTAKEINFINITE);
                invoker.weaponstatus[CURS_CHAMBER]=2;
                A_StartSound("weapons/currawongchamber",8);
            }else A_SetTics(4);
        }
        #### A 3 offset(9,76);
        ---- A 2 offset(5,70);
        ---- A 1 offset(5,64);
        ---- A 1 offset(5,52);
        ---- A 1 offset(5,42);
        ---- A 1 offset(2,36);
        ---- A 2 offset(0,34);
        goto nope;
    user4:
    unload:
        #### A 0{
            invoker.weaponstatus[0]|=CURF_JUSTUNLOAD;
            if(
                invoker.weaponstatus[CURS_MAG]>=0
            )setweaponstate("unmag");
            else if(invoker.weaponstatus[CURS_CHAMBER]>0)setweaponstate("unloadchamber");
        }goto nope;
    reload:
        #### A 0{
            invoker.weaponstatus[0]&=~CURF_JUSTUNLOAD;
            bool nomags=HDMagAmmo.NothingLoaded(self,"HD10mMag25");
            if(invoker.weaponstatus[CURS_MAG]>=25)setweaponstate("nope");
            else if(
                invoker.weaponstatus[CURS_MAG]<1
                &&(
                    pressinguse()
                    ||nomags
                )
            ){
                if(
                    countinv("HD10mAmmo")
                )setweaponstate("loadchamber");
                else setweaponstate("nope");
            }else if(nomags)setweaponstate("nope");
        }goto unmag;
    unmag:
        #### A 1 offset(0,34) A_SetCrosshair(21);
        #### A 1 offset(5,38);
        #### A 1 offset(10,42);
        #### B 2 offset(20,46) A_StartSound("weapons/currawongmagout",8);
        #### B 4 offset(30,52){
            A_MuzzleClimb(0.3,0.4,wepdot:false);
            A_StartSound("weapons/currawongmagmove",8,CHANF_OVERLAP);
        }
        #### B 0{
            int magamt=invoker.weaponstatus[CURS_MAG];
            if(magamt<0){
                setweaponstate("magout");
                return;
            }
            invoker.weaponstatus[CURS_MAG]=-1;
            if(
                (!PressingUnload()&&!PressingReload())
                ||A_JumpIfInventory("HD10mMag25",0,"null")
            ){
                HDMagAmmo.SpawnMag(self,"HD10mMag25",magamt);
                setweaponstate("magout");
            }else{
                HDMagAmmo.GiveMag(self,"HD10mMag25",magamt);
                A_StartSound("weapons/pocket",9);
                setweaponstate("pocketmag");
            }
        }
    pocketmag:
        #### BB 7 offset(34,54) A_MuzzleClimb(frandom(0.2,-0.8),frandom(-0.2,0.4),wepdot:false);
    magout:
        #### B 0{
            if(invoker.weaponstatus[0]&CURF_JUSTUNLOAD)setweaponstate("reloadend");
            else setweaponstate("loadmag");
        }

    loadmag:
        #### B 0 A_StartSound("weapons/pocket",9);
        #### B 6 offset(34,54) A_MuzzleClimb(frandom(0.2,-0.8),frandom(-0.2,0.4),wepdot:false);
        #### B 7 offset(34,52) A_MuzzleClimb(frandom(0.2,-0.8),frandom(-0.2,0.4),wepdot:false);
        #### B 10 offset(32,50);
        #### B 3 offset(32,49){
            let mmm=hdmagammo(findinventory("HD10mMag25"));
            if(mmm){
                invoker.weaponstatus[CURS_MAG]=mmm.TakeMag(true);
                A_StartSound("weapons/currawongmagin",8,CHANF_OVERLAP);
            }
            if(
                invoker.weaponstatus[CURS_MAG]<1
                ||invoker.weaponstatus[CURS_CHAMBER]>0
            )setweaponstate("reloadend");
        }
        goto reloadend;

    reloadend:
        #### B 3 offset(30,52);
        #### B 2 offset(20,46);
        #### A 1 offset(10,42);
        #### A 1 offset(5,38);
        #### A 1 offset(0,34);
        goto chamber_manual;

    chamber_manual:
        #### A 0 A_JumpIf(
            invoker.weaponstatus[CURS_MAG]<1
            ||invoker.weaponstatus[CURS_CHAMBER]==2
        ,"nope");
        #### B 2 offset(3,32){
            A_WeaponBusy();
            invoker.weaponstatus[CURS_MAG]--;
            invoker.weaponstatus[CURS_CHAMBER]=2;
        }
        #### B 3 offset(5,35) A_StartSound("weapons/currawongchamber",8,CHANF_OVERLAP);
        #### A 1 offset(3,32);
        #### A 1 offset(2,31);
        goto nope;


    spawn:
        CWRP A -1{if(invoker.weaponstatus[CURS_MAG]<0)frame=1;}
        CWRP # -1;
        stop;
    }
    override void initializewepstats(bool idfa){
        weaponstatus[CURS_MAG]=25;
        weaponstatus[CURS_CHAMBER]=2;
        weaponstatus[CURF_4GAUGELOADED]=0;
    }
    override void loadoutconfigure(string input){
        int firemode=getloadoutvar(input,"firemode",1);
        if(firemode>=0)weaponstatus[CURS_AUTO]=clamp(firemode,0,2);

        int fireswitch=getloadoutvar(input,"fireswitch",1);
        if(fireswitch>3)weaponstatus[CURS_SWITCHTYPE]=0;
        else if(fireswitch>0)weaponstatus[CURS_SWITCHTYPE]=clamp(fireswitch,0,3);
    }
}
enum CurrawongStatus{
    CURF_FLAGS=1,
    CURF_JUSTUNLOAD=2,
    CURF_4GAUGELOADED=3,

    CURN_SEMIONLY=1,
    CURN_BURSTONLY=2,
    CURN_FULLONLY=3,

    CURS_FLAGS=0,
    CURS_MAG=1,
    CURS_CHAMBER=2, //0 empty, 1 spent, 2 loaded
    CURS_AUTO=3, //0 semi, 1 burst, 2 auto
    CURS_RATCHET=4,
    CURS_SWITCHTYPE=5,
    CURS_WEIRDFIRE=6,
    CURS_HEAT=7
};

class HDCurrawongRandom:IdleDummy{
    states{
    spawn:
        TNT1 A 0 nodelay{
            let lll=HDCurrawong(spawn("HDCurrawong",pos,ALLOW_REPLACE));
            if(!lll)return;
            lll.special=special;
            lll.vel=vel;
            for(int i=0;i<5;i++)lll.args[i]=args[i];
            if(!random(0,2))lll.weaponstatus[CURS_SWITCHTYPE]=random(0,3);
        }stop;
    }
}

class HD10mMag25:HDMagAmmo{
    default{
        hdmagammo.maxperunit 25;
        hdmagammo.roundtype "HD10mAmmo";
        hdmagammo.roundbulk ENC_10_LOADED;
        hdmagammo.magbulk ENC_9MAG_EMPTY;
        tag "$TAG_10MAG25";
        inventory.pickupmessage "$PICKUP_10MMAG25";
        hdpickup.refid HDLD_CURRAWONGMAG;
    }
    override string,string,name,double getmagsprite(int thismagamt){
        string magsprite=(thismagamt>0)?"CWNMA0":"CWNMB0";
        return magsprite,"PBRSA0","HD10mAmmo",0.6;
    }
    states{
    spawn:
        CWNM A -1;
        stop;
    spawnempty:
        CWNM A -1 A_SpawnEmpty();
        stop;
    }
}