class HDKakapo:HDHandgun{
	default{
		+hdweapon.fitsinbackpack
		+hdweapon.reverseguninertia
		scale 0.63;
		weapon.selectionorder 50;
		weapon.slotnumber 2;
		weapon.slotpriority 2;
		weapon.kickback 30;
		weapon.bobrangex 0.1;
		weapon.bobrangey 0.6;
		weapon.bobspeed 2.5;
		weapon.bobstyle "normal";
		obituary "$OB_KAKAPO";
		inventory.pickupmessage "$PICKUP_KAKAPO";
		tag "$TAG_KAKAPO";
		hdweapon.refid "kpo";
		hdweapon.barrelsize 19,0.3,0.5;

		hdweapon.ammo1 "HDBattery",1;

		hdweapon.loadoutcodes "
			\cuselectfire - 0/1, whether it has a fire selector
			\cufiremode - 0/1, semi/auto, subject to the above";
	}
	override double weaponbulk(){
		int mgg=weaponstatus[KRProp_Battery];
		return 30+(mgg<0?0:(ENC_9MAG_LOADED+mgg*ENC_9_LOADED));
	}
	override double gunmass(){
		int mgg=weaponstatus[KRProp_Battery];
		return 3.5+(mgg<0?0:0.08*(mgg+1));
	}
	override void failedpickupunload(){
		failedpickupunloadmag(KRProp_Battery,"HDBattery");
	}
	override string,double getpickupsprite(bool usespare){
		string spr;
		int wep0=GetSpareWeaponValue(0,usespare);
		if(GetSpareWeaponValue(KRProp_Chamber,usespare)<1){
			spr="B";
		}else{
			spr="A";
		}
		return "PIST"..spr.."0",1.;
	}
	override void DrawHUDStuff(HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl){
		if(sb.hudlevel==1){
			int nextmagloaded=sb.GetNextLoadMag(hdmagammo(hpl.findinventory("HDBattery")));
			if(nextmagloaded>=20){
				sb.drawimage("CLP2NORM",(-46,-3),sb.DI_SCREEN_CENTER_BOTTOM,scale:(1,1));
			}else if(nextmagloaded<1){
				sb.drawimage("CLP2EMPTY",(-46,-3),sb.DI_SCREEN_CENTER_BOTTOM,alpha:nextmagloaded?0.6:1.,scale:(1,1));
			}else sb.drawbar(
				"CLP2NORM","CLP2GREY",
				nextmagloaded,20,
				(-46,-3),-1,
				sb.SHADER_VERT,sb.DI_SCREEN_CENTER_BOTTOM
			);
			sb.drawnum(hpl.countinv("HDBattery"),-43,-8,sb.DI_SCREEN_CENTER_BOTTOM);
		}
		sb.drawwepnum(hdw.weaponstatus[KRProp_Battery],20);
		if(hdw.weaponstatus[KRProp_Chamber]==1)sb.drawrect(-19,-11,3,1);
	}
	override string gethelptext(){
		LocalizeHelp();
		return
		LWPHELP_FIRESHOOT
		..LWPHELP_ALTRELOAD..StringTable.Localize("$PISWH_ALTRELOAD")
		..LWPHELP_RELOAD..StringTable.Localize("$PISWH_RELOAD")
		..LWPHELP_USE.."+"..LWPHELP_RELOAD..StringTable.Localize("$PISWH_UPRELOAD")
		..LWPHELP_MAGMANAGER
		..LWPHELP_UNLOADUNLOAD
		;
	}
	override void DrawSightPicture(
		HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl,
		bool sightbob,vector2 bob,double fov,bool scopeview,actor hpc
	){
		int cx,cy,cw,ch;
		[cx,cy,cw,ch]=screen.GetClipRect();
		vector2 scc;
		vector2 bobb=bob*1.3;
		sb.SetClipRect(
			-8+bob.x,-9+bob.y,16,15,
			sb.DI_SCREEN_CENTER
		);
		scc=(0.6,0.6);
		sb.drawimage(
			"frntsite",(0,0)+bobb,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP,
			scale:scc
		);
		sb.SetClipRect(cx,cy,cw,ch);
		sb.drawimage(
			"backsite",(0,0)+bob,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP,
			alpha:0.9,
			scale:scc
		);
	}
	override void DropOneAmmo(int amt){
		if(owner){
			amt=clamp(amt,1,10);
			owner.A_DropInventory("HDBattery",1);
		}
	}
	override void ForceBasicAmmo(){
		owner.A_TakeInventory("HDPistolAmmo");
		ForceOneBasicAmmo("HDBattery");
	}
	action void A_CheckPistolHand(){
		if(invoker.wronghand)player.getpsprite(PSP_WEAPON).sprite=getspriteindex("PI2GA0");
	}
	states{
	select0:
		PI1G A 0{
			if(!countinv("NulledWeapon"))invoker.wronghand=false;
			A_TakeInventory("NulledWeapon");
			A_CheckPistolHand();
		}
		#### A 0 A_JumpIf(invoker.weaponstatus[KRProp_Chamber]>0,2);
		#### C 0;
		---- A 1 A_Raise();
		---- A 1 A_Raise(30);
		---- A 1 A_Raise(30);
		---- A 1 A_Raise(24);
		---- A 1 A_Raise(18);
		wait;
	deselect0:
		PI1G A 0 A_CheckPistolHand();
		#### A 0 A_JumpIf(invoker.weaponstatus[KRProp_Chamber]>0,2);
		#### C 0;
		---- AAA 1 A_Lower();
		---- A 1 A_Lower(18);
		---- A 1 A_Lower(24);
		---- A 1 A_Lower(30);
		wait;

	ready:
		PI1G A 0 A_CheckPistolHand();
		#### A 0 A_JumpIf(invoker.weaponstatus[KRProp_Chamber]>0,2);
		#### C 0;
		#### # 0 A_SetCrosshair(21);
		#### # 1 A_WeaponReady(WRF_ALL);
		goto readyend;
	user3:
		---- A 0 A_MagManager("HDBattery");
		goto ready;
	user2:
	firemode:
	althold:
	hold:
		goto nope;
	fire:
		---- A 0{
			invoker.weaponstatus[0]&=~KRProp_JustUnload;
			if(invoker.weaponstatus[KRProp_Chamber]==1)setweaponstate("shoot");
			else if(invoker.weaponstatus[KRProp_Battery]>0)setweaponstate("nope");
		}goto nope;
	shoot:
		#### B 1{
			if(invoker.weaponstatus[KRProp_Chamber]==1)A_GunFlash();
		}
		#### C 1{
			if(hdplayerpawn(self)){
				hdplayerpawn(self).gunbraced=false;
			}
			A_MuzzleClimb(
				-frandom(0.8,1.),-frandom(1.2,1.6),
				frandom(0.4,0.5),frandom(0.6,0.8)
			);
			invoker.weaponstatus[KRProp_Chamber]=0;
			A_WeaponReady(WRF_NOFIRE);
		}
		#### C 0{
			if(invoker.weaponstatus[KRProp_Battery]<1){
				A_StartSound("weapons/pistoldry",8,CHANF_OVERLAP,0.9);
				setweaponstate("nope");
			}
		}
		#### B 1 A_Refire();
		goto ready;
	flash:
		PI2F A 0 A_JumpIf(invoker.wronghand,2);
		PI1F A 0;
		---- A 1 bright
		{
			HDFlashAlpha(64);
			A_Light1();
			
			A_RailAttack(random(800, 1000), 0, false, "", "", RGF_NORANDOMPUFFZ | RGF_SILENT | RGF_NOPIERCING, 0, "KakapoRayImpact", 0, 0, HDCONST_ONEMETRE * 300, 0, 10.0, 0, "KakapoRaySegment", player.crouchfactor < 1.0 ? 0.9 : 1.8);
        	A_Recoil((2.25) * (HDPlayerPawn(self).gunbraced ? 0.3 : 1.0));
			A_AlertMonsters();
			A_SetBlend(1, 0.33, 30);
			A_ZoomRecoil(1.00 - 0.2);
		}
		---- A 0 A_StartSound("weapons/pistol",CHAN_WEAPON);
		---- A 0 A_Light0();
		stop;

	AltFire:
		#### A 1 Offset(1, 32) A_WeaponBusy();
		#### A 1 Offset(1, 34);
		#### A 1 Offset (2, 36);
		#### A 1 Offset(2, 38) A_MuzzleClimb(-frandom(0.06,0.1),-frandom(0.3,0.5));
		#### B 1 Offset(2, 40);
		#### B 0 A_Refire("chamber");
		goto ready;

	/*AltHold:
		#### B 1 A_WeaponReady(WRF_NOFIRE);
		#### B 1{
			A_ClearRefire();
			if (PressingAltFire())
			{
				return ResolveState("AltHold");
			}
			return resolvestate("altholdend");
		}*/
	chamber:
		#### B 1 offset(2,38)A_StartSound("weapons/spstslideback",8);
		#### B 1 offset(1,42);
		#### B 1 offset(1,46){
			if(gunbraced())A_MuzzleClimb(
				frandom(-0.1,0.3),frandom(-0.1,0.3)
			);else A_MuzzleClimb(
				frandom(-0.2,0.8),frandom(-0.4,0.8)
			);
		}
		#### B 1 offset(1,42){
			//cycle new
			if(invoker.weaponstatus[KRProp_Battery]>0){  
				invoker.weaponstatus[KRProp_Chamber]=1;
				invoker.weaponstatus[KRProp_Battery]--;
			}else invoker.weaponstatus[KRProp_Chamber]=0;
		}
		#### B 1 offset(1,42) A_WeaponReady(WRF_NOFIRE);
		//#### B 0 A_Refire("althold");
		goto altholdend;

	AltHoldEnd:
		#### B 1 offset(1,36) A_StartSound("weapons/spstslidefwd", 8);
		#### A 1 offset(1,32);
		Goto Ready;

	reload:
		#### C 0{
			if(
				invoker.weaponstatus[KRProp_Battery]>=20
				||!countinv("HDBattery")
			){return resolvestate("nope");}
			invoker.weaponstatus[0]&=~CSAWF_JUSTUNLOAD;
			return resolvestate("unmag");
		}

	user4:
	unload:
		#### C 0{
			if(invoker.weaponstatus[KRProp_Battery]<0){
				return resolvestate("nope");
			}invoker.weaponstatus[0]|=CSAWF_JUSTUNLOAD;return resolvestate(null);
		}
	unmag:
		#### A 1 offset(0,33);
		#### A 1 offset(0,35);
		#### A 1 offset(0,37);
		#### A 1 offset(0,39);
		#### A 2 offset(0,44);
		#### A 2 offset(0,52);
		#### A 3 offset(2,62);
		#### A 4 offset(4,74);
		#### A 7 offset(6,78)A_StartSound("weapons/csawopen",8);
		#### A 0{
			A_StartSound("weapons/csawload",8,CHANF_OVERLAP);
			if(
				!PressingUnload()&&!PressingReload()
			){
				setweaponstate("dropmag");
			}else setweaponstate("pocketmag");
		}
	dropmag:
		#### A 0{
			if(invoker.weaponstatus[KRProp_Battery]>=0){
				HDMagAmmo.SpawnMag(self,"HDBattery",invoker.weaponstatus[KRProp_Battery]);
			}
			invoker.weaponstatus[KRProp_Battery]=-1;
		}goto magout;
	pocketmag:
		#### A 6 offset(7,80){
			if(invoker.weaponstatus[KRProp_Battery]>=0){
				HDMagAmmo.GiveMag(self,"HDBattery",invoker.weaponstatus[KRProp_Battery]);
				A_StartSound("weapons/pocket",9);
				A_MuzzleClimb(
					randompick(-1,1)*frandom(-0.3,-1.2),
					randompick(-1,1)*frandom(0.3,1.8),
					wepdot:false
				);
			}
			invoker.weaponstatus[KRProp_Battery]=-1;
		}
		#### A 7 offset(6,81) A_StartSound("weapons/pocket",9);
		goto magout;

	magout:
		#### A 0 A_JumpIf(invoker.weaponstatus[0]&CSAWF_JUSTUNLOAD,"reloadend");

	loadmag:
		#### A 4 offset(7,79) A_MuzzleClimb(
			randompick(-1,1)*frandom(-0.3,-1.2),
			randompick(-1,1)*frandom(0.3,0.8)
		);
		#### A 2 offset(6,78) A_StartSound("weapons/pocket",9);
		#### AA 5 offset(5,76) A_MuzzleClimb(
			randompick(-1,1)*frandom(-0.3,-1.2),
			randompick(-1,1)*frandom(0.3,0.8)
		);
		#### A 0{
			let mmm=HDMagAmmo(findinventory("HDBattery"));
			if(mmm)invoker.weaponstatus[KRProp_Battery]=mmm.TakeMag(true);
		}

	reloadend:
		#### A 6 offset(5,72);
		#### A 5 offset(4,74)A_StartSound("weapons/csawclose",8);
		#### A 4 offset(2,62);
		#### A 3 offset(0,52);
		#### A 4 offset(0,44);
		#### A 1 offset(0,37);
		#### A 1 offset(0,35);
		#### A 1 offset(0,33);
		goto ready;

	user1:
	altreload:
	swappistols:
		---- A 0 A_SwapHandguns();
		---- A 0{
			if(!invoker.wronghand){
				A_Overlay(1025,"raiseleft");
				A_Overlay(1026,"lowerright");
			}else{
				A_Overlay(1025,"raiseright");
				A_Overlay(1026,"lowerleft");
			}
		}
		TNT1 A 5;
		PI1G A 0 A_CheckPistolHand();
		goto nope;
	lowerleft:
		PI1G A 0;
		#### A 1 offset(-6,38);
		#### A 1 offset(-12,48);
		#### A 1 offset(-20,60);
		#### A 1 offset(-34,76);
		#### A 1 offset(-50,86);
		stop;
	lowerright:
		PI2G A 0;
		#### A 1 offset(6,38);
		#### A 1 offset(12,48);
		#### A 1 offset(20,60);
		#### A 1 offset(34,76);
		#### A 1 offset(50,86);
		stop;
	raiseleft:
		PI1G A 0;
		#### A 1 offset(-50,86);
		#### A 1 offset(-34,76);
		#### A 1 offset(-20,60);
		#### A 1 offset(-12,48);
		#### A 1 offset(-6,38);
		stop;
	raiseright:
		PI2G A 0;
		#### A 1 offset(50,86);
		#### A 1 offset(34,76);
		#### A 1 offset(20,60);
		#### A 1 offset(12,48);
		#### A 1 offset(6,38);
		stop;
	whyareyousmiling:
		#### A 1 offset(0,48);
		#### A 1 offset(0,60);
		#### A 1 offset(0,76);
		TNT1 A 7;
		PI1G A 0{
			invoker.wronghand=!invoker.wronghand;
			A_CheckPistolHand();
		}
		#### A 1 offset(0,76);
		#### A 1 offset(0,60);
		#### A 1 offset(0,48);
		goto nope;


	spawn:
		PIST ABCD -1 nodelay;
		stop;
	}
	override void initializewepstats(bool idfa){
		weaponstatus[KRProp_Battery]=20;
		weaponstatus[KRProp_Chamber]=1;
	}
}
enum kakapostatus{
	KRProp_Flags=0,
	KRProp_Battery=1,
	KRProp_Chamber=2, //0 empty, 1 loaded
	KRProp_JustUnload=3,
};

class KakapoRaySegment : Actor
{
	override void PostBeginPlay()
	{
		Super.PostBeginPlay();
		pcol = HDMath.PlayingId() ? 0xDFFF66 : 0x0098ff;
		for (int i = 0; i < 2; ++i)
		{
			A_SpawnParticle(pcol, SPF_RELATIVE | SPF_FULLBRIGHT, random(100, 200), frandom(1.5, 3.0), 0,random(-10, 10), 0, 0,
				frandom(-0.10, 0.10), frandom(-0.10, 0.10), frandom(-0.10, 0.10),
				frandom(-0.005, 0.005), frandom(-0.005, 0.005), frandom(-0.005, 0.005));
		}
		if (target)
		{
			double dist = Distance3D(target);
			alpha += 0.00075 * dist;
		}
	}

	private double FadeSpeed;
	Color pcol;

	Default
	{
		Renderstyle "Add";
		+NOINTERACTION
		+NOBLOCKMAP
		+BRIGHT
		Alpha 1.0;
	}

	States
	{
		Spawn:
			GNGY A 1 Bright A_FadeOut(0.05);
			Loop;
	}
}

class KakapoRayImpactBase : Actor abstract
{
	protected abstract void OnBlast(bool miss);
	protected void SpawnBlastEffects(int tier, bool miss)
	{
		pcol1 = HDMath.PlayingID() ? 0xAAFF42 : 0x0098ff;
		pcol2 = HDMath.PlayingID() ? 0xDFFF66 : 0x0098ff;
		// Horizontal ring.
		for (int i = -180; i < 180; i += 4)
		{
			A_SpawnParticle(pcol1, SPF_FULLBRIGHT | SPF_RELATIVE, 10 + 2 * tier, 32 + 8 * tier, i, 0, 0, 0, 12, sizestep: 4.0);
		}
		
		// Ball.
		for (int i = -180; i < 180; i += 10)
		{
			for (int j = -90 + 10; j < 90 - 9; j += 10)
			{
				A_SpawnParticle(pcol2, SPF_FULLBRIGHT | SPF_RELATIVE, 15 + tier, 24 + 4 * tier, i, 0, 0, 0, 4 * cos(j) * level.pixelstretch, 0, 4 * sin(j), sizestep: 2.0);
			}
		}

		if (miss)
		{
			// Spears.
			for (int i = 0; i < 10 * (tier + 1); ++i)
			{
				pitch = frandom(-85.0, 85.0);
				double smokeVel = frandom(10 + 5 * tier, 20 + 10 * tier);
				A_SpawnItemEx("KakapoRayImpactSpear", 0, 0, 0, smokeVel * cos(pitch), 0, smokeVel * sin(pitch), random(0, 359), SXF_NOCHECKPOSITION);
			}
		}
	}

	protected void SpawnZapper(int num)
	{
		for (let i = 0; i < num; i++)
		{
			A_SpawnItemEx("HDKakapoRayZapper", frandom(-359, 359), frandom(-359, 359), frandom(-359, 359), 0, 0, 0, frandom(0, 359), SXF_NOCHECKPOSITION|SXF_TRANSFERPOINTERS);
		}
	}

	Color pcol1;
	Color pcol2;

	Default
	{
		+FORCEDECAL
		+PUFFGETSOWNER
		+ALWAYSPUFF
		+PUFFONACTORS
		+NOINTERACTION
		+BLOODLESSIMPACT
		+FORCERADIUSDMG
		+NOBLOOD
		+HITTRACER
		Decal "GungnirScorch";
		DamageType "Electrical";
	}

	States
	{
		Spawn:
			TNT1 A 16 NoDelay OnBlast(false);
			Stop;
		Crash:
			TNT1 A 16 OnBlast(true);
			Stop;
	}
}

class KakapoRayImpact : KakapoRayImpactBase
{
	override void OnBlast(bool miss)
	{
		//DoorDestroyer.DestroyDoor(self, 128, 32, dedicated: true);
		A_Explode(random(20, 35), int(HDCONST_ONEMETRE), XF_HURTSOURCE, false, damageType: 'Electrical');
		A_StartSound("Gungnir/RayHit", 8, attenuation: 0.5);
		//DistantQuaker.Quake(self, 2, 50, HDCONST_ONEMETRE * 30, 10, 256, 512, 128);
		SpawnZapper(1);
		SpawnBlastEffects(0, miss);
	}
}

class KakapoRayImpactSpear : Actor
{
	override void PostBeginPlay()
	{
		ReactionTime = int(ReactionTime * frandom(0.10, 1.0));

		Super.PostBeginPlay();
	}

	Default
	{
		+NOINTERACTION
		Gravity 0.4;
		ReactionTime 70;
	}

	Name smoke;

	States
	{
		Spawn:
			TNT1 A 1
			{
				if (!level.IsPointInLevel(pos) || --ReactionTime == 0)
				{
					Destroy();
					return;
				}

				vel *= 0.97;
				vel.z -= 1.0 * Gravity;

				smoke = HDMath.PlayingID() ? "GungnirSmoke" : "GungnirSmokeFD";
				A_SpawnItemEx(smoke);
			}
			Loop;
	}
}

class HDKakapoRayZapper : HDFireball
{
	int KakapoRayRipDmg;
	default{
		-notelestomp +telestomp
		+skyexplode +forceradiusdmg +ripper -noteleport +notarget
		+bright
		decal "HDBFGLightning";
		renderstyle "add";
		damagefunction(KakapoRayRipDmg);
		seesound "weapons/plasmaf";
		deathsound "weapons/bfgx";
		obituary "$OB_MPBFG_BOOM";
		translation "160:160=115:115", "224:229=112:116";
		scale 0.6;
		alpha 0.9;
		height 6;
		radius 6;
		speed 35;
		gravity 0;
		ReactionTime 16;
	}
	override void postbeginplay(){
		rcol = HDMath.PlayingID() ? 0x55ff88 : 0x0093FF;
		pcol = HDMath.PlayingID() ? 0xAAFF42 : 0x0093FF;
	}
	void A_KakapoBlastZap(){
		if(pos.z-floorz<12)vel.z+=1;
		else if(ceilingz-pos.z<19)vel.z-=1;

		for(int i=0;i<10;i++){
			A_SpawnParticle(pcol, SPF_FULLBRIGHT | SPF_RELATIVE, 0, 0, 0, 0, 12, sizestep: 4.0);
		}

		vector2 oldaim=(angle,pitch);
		blockthingsiterator it=blockthingsiterator.create(self,2048);
		while(it.Next()){
			actor itt=it.thing;
			if(
				(itt.bismonster||itt.player)
				&&itt!=target
				&&itt.health>0
				&&target.ishostile(itt)
				&&checksight(itt)
			){
				A_Face(itt,0,0);
				A_CustomRailgun((0),0,"", rcol,
					RGF_CENTERZ|RGF_SILENT|RGF_NOPIERCING|RGF_FULLBRIGHT,
					0,50.0,"KakapoZAPRayPuff",0,0,2048,18,0.2,1.0
				);
				break;
			}
		}
		angle=oldaim.x;pitch=oldaim.y;
	}
	void A_KakapoRaySplodeZap(){
		blockthingsiterator it=blockthingsiterator.create(self,2048);
		while(it.Next()){
			actor itt=it.thing;
			if(
				(itt.bismonster||itt.player)
				&&itt!=target
				&&itt.health>0
				&&!target.isfriend(itt)
				&&!target.isteammate(itt)
				&&checksight(itt)
			){
				A_Face(itt,0,0);
				int hhh=min(itt.health,4096);
				for(int i=0;i<hhh;i+=1024){
					A_CustomRailgun((0),0,"",rcol,
						RGF_CENTERZ|RGF_SILENT|RGF_NOPIERCING|RGF_FULLBRIGHT,
						0,50.0,"KakapoZAPRayPuff",3,3,2048,18,0.2,1.0
					);
				}
			}
		}
	}

	Color rcol;
	Color pcol;

	states{
	spawn:
		TNT1 A 0
		{
			KakapoRayRipDmg=1;
			let hdp=hdplayerpawn(target);
			if(hdp){
				pitch=hdp.gunpitch;
				angle=hdp.gunangle;
			}else if(
				!!target
				&&IsMoving.Count(target)>=6
			){
				pitch+=frandom(-3,3);
				angle+=frandom(-1,1);
			}
		}
		APLS  AB 2 A_SpawnItemEx("KakapoRayZAPTail",0,0,0,vel.x*0.2,vel.y*0.2,vel.z*0.2,0,168,0);
		APLS  A 0{
			KakapoRayRipDmg=random(100,200);
			bripper=false;
		}
		goto spawn2;
	spawn2:
		APLS AB 1 A_Corkscrew();
		---- A 0 A_KakapoBlastZap();
		APLS AB 1 A_Corkscrew();
		---- A 0 A_KakapoBlastZap();
		APLS AB 1 A_Corkscrew();
		---- A 0 A_KakapoBlastZap();
		TNT1 A 0 A_Countdown;
		loop;
	death:
		APBX A 2;
		//APBX B 2 A_Explode(80,256,1,1,20);
		APBX B 2{
					DistantQuaker.Quake(self,6,100,16384,10,256,512,128);
					DistantNoise.Make(self,"world/bfgfar");
				}
		TNT1 AAAAA 0 A_SpawnItemEx("HDSmokeChunk",random(-2,0),random(-3,3),random(-2,2),random(-5,0),random(-5,5),random(0,5),random(100,260),SXF_TRANSFERPOINTERS|SXF_NOCHECKPOSITION,16);
		APBX CCCC 2 A_KakapoRaySplodeZap();
		APBX CCC 0 A_SpawnItemEx("HDSmoke",random(-4,0),random(-3,3),random(0,4),random(-1,1),random(-1,1),random(1,3),0,SXF_TRANSFERPOINTERS|SXF_NOCHECKPOSITION,16);
		APBX DEF 6;
		APBX F 3 A_FadeOut(0.1);
		wait;
	}
}

class KakapoRayZAPTail:IdleDummy{
	default{
		+forcexybillboard
		scale 0.5;renderstyle "add";
	}
	states{
	spawn:
		APLS AB 2 bright A_FadeOut(0.2);
		loop;
	}
}

class KakapoZAPRayPuff:IdleDummy{
	string pcol;
	default{
		-invisible +forcexybillboard +bloodlessimpact
		+noblood +alwayspuff -allowparticles +puffonactors +puffgetsowner +forceradiusdmg
		+hittracer
		renderstyle "add";
		damagetype "BFGBallAttack";
		scale 0.8;
		obituary "$OB_MPBFG_BOOM";
	}
	states{
	spawn:
		BFE2 A 1 bright nodelay{
			pcol = HDMath.PlayingID() ? "55 88 ff" : "00 93 FF";
			if(target)target=target.target;
			A_StartSound("misc/bfgrail",9005);
		}
		BFE2 A 3 bright{
			A_Explode(random(196,320),320,0);
		}
		BFE2 ABCDE 1 bright{
			A_FadeOut(0.05);
			A_SpawnParticle(
				pcol,SPF_FULLBRIGHT,35,
				size:frandom(1,8),0,
				frandom(-16,16),frandom(-16,16),frandom(0,8),
				frandom(-1,1),frandom(-1,1),frandom(1,2),
				frandom(-0.1,0.1),frandom(-0.1,0.1),-0.05
			);
		}
		TNT1 A 0 A_SpawnItemEx("BFGNecroShard",0,0,10,10,0,0,random(0,360),SXF_NOCHECKPOSITION|SXF_TRANSFERPOINTERS,254);
		stop;
	}
}