class HDShotPistol:HDHandgun{
    default{
        +hdweapon.fitsinbackpack
        +hdweapon.reverseguninertia
        scale 0.63;
        weapon.selectionorder 50;
        weapon.slotnumber 2;
        weapon.slotpriority 2;
        weapon.kickback 30;
        weapon.bobrangex 0.1;
        weapon.bobrangey 0.6;
        weapon.bobspeed 2.5;
        weapon.bobstyle "normal";
        obituary "$OB_SHOTPISTOL";
        inventory.pickupmessage "$PICKUP_SHOTPISTOL";
        tag "$TAG_SHOTPISTOL";
        hdweapon.refid HDLD_SHTPSTL;
        hdweapon.barrelsize 16,0.3,0.5;

        hdweapon.ammo1 "HD066Clip10",1;

		hdweapon.loadoutcodes "
			\cusuppressor - 0/1, significantly quieter shots at the cost of low shotpower
			\cuchoke - 0-4, 0 skeet, 4 full; incompatible with suppressor";
    }

	double shotpower;
    int handrounds;
	const SHOTPIS_MINSHOTPOWER=0.851;
    private transient CVar AHelpText;

	//returns the power of the load just fired
	static double Fire(actor caller,int choke=1, int suppressor=0){
		double spread=6.;
		double speedfactor=1.;
		let hhh=HDShotPistol(caller.findinventory("HDShotPistol"));
		if(hhh)choke=hhh.weaponstatus[SPSTS_CHOKE];
		if(hhh)suppressor=hhh.weaponstatus[SPSTS_SUPPRESSOR];

		choke=clamp(choke,0,4);
		spread=10.5-0.25*choke;
		speedfactor=1.15+0.02857*choke;

		double shotpower=(suppressor?frandom(0.58,0.92):frandom(0.84,1.05));
		spread*=shotpower;
		speedfactor*=shotpower;
		HDBulletActor.FireBullet(caller,"HDB_wad");
		let p=HDBulletActor.FireBullet(caller,"HDB_000",spread:spread,speedfactor:speedfactor,amount:5);
		caller.A_StartSound("weapons/shotpistolprefire",8,CHANF_OVERLAP,0.9);
		if(!suppressor)distantnoise.make(caller,"world/shotgunfar",pitch:0.85,volume:0.75);
		caller.A_StartSound(suppressor?"weapons/shotpistolsuppressed":"weapons/shotpistol",CHAN_WEAPON,CHANF_OVERLAP);
		return shotpower;
	}
	action void A_FireShotpistol(){
		double shotpower=invoker.Fire(self);
		vector2 shotrecoil=(randompick(-1,1),-2.6);
		shotrecoil=(randompick(-1,1)*1.4,-3.4);
		shotrecoil*=shotpower;
		A_MuzzleClimb(0,0,shotrecoil.x,shotrecoil.y,randompick(-1,1)*shotpower,-0.3*shotpower);
		if(shotpower<SHOTPIS_MINSHOTPOWER)invoker.weaponstatus[SPSTS_CHAMBER]=1;
		invoker.shotpower=shotpower;
	}
    override double weaponbulk(){
        int mgg=weaponstatus[SPSTS_MAG];
        return 37+(mgg<0?0:(ENC_9MAG_LOADED+mgg*ENC_069BORE_LOADED));
    }
    override double gunmass(){
        int mgg=weaponstatus[SPSTS_MAG];
        return 4.5+(mgg<0?0:0.08*(mgg+1));
    }
    override void failedpickupunload(){
        failedpickupunloadmag(SPSTS_MAG,"HD066Clip10");
    }
   	override string,double getpickupsprite(){
		string spr;
		string type;
		if(weaponstatus[0]&SPSTS_SUPPRESSOR){
			type="SPPS";
		}else{
			type="SPIP";
		}
		if(weaponstatus[SPSTS_CHAMBER]<1){
			spr="B";
		}else{
			spr="A";
		}
		return type..spr.."0",1.;
	}
    override void DrawHUDStuff(HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl){
        if(sb.hudlevel==1){
			int nextmagloaded=sb.GetNextLoadMag(hdmagammo(hpl.findinventory("HD066Clip10")));
			if(nextmagloaded<1){
				sb.drawimage("6CLPF0",(-50,-3),sb.DI_SCREEN_CENTER_BOTTOM,alpha:nextmagloaded?0.6:1.,scale:(1.2,1.2));
			}else if(nextmagloaded<3){
				sb.drawimage("6CLPE0",(-50,-3),sb.DI_SCREEN_CENTER_BOTTOM,scale:(1.2,1.2));
			}else if(nextmagloaded<5){
				sb.drawimage("6CLPD0",(-50,-3),sb.DI_SCREEN_CENTER_BOTTOM,scale:(1.2,1.2));
			}else if(nextmagloaded<7){
				sb.drawimage("6CLPC0",(-50,-3),sb.DI_SCREEN_CENTER_BOTTOM,scale:(1.2,1.2));
			}else if(nextmagloaded<9){
				sb.drawimage("6CLPB0",(-50,-3),sb.DI_SCREEN_CENTER_BOTTOM,scale:(1.2,1.2));
			}else sb.drawimage("6CLPA0",(-50,-3),sb.DI_SCREEN_CENTER_BOTTOM,scale:(1.2,1.2));
			sb.drawnum(hpl.countinv("HD066Clip10"),-43,-8,sb.DI_SCREEN_CENTER_BOTTOM);

			int sevenrounds=hpl.countinv("HD069BoreAmmo");
			sb.drawimage("42BRA0",(-62,-4),sb.DI_SCREEN_CENTER_BOTTOM,alpha:sevenrounds?1:0.6,scale:(1.2,1.2));
			sb.drawnum(sevenrounds,-56,-8,sb.DI_SCREEN_CENTER_BOTTOM);
        }
        sb.drawwepnum(hdw.weaponstatus[SPSTS_MAG],10);
        if(hdw.weaponstatus[SPSTS_CHAMBER]>1){
			sb.drawrect(-22,-12,4,2);
			sb.drawrect(-17,-12,1,2);
		}
		else if(hdw.weaponstatus[SPSTS_CHAMBER]>0){
			sb.drawrect(-17,-12,1,2);
		}
    }
    override string gethelptext(){
        LocalizeHelp();
        if(!AHelpText) AHelpText = CVar.GetCVar('mm_advanced_helptext', owner.player);
        return
        LWPHELP_FIRE..StringTable.Localize("$SHOOT_CH")..weaponstatus[SPSTS_CHOKE]..")\n"
		..LWPHELP_ALTFIRE..StringTable.Localize("$SHTPWH_ALTFIRE")
        ..LWPHELP_RELOAD..StringTable.Localize("$PISWH_RELOAD")
        ..LWPHELP_ALTFIRE.."+"..LWPHELP_RELOAD..StringTable.Localize("$PISWH_UPRELOAD")
		..LWPHELP_ALTFIRE.."+"..LWPHELP_UNLOAD..StringTable.Localize("$SHTPWH_AFIREPUNL")
        ..LWPHELP_MAGMANAGER
        ..LWPHELP_UNLOADUNLOAD
        ..(AHelpText.GetBool() ? Stringtable.Localize("$WEPHELP_INFO") : "")
        ..(AHelpText.GetBool() ? Stringtable.Localize("$SHTPWH_RTYPE") : "")
        ..(AHelpText.GetBool() && WeaponStatus[SPSTS_SUPPRESSOR]>0 ? Stringtable.Localize("$SHTPWH_SUPPR") : "")
        ..(AHelpText.GetBool() ? Stringtable.Localize("$SHTPWH_WTYPE") : "");
    }
    override void DrawSightPicture(
        HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl,
        bool sightbob,vector2 bob,double fov,bool scopeview,actor hpc
    ){
        int cx,cy,cw,ch;
        [cx,cy,cw,ch]=screen.GetClipRect();
        vector2 scc;
        vector2 bobb=bob*1.3;

        //if slide is pushed back, throw sights off line
        if(hpl.player.getpsprite(PSP_WEAPON).frame>=2){
            sb.SetClipRect(
                -10+bob.x,-10+bob.y,20,19,
                sb.DI_SCREEN_CENTER
            );
            bobb.y-=2;
            scc=(0.9,1.0);
        }else{
            sb.SetClipRect(
                -8+bob.x,-9+bob.y,16,15,
                sb.DI_SCREEN_CENTER
            );
            scc=(0.8,0.8);
        }
        sb.drawimage(
            "frntsite",(0,0)+bobb,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP,
            scale:scc
        );
        sb.SetClipRect(cx,cy,cw,ch);
        sb.drawimage(
            "backsite",(0,0)+bob,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP,
            alpha:0.9,
            scale:scc
        );
    }
    override void DropOneAmmo(int amt){
        if(owner){
            amt=clamp(amt,1,10);
            if(owner.countinv("HD069BoreAmmo"))owner.A_DropInventory("HD069BoreAmmo",amt*10);
            else owner.A_DropInventory("HD066Clip10",amt);
        }
    }
    override void ForceBasicAmmo(){
        owner.A_TakeInventory("HD069BoreAmmo");
        ForceOneBasicAmmo("HD066Clip10");
    }
    states{
    select0:
        SPST A 0;
        goto select0big;

    deselect0:
        SPST A 0;
        goto deselect0big;

    ready:
        SPST A 0 A_JumpIf(invoker.weaponstatus[SPSTS_CHAMBER]>0,2);
        #### A 0;
        #### # 0 A_SetCrosshair(21);
        #### # 1 A_WeaponReady(WRF_ALL);
        goto readyend;
    user3:
        ---- A 0 A_MagManager("HD066Clip10");
        goto ready;
    chamber_manual:
        ---- A 0 A_JumpIf(
            !(invoker.weaponstatus[0]&SPSTF_JUSTUNLOAD)
            &&(
                invoker.weaponstatus[SPSTS_CHAMBER]==2
                ||invoker.weaponstatus[SPSTS_MAG]<1
            )
            ,"nope"
        );
        #### A 3 offset(0,34);
        #### A 4 offset(0,37){
            A_MuzzleClimb(frandom(0.4,0.5),-frandom(0.6,0.8));
            A_StartSound("weapons/shotpistol_chamber",8);
            int psch=invoker.weaponstatus[SPSTS_CHAMBER];
            invoker.weaponstatus[SPSTS_CHAMBER]=0;
            if(psch==2){
                A_EjectCasing("HD069BoreAmmo",
                    frandom(-1,2),
                    (-frandom(2,3),frandom(0,0.2),frandom(0.4,0.5)),
                    (-2,0,-1)
                );
            }else if(psch==1){
                A_EjectCasing("HDSpent069Bore",
                    -frandom(-1,2),
                    (frandom(0.4,0.7),-frandom(6,7),frandom(0.8,1)),
                    (-2,0,-1)
                );
            }
            if(invoker.weaponstatus[SPSTS_MAG]>0){
                invoker.weaponstatus[SPSTS_CHAMBER]=2;
                invoker.weaponstatus[SPSTS_MAG]--;
            }
        }
        #### A 3 offset(0,35);
        goto nope;
    hold:
        goto nope;
    fire:
        ---- A 0{
            invoker.weaponstatus[0]&=~SPSTF_JUSTUNLOAD;
            if(invoker.weaponstatus[SPSTS_CHAMBER]==2)setweaponstate("shoot");
        }goto nope;
    shoot:
        #### A 1{
            if(invoker.weaponstatus[SPSTS_CHAMBER]==2)A_GunFlash();
        }
        #### A 1{
            if(hdplayerpawn(self)){
                hdplayerpawn(self).gunbraced=false;
            }
            A_MuzzleClimb(
                -frandom(0.8,1.),-frandom(1.2,1.6),
                frandom(0.4,0.5),frandom(0.6,0.8)
            );
            invoker.weaponstatus[SPSTS_CHAMBER]=0;
            A_EjectCasing("HDSpent069Bore"
                ,frandom(-1,2),
                (frandom(0.4,0.7),-frandom(6,7),frandom(0.8,1))
            );
            A_WeaponReady(WRF_NOFIRE);
        }
        #### A 0{
            if(invoker.weaponstatus[SPSTS_MAG]<1){
                A_StartSound("weapons/shotpistoldry",8,CHANF_OVERLAP,0.9);
                setweaponstate("nope");
            }else if(invoker.shotpower>SHOTPIS_MINSHOTPOWER){
                invoker.weaponstatus[SPSTS_CHAMBER]=2;
                invoker.weaponstatus[SPSTS_MAG]--;
            }
			else{
				invoker.weaponstatus[SPSTS_CHAMBER]=1;
			}
        }
        #### A 1 A_Refire();
        goto ready;
	flash:
		SPST F 0;
		---- F 1 bright{
			HDFlashAlpha(64);
			A_Light1();
            A_FireShotpistol();
            A_ZoomRecoil(0.93);
            int suppressor;
            if(invoker.WeaponStatus[SPSTS_SUPPRESSOR])suppressor=2;
            else suppressor=25;
            A_AlertMonsters(HDCONST_ONEMETRE * (suppressor));
		}
		---- A 0 A_Light0();
		stop;
	AltFire:
		SPST A 1 Offset(1, 32) A_WeaponBusy();
		#### A 1 Offset(1, 34);
		#### A 1 Offset (2, 36);
		#### A 1 Offset(2, 38) A_MuzzleClimb(-frandom(0.06,0.1),-frandom(0.3,0.5));
		#### A 1 Offset(2, 40);
		#### A 0 A_Refire("chamber");
		goto ready;

	AltHold:
		SPST A 1 A_WeaponReady(WRF_NOFIRE);
		#### A 1{
			A_ClearRefire();
			bool ChamberEmpty = invoker.WeaponStatus[SPSTS_CHAMBER]<1;
			if (PressingUnload())
			{
				if(ChamberEmpty)
				{
					return resolvestate("AltHold");
				}
				else
				{
					invoker.WeaponStatus[SPSTS_LoadType] = 0;
					return resolvestate("loadchamber");
				}
			}
			else if(PressingReload())
			{
				if(!ChamberEmpty)
				{
					invoker.WeaponStatus[SPSTS_LoadType] = 0;
					return resolvestate("loadchamber");
				}
				else if (CheckInventory("HD069BoreAmmo", 1))
				{
					invoker.WeaponStatus[SPSTS_LoadType] = 1;
					return resolvestate("loadchamber");
				}
			}
			if (PressingAltFire())
			{
				return ResolveState("AltHold");
			}
			return resolvestate("altholdend");
		}
	chamber:
		SPST A 2 offset(2,38)A_StartSound("weapons/spstslideback",8);
		SPST A 2 offset(1,42)A_JumpIf(invoker.weaponstatus[0]&SPSTS_SUPPRESSOR,1);
		SPST A 1 offset(1,46){
			if(gunbraced())A_MuzzleClimb(
				frandom(-0.1,0.3),frandom(-0.1,0.3)
			);else A_MuzzleClimb(
				frandom(-0.2,0.8),frandom(-0.4,0.8)
			);
		}
		SPST A 2 offset(1,42){
			//eject
			int chm=invoker.weaponstatus[SPSTS_CHAMBER];
			double cp=cos(pitch);
			double sp=sin(pitch);
			if(chm>1){
				A_SpawnItemEx(
					"HD069BoreAmmo",cp*8,1,height-7-sp*8,
					cp*cos(angle-80)*4+vel.x,
					cp*sin(angle-80)*4+vel.y,
					-sp*4+vel.z,
					0,SXF_ABSOLUTEMOMENTUM|SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH
				);
			}else if(chm==1){
				A_SpawnItemEx(
					"HDSpent069Bore",cp*8,1,height-7-sp*8,
					cp*cos(angle-80)*6+vel.x,
					cp*sin(angle-80)*6+vel.y,
					-sp*6+vel.z,
					0,SXF_ABSOLUTEMOMENTUM|SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH
				);
			}
			//cycle new
			if(invoker.weaponstatus[SPSTS_MAG]>0){  
				invoker.weaponstatus[SPSTS_CHAMBER]=2;
				invoker.weaponstatus[SPSTS_MAG]--;
			}else invoker.weaponstatus[SPSTS_CHAMBER]=0;
		}
		SPST A 1 offset(1,42) A_WeaponReady(WRF_NOFIRE);
		SPST A 0 A_Refire("althold");
		goto altholdend;

	AltHoldEnd:
		#### A 1 offset(1,36) A_StartSound("weapons/spstslidefwd", 8);
		#### A 1 offset(1,32);
		Goto Ready;
    unload:
        ---- A 0{
            invoker.weaponstatus[0]|=SPSTF_JUSTUNLOAD;
            if(invoker.weaponstatus[SPSTS_MAG]>=0)setweaponstate("unmag");
        }goto chamber_manual;
    loadchamber:
        ---- A 0 A_JumpIf(invoker.weaponstatus[SPSTS_CHAMBER]>0,"nope");
        ---- A 1 offset(0,36) A_StartSound("weapons/pocket",9);
        ---- A 1 offset(2,40);
        ---- A 1 offset(2,50);
        ---- A 1 offset(3,60);
        ---- A 2 offset(5,90);
        ---- A 2 offset(7,80);
        ---- A 2 offset(10,90);
        #### A 2 offset(8,96);
        #### A 3 offset(6,88){
            if(countinv("HD069BoreAmmo")){
                A_TakeInventory("HD069BoreAmmo",1,TIF_NOTAKEINFINITE);
                invoker.weaponstatus[SPSTS_CHAMBER]=2;
                A_StartSound("weapons/shotpistolchamber",8);
            }
        }
        #### A 2 offset(5,76);
        #### A 1 offset(4,64);
        #### A 1 offset(3,56);
        #### A 1 offset(2,48);
        #### A 2 offset(1,38);
        #### A 3 offset(0,34);
        goto readyend;
    reload:
		---- A 0{invoker.weaponstatus[0]&=~SPSTF_DONTUSECLIPS;}
		goto reloadstart;
	altreload:
		---- A 0{invoker.weaponstatus[0]|=SPSTF_DONTUSECLIPS;}
		goto reloadstart;
	reloadstart:
		SPST A 1 offset(0,34);
		SPST A 1 offset(2,36);
		SPST A 1 offset(4,40);
		SPST A 1 offset(8,42){
			A_StartSound("weapons/spstloads",8,CHANF_OVERLAP,0.9,pitch:0.95);
			A_MuzzleClimb(-frandom(0.4,0.8),frandom(0.4,1.4));
		}
		SPST A 2 offset(14,46){
			A_StartSound("weapons/spstloadm",8,CHANF_OVERLAP);
			A_MuzzleClimb(-frandom(0.4,0.8),frandom(0.4,1.4));
		}
		SPST A 0{
			int mg=invoker.weaponstatus[SPSTS_MAG];
			if(mg==10)setweaponstate("reloaddone");
			else if(invoker.weaponstatus[0]&SPSTF_DONTUSECLIPS)setweaponstate("loadhand");
			else if(
				(
					mg<1
					||!countinv("HD069BoreAmmo")
				)&&!HDMagAmmo.NothingLoaded(self,"HD066Clip10")
			)setweaponstate("loadclip");
		}
	loadhand:
		SPST A 0 A_JumpIfInventory("HD069BoreAmmo",1,"loadhandloop");
		goto reloaddone;
	loadhandloop:
		SPST A 4{
			int hnd=min(
				countinv("HD069BoreAmmo"),3,
				10-invoker.weaponstatus[SPSTS_MAG]
			);
			if(hnd<1){
				setweaponstate("reloaddone");
				return;
			}else{
				A_TakeInventory("HD069BoreAmmo",hnd,TIF_NOTAKEINFINITE);
				invoker.handrounds=hnd;
				A_StartSound("weapons/pocket",9);
			}
		}
	loadone:
		SPST A 2 offset(16,50) A_JumpIf(invoker.handrounds<1,"loadhandnext");
		SPST A 4 offset(14,46){
			invoker.handrounds--;
			invoker.weaponstatus[SPSTS_MAG]++;
			A_StartSound("weapons/spstloadm",8);
		}loop;
	loadhandnext:
		SPST A 5 offset(16,48){
			if(
				PressingReload()||
				PressingFire()||
				PressingAltFire()||
				PressingZoom()||
				!countinv("HD069BoreAmmo")	//don't strip clips automatically
			)setweaponstate("reloaddone");
			else A_StartSound("weapons/pocket",9);
		}goto loadhandloop;
	loadclip:
		SPST A 0 A_JumpIf(invoker.weaponstatus[SPSTS_MAG]>9,"reloaddone");
		SPST A 1 offset(16,50){
			let ccc=hdmagammo(findinventory("HD066Clip10"));
			if(ccc){
				//find the last mag that has anything in it and load from that
				bool fullmag=false;
				int magindex=-1;
				for(int i=ccc.mags.size()-1;i>=0;i--){
					if(ccc.mags[i]>=10)fullmag=true;
					if(magindex<0&&ccc.mags[i]>0)magindex=i;
					if(fullmag&&magindex>0)break;
				}
				if(magindex<0){
					setweaponstate("reloaddone");
					return;
				}

				//load the whole clip at once if possible
				if(
					fullmag
					&&invoker.weaponstatus[SPSTS_MAG]<1
				){
					setweaponstate("loadwholeclip");
					return;
				}

				//strip one round and load it
				A_StartSound("weapons/spstloadm",CHAN_WEAPONBODY);
				invoker.weaponstatus[SPSTS_MAG]++;
				ccc.mags[magindex]--;
			}
		}
		SPST A 3 offset(16,52) A_JumpIf(
			PressingReload()||
			PressingFire()||
			PressingAltFire()||
			PressingZoom()
		,"reloaddone");
		loop;
	loadwholeclip:
		SPST A 3 offset(16,50) A_StartSound("weapons/spstloads",8);
		SPST AAA 2 offset(17,52) A_StartSound("weapons/spstloads",8,pitch:1.01);
		SPST AAA 1 offset(16,50) A_StartSound("weapons/spstloads",8,CHANF_OVERLAP,pitch:1.02);
		SPST AAA 1 offset(15,48) A_StartSound("weapons/spstloads",8,CHANF_OVERLAP,pitch:1.02);
		SPST A 1 offset(14,46){
			A_StartSound("weapons/rifleclick",CHAN_WEAPONBODY);
			let ccc=hdmagammo(findinventory("HD066Clip10"));
			if(ccc){
				invoker.weaponstatus[SPSTS_MAG]=ccc.TakeMag(true);
				if(pressingreload()){
					ccc.addamag(0);
					A_SetTics(10);
					A_StartSound("weapons/pocket",CHAN_POCKETS);
				}else HDMagAmmo.SpawnMag(self,"HD066Clip10",0);
			}
		}goto reloaddone;
	reloaddone:
		SPST A 1 offset(4,40);
		SPST A 1 offset(2,36);
		SPST A 1 offset(0,34);
		goto nope;
    unload:
		SPST A 1 offset(0,34);
		SPST A 1 offset(2,36);
		SPST A 1 offset(4,40);
		SPST A 2 offset(8,42){
			A_MuzzleClimb(-frandom(0.4,0.8),frandom(0.4,1.4));
			A_StartSound("weapons/spstloads",8);
		}
		SPST A 4 offset (14,46){
			A_MuzzleClimb(-frandom(0.4,0.8),frandom(0.4,1.4));
			A_StartSound("weapons/spstloadm",8);
		}
	unloadloop:
		SPST A 4 offset(3,41){
			if(invoker.weaponstatus[SPSTS_MAG]<1)setweaponstate("unloaddone");
			else{
				A_StartSound("weapons/spstloads",8);
				invoker.weaponstatus[SPSTS_MAG]--;
				if(A_JumpIfInventory("HD069BoreAmmo",0,"null")){
					A_SpawnItemEx(
						"HD069BoreAmmo",cos(pitch)*8,0,height-7-sin(pitch)*8,
						cos(pitch)*cos(angle-40)*1+vel.x,
						cos(pitch)*sin(angle-40)*1+vel.y,
						-sin(pitch)*1+vel.z,
						0,SXF_ABSOLUTEMOMENTUM|
						SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH
					);
				}else A_GiveInventory("HD069BoreAmmo",1);
			}
		}
		SPST A 2 offset(2,42);
		SPST A 0{
			if(
				PressingReload()||
				PressingFire()||
				PressingAltFire()||
				PressingZoom()
			)setweaponstate("unloaddone");
		}loop;
	unloaddone:
		SPST A 2 offset(2,42);
		SPST A 3 offset(3,41);
		SPST A 1 offset(4,40) A_StartSound("weapons/spstslidefwd",8);
		SPST A 1 offset(2,36);
		SPST A 1 offset(0,34);
		goto ready;

	user1:
        goto nope;

    spawn:
	SPIP AB -1 nodelay{
			if(invoker.weaponstatus[SPSTS_CHAMBER]<1){
			frame=1;
			}else{
			frame=0;
			}
			if(invoker.weaponstatus[SPSTS_SUPPRESSOR])invoker.sprite=getspriteindex("SPPSA0");
		}
		SPPS # -1;
		stop;
	}
    override void initializewepstats(bool idfa){
        weaponstatus[SPSTS_MAG]=10;
        weaponstatus[SPSTS_CHAMBER]=2;
        if(!idfa){
            weaponstatus[SPSTS_CHOKE]=1;
        }
    }
	override void loadoutconfigure(string input){
		int choke=min(getloadoutvar(input,"choke",1),4);
		if(choke>=0)weaponstatus[SPSTS_CHOKE]=choke;
        int suppressor=getloadoutvar(input,"suppressor",1);
		if(suppressor>=1){
            weaponstatus[SPSTS_SUPPRESSOR]=1;
            weaponstatus[SPSTS_CHOKE]=1;
        }
	}
}
enum Shotpistolstatus{
    SPSTF_JUSTUNLOAD=1,
    SPSTF_DONTUSECLIPS=2,

    SPSTS_FLAGS=0,
    SPSTS_MAG=1,
    SPSTS_CHAMBER=2, //0 empty, 1 spent, 2 loaded
    SPSTS_CHOKE=3,
    SPSTS_SUPPRESSOR=4,
	SPSTS_LoadType=5,
};

class HDShotpistolRandom:IdleDummy{
	states{
	spawn:
		TNT1 A 0 nodelay{
			let zzz=HDShotPistol(spawn("HDShotPistol",pos,ALLOW_REPLACE));
			if(!zzz)return;
			HDF.TransferSpecials(self,zzz,HDF.TS_ALL);
			if(!random(0,4))zzz.weaponstatus[SPSTS_CHOKE]=random(random(0,4),4);
			else if(!random(0,3))zzz.weaponstatus[0]|=SPSTS_SUPPRESSOR;
			spawn("HD066Clip10",pos+(7,0,0),ALLOW_REPLACE);
			spawn("HD066Clip10",pos+(5,0,0),ALLOW_REPLACE);
		}stop;
	}
}

class HD066Clip10:HDMagAmmo{
	default{
		//$Category "Ammo/Hideous Destructor/"
		//$Title "Boss Clip"
		//$Sprite "RCLPA0"

		hdmagammo.maxperunit 10;
		hdmagammo.roundtype "HD069BoreAmmo";
		hdmagammo.roundbulk ENC_069BORE_LOADED;
		hdmagammo.magbulk ENC_776CLIP_EMPTY;
		hdpickup.refid HDLD_066MAG10;
		tag "$TAG_066MAG10";
		inventory.pickupmessage "$PICKUP_066MAG10";
		scale 0.6;
	}
	override string,string,name,double getmagsprite(int thismagamt){
		string magsprite;
		thismagamt=thismagamt%100;
		if(thismagamt>8)magsprite="6CLPA0";
		else if(thismagamt>6)magsprite="6CLPB0";
		else if(thismagamt>4)magsprite="6CLPC0";
		else if(thismagamt>2)magsprite="6CLPD0";
		else if(thismagamt>0)magsprite="6CLPE0";
		else magsprite="6CLPF0";
		return magsprite,"42BRA0","HD069BoreAmmo",1.5;
	}
	states(actor){
	spawn:
		6CLP ABCDE -1 nodelay{
			if(!mags.size()){destroy();return;}
			int amt=mags[0]%100;
			if(amt>8)frame=0;
			else if(amt>6)frame=1;
			else if(amt>4)frame=2;
			else if(amt>2)frame=3;
			else if(amt>0)frame=4;
		}stop;
	spawnempty:
		6CLP F -1;
		stop;
	}
}