class HDShotPistol:HDHandgun{
    default{
        +hdweapon.fitsinbackpack
        +hdweapon.reverseguninertia
        scale 0.63;
        weapon.selectionorder 50;
        weapon.slotnumber 2;
        weapon.slotpriority 2;
        weapon.kickback 30;
        weapon.bobrangex 0.1;
        weapon.bobrangey 0.6;
        weapon.bobspeed 2.5;
        weapon.bobstyle "normal";
        obituary "$OB_SHOTPISTOL";
        inventory.pickupmessage "$PICKUP_SHOTPISTOL";
        tag "$TAG_SHOTPISTOL";
        hdweapon.refid HDLD_SHTPSTL;
        hdweapon.barrelsize 19,0.3,0.5;

        hdweapon.ammo1 "HD066Mag10",1;

		hdweapon.loadoutcodes "
			\cuchoke - 0-7, 0 skeet, 7 full";
    }
	double shotpower;
	//returns the power of the load just fired
	static double Fire(actor caller,int choke=1){
		double spread=6.;
		double speedfactor=1.;
		let hhh=HDShotPistol(caller.findinventory("HDShotPistol"));
		if(hhh)choke=hhh.weaponstatus[SPSTS_CHOKE];

		choke=clamp(choke,0,7);
		spread=6.5-0.5*choke;
		speedfactor=1.+0.02857*choke;

		double shotpower=frandom(0.9,1.05);
		spread*=shotpower;
		speedfactor*=shotpower;
		HDBulletActor.FireBullet(caller,"HDB_wad");
		let p=HDBulletActor.FireBullet(caller,"HDB_000",spread:spread,speedfactor:speedfactor,amount:8);
		distantnoise.make(caller,"world/shotgunfar");
		caller.A_StartSound("weapons/hunter",CHAN_WEAPON,CHANF_OVERLAP);
		return shotpower;
	}
	action void A_FireShotpistol(){
		double shotpower=invoker.Fire(self);
		vector2 shotrecoil=(randompick(-1,1),-2.6);
		shotrecoil=(randompick(-1,1)*1.4,-3.4);
		shotrecoil*=shotpower;
		A_MuzzleClimb(0,0,shotrecoil.x,shotrecoil.y,randompick(-1,1)*shotpower,-0.3*shotpower);
		invoker.weaponstatus[SPSTS_CHAMBER]=1;
		invoker.shotpower=shotpower;
	}
    override double weaponbulk(){
        int mgg=weaponstatus[SPSTS_MAG];
        return 30+(mgg<0?0:(ENC_9MAG_LOADED+mgg*ENC_9_LOADED));
    }
    override double gunmass(){
        int mgg=weaponstatus[SPSTS_MAG];
        return 3.5+(mgg<0?0:0.08*(mgg+1));
    }
    override void failedpickupunload(){
        failedpickupunloadmag(SPSTS_MAG,"HD066Mag10");
    }
    override string,double getpickupsprite(bool usespare){
        return "SPSTP0",1.;
    }
    override void DrawHUDStuff(HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl){
        if(sb.hudlevel==1){
            int nextmagloaded=sb.GetNextLoadMag(hdmagammo(hpl.findinventory("HD066Mag10")));
            if(nextmagloaded>=10){
                sb.drawimage("CLP2NORM",(-46,-3),sb.DI_SCREEN_CENTER_BOTTOM,scale:(1,1));
            }else if(nextmagloaded<1){
                sb.drawimage("CLP2EMPTY",(-46,-3),sb.DI_SCREEN_CENTER_BOTTOM,alpha:nextmagloaded?0.6:1.,scale:(1,1));
            }else sb.drawbar(
                "CLP2NORM","CLP2GREY",
                nextmagloaded,10,
                (-46,-3),-1,
                sb.SHADER_VERT,sb.DI_SCREEN_CENTER_BOTTOM
            );
            sb.drawnum(hpl.countinv("HD066Mag10"),-43,-8,sb.DI_SCREEN_CENTER_BOTTOM);
        }
        sb.drawwepnum(hdw.weaponstatus[SPSTS_MAG],10);
        if(hdw.weaponstatus[SPSTS_CHAMBER]==2)sb.drawrect(-19,-11,3,1);
    }
    override string gethelptext(){
        LocalizeHelp();
        return
        LWPHELP_FIRESHOOT
        ..LWPHELP_ALTRELOAD..StringTable.Localize("$PISWH_ALTRELOAD")
        ..LWPHELP_RELOAD..StringTable.Localize("$PISWH_RELOAD")
        ..LWPHELP_USE.."+"..LWPHELP_RELOAD..StringTable.Localize("$PISWH_UPRELOAD")
        ..LWPHELP_MAGMANAGER
        ..LWPHELP_UNLOADUNLOAD
        ;
    }
    override void DrawSightPicture(
        HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl,
        bool sightbob,vector2 bob,double fov,bool scopeview,actor hpc
    ){
        int cx,cy,cw,ch;
        [cx,cy,cw,ch]=screen.GetClipRect();
        vector2 scc;
        vector2 bobb=bob*1.3;

        //if slide is pushed back, throw sights off line
        if(hpl.player.getpsprite(PSP_WEAPON).frame>=2){
            sb.SetClipRect(
                -10+bob.x,-10+bob.y,20,19,
                sb.DI_SCREEN_CENTER
            );
            bobb.y-=2;
            scc=(0.7,0.8);
        }else{
            sb.SetClipRect(
                -8+bob.x,-9+bob.y,16,15,
                sb.DI_SCREEN_CENTER
            );
            scc=(0.6,0.6);
        }
        sb.drawimage(
            "frntsite",(0,0)+bobb,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP,
            scale:scc
        );
        sb.SetClipRect(cx,cy,cw,ch);
        sb.drawimage(
            "backsite",(0,0)+bob,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP,
            alpha:0.9,
            scale:scc
        );
    }
    override void DropOneAmmo(int amt){
        if(owner){
            amt=clamp(amt,1,10);
            if(owner.countinv("HD069BoreAmmo"))owner.A_DropInventory("HD069BoreAmmo",amt*10);
            else owner.A_DropInventory("HD066Mag10",amt);
        }
    }
    override void ForceBasicAmmo(){
        owner.A_TakeInventory("HD069BoreAmmo");
        ForceOneBasicAmmo("HD066Mag10");
    }
    states{
    select0:
        #### A 0 A_Log("Select0");
        SPST A 0;
        goto select0big;

    deselect0:
        #### A 0 A_Log("Deselect0");
        SPST A 0;
        goto deselect0big;

    ready:
        SPST A 0 A_JumpIf(invoker.weaponstatus[SPSTS_CHAMBER]>0,2);
        #### A 0;
        #### # 0 A_SetCrosshair(21);
        #### # 1 A_WeaponReady(WRF_ALL);
        goto readyend;
    user3:
        #### A 0 A_Log("User3");
        ---- A 0 A_MagManager("HD066Mag10");
        goto ready;
    chamber_manual:
        #### A 0 A_Log("Chamber Manual");
        ---- A 0 A_JumpIf(
            !(invoker.weaponstatus[0]&SPSTF_JUSTUNLOAD)
            &&(
                invoker.weaponstatus[SPSTS_CHAMBER]==2
                ||invoker.weaponstatus[SPSTS_MAG]<1
            )
            ,"nope"
        );
        #### A 3 offset(0,34);
        #### A 4 offset(0,37){
            A_MuzzleClimb(frandom(0.4,0.5),-frandom(0.6,0.8));
            A_StartSound("weapons/pischamber2",8);
            int psch=invoker.weaponstatus[SPSTS_CHAMBER];
            invoker.weaponstatus[SPSTS_CHAMBER]=0;
            if(psch==2){
                A_EjectCasing("HD069BoreAmmo",
                    frandom(-1,2),
                    (-frandom(2,3),frandom(0,0.2),frandom(0.4,0.5)),
                    (-2,0,-1)
                );
            }else if(psch==1){
                A_EjectCasing("HDSpent069Bore",
                    -frandom(-1,2),
                    (frandom(0.4,0.7),-frandom(6,7),frandom(0.8,1)),
                    (-2,0,-1)
                );
            }
            if(invoker.weaponstatus[SPSTS_MAG]>0){
                invoker.weaponstatus[SPSTS_CHAMBER]=2;
                invoker.weaponstatus[SPSTS_MAG]--;
            }
        }
        #### A 3 offset(0,35);
        goto nope;
    hold:
        #### A 0 A_Log("Hold");
        goto nope;
    fire:
        #### A 0 A_Log("Fire");
        ---- A 0{
            invoker.weaponstatus[0]&=~SPSTF_JUSTUNLOAD;
            if(invoker.weaponstatus[SPSTS_CHAMBER]==2)setweaponstate("shoot");
            else if(invoker.weaponstatus[SPSTS_MAG]>0)setweaponstate("chamber_manual");
        }goto nope;
    shoot:
        #### A 0 A_Log("Shoot");
        #### A 1{
            if(invoker.weaponstatus[SPSTS_CHAMBER]==2)A_GunFlash();
        }
        #### A 1{
            if(hdplayerpawn(self)){
                hdplayerpawn(self).gunbraced=false;
            }
            A_MuzzleClimb(
                -frandom(0.8,1.),-frandom(1.2,1.6),
                frandom(0.4,0.5),frandom(0.6,0.8)
            );
            invoker.weaponstatus[SPSTS_CHAMBER]=0;
            A_EjectCasing("HDSpent069Bore"
                ,frandom(-1,2),
                (frandom(0.4,0.7),-frandom(6,7),frandom(0.8,1))
            );
            A_WeaponReady(WRF_NOFIRE);
        }
        #### A 0{
            if(invoker.weaponstatus[SPSTS_MAG]<1){
                A_StartSound("weapons/pistoldry",8,CHANF_OVERLAP,0.9);
                setweaponstate("nope");
            }else{
                invoker.weaponstatus[SPSTS_CHAMBER]=2;
                invoker.weaponstatus[SPSTS_MAG]--;
            }
        }
        #### A 1 A_Refire();
        goto ready;
	flash:
		STPF F 0;
		---- F 1 bright{
			HDFlashAlpha(64);
			A_Light1();
            A_FireShotpistol();
            A_AlertMonsters(256);
		}
		---- A 0 A_Light0();
		stop;
    unload:
        #### A 0 A_Log("Unload");
        ---- A 0{
            invoker.weaponstatus[0]|=SPSTF_JUSTUNLOAD;
            if(invoker.weaponstatus[SPSTS_MAG]>=0)setweaponstate("unmag");
        }goto chamber_manual;
    loadchamber:
        #### A 0 A_Log("Loadchamber");
        ---- A 0 A_JumpIf(invoker.weaponstatus[SPSTS_CHAMBER]>0,"nope");
        ---- A 1 offset(0,36) A_StartSound("weapons/pocket",9);
        ---- A 1 offset(2,40);
        ---- A 1 offset(2,50);
        ---- A 1 offset(3,60);
        ---- A 2 offset(5,90);
        ---- A 2 offset(7,80);
        ---- A 2 offset(10,90);
        #### A 2 offset(8,96);
        #### A 3 offset(6,88){
            if(countinv("HD069BoreAmmo")){
                A_TakeInventory("HD069BoreAmmo",1,TIF_NOTAKEINFINITE);
                invoker.weaponstatus[SPSTS_CHAMBER]=2;
                A_StartSound("weapons/pischamber1",8);
            }
        }
        #### A 2 offset(5,76);
        #### A 1 offset(4,64);
        #### A 1 offset(3,56);
        #### A 1 offset(2,48);
        #### A 2 offset(1,38);
        #### A 3 offset(0,34);
        goto readyend;
    reload:
        #### A 0 A_Log("Reload");
        ---- A 0{
            invoker.weaponstatus[0]&=~SPSTF_JUSTUNLOAD;
            bool nomags=HDMagAmmo.NothingLoaded(self,"HD066Mag10");
            if(invoker.weaponstatus[SPSTS_MAG]>=10)setweaponstate("nope");
            else if(
                invoker.weaponstatus[SPSTS_MAG]<1
                &&(
                    pressinguse()
                    ||nomags
                )
            ){
                if(
                    countinv("HD069BoreAmmo")
                )setweaponstate("loadchamber");
                else setweaponstate("nope");
            }else if(nomags)setweaponstate("nope");
        }goto unmag;
    unmag:
        #### A 0 A_Log("Unmag");
        ---- A 1 offset(0,34) A_SetCrosshair(21);
        ---- A 1 offset(1,38);
        ---- A 2 offset(2,42);
        ---- A 3 offset(3,46) A_StartSound("weapons/pismagclick2",8,CHANF_OVERLAP);
        ---- A 0{
            int pmg=invoker.weaponstatus[SPSTS_MAG];
            invoker.weaponstatus[SPSTS_MAG]=-1;
            if(pmg<0)setweaponstate("magout");
            else if(
                (!PressingUnload()&&!PressingReload())
                ||A_JumpIfInventory("HD066Mag10",0,"null")
            ){
                HDMagAmmo.SpawnMag(self,"HD066Mag10",pmg);
                setweaponstate("magout");
            }
            else{
                HDMagAmmo.GiveMag(self,"HD066Mag10",pmg);
                A_StartSound("weapons/pocket",9);
                setweaponstate("pocketmag");
            }
        }
    pocketmag:
        #### A 0 A_Log("Pocket Mag");
        ---- AAA 5 offset(0,46) A_MuzzleClimb(frandom(-0.2,0.8),frandom(-0.2,0.4),wepdot:false);
        goto magout;
    magout:
        #### A 0 A_Log("Magout");
        ---- A 0{
            if(invoker.weaponstatus[0]&SPSTF_JUSTUNLOAD)setweaponstate("reloadend");
            else setweaponstate("loadmag");
        }

    loadmag:
        #### A 0 A_Log("Load Mag");
        ---- A 4 offset(0,46) A_MuzzleClimb(frandom(-0.2,0.8),frandom(-0.2,0.4));
        ---- A 0 A_StartSound("weapons/pocket",9);
        ---- A 5 offset(0,46) A_MuzzleClimb(frandom(-0.2,0.8),frandom(-0.2,0.4));
        ---- A 3;
        ---- A 0{
            let mmm=hdmagammo(findinventory("HD066Mag10"));
            if(mmm){
                invoker.weaponstatus[SPSTS_MAG]=mmm.TakeMag(true);
                A_StartSound("weapons/pismagclick",8);
            }
        }
        goto reloadend;

    reloadend:
        #### A 0 A_Log("Reload end");
        ---- A 2 offset(3,46);
        ---- A 1 offset(2,42);
        ---- A 1 offset(2,38);
        ---- A 1 offset(1,34);
        ---- A 0 A_JumpIf(!(invoker.weaponstatus[0]&SPSTF_JUSTUNLOAD),"chamber_manual");
        goto nope;
	altfire:
	user1:
	altreload:
        #### A 0 A_Log("Altreload");
        goto nope;

    spawn:
        SPST P -1 nodelay;
        stop;
    }
    override void initializewepstats(bool idfa){
        weaponstatus[SPSTS_MAG]=10;
        weaponstatus[SPSTS_CHAMBER]=2;
        if(!idfa){
            weaponstatus[SPSTS_CHOKE]=1;
        }
    }
	override void loadoutconfigure(string input){
		int choke=min(getloadoutvar(input,"choke",1),7);
		if(choke>=0)weaponstatus[SPSTS_CHOKE]=choke;
	}
}
enum Shotpistolstatus{
    SPSTF_JUSTUNLOAD=1,

    SPSTS_FLAGS=0,
    SPSTS_MAG=1,
    SPSTS_CHAMBER=2, //0 empty, 1 spent, 2 loaded
    SPSTS_CHOKE=3,
};

class HD066Mag10:HDMagAmmo{
	default{
		//$Category "Ammo/Hideous Destructor/"
		//$Title "Pistol Magazine"
		//$Sprite "CLP2A0"

		hdmagammo.maxperunit 10;
		hdmagammo.roundtype "HDPistolAmmo";
		hdmagammo.roundbulk ENC_9_LOADED;
		hdmagammo.magbulk ENC_9MAG_EMPTY;
		tag "$TAG_9MMAG10";
		inventory.pickupmessage "$PICKUP_9MMAG";
		hdpickup.refid HDLD_066MAG10;
	}
	override string,string,name,double getmagsprite(int thismagamt){
		string magsprite=(thismagamt>0)?"CLP2NORM":"CLP2EMPTY";
		return magsprite,"PBRSA0","HDPistolAmmo",0.6;
	}
	override void GetItemsThatUseThis(){
		itemsthatusethis.push("DERPUsable");
		itemsthatusethis.push("DERPDEAD");
		itemsthatusethis.push("HDPistol");
	}
	states{
	spawn:
		CLP2 A -1;
		stop;
	spawnempty:
		CLP2 A -1 A_SpawnEmpty();
		stop;
	}
}