// ------------------------------------------------------------
// SMG
// ------------------------------------------------------------
class HDTrocaz:HDWeapon{
	default{
		+hdweapon.fitsinbackpack
		obituary "$OB_SMG";
		weapon.selectionorder 24;
		weapon.slotnumber 2;
		weapon.slotpriority 1;
		weapon.kickback 30;
		weapon.bobrangex 0.3;
		weapon.bobrangey 0.8;
		weapon.bobspeed 2.5;
		scale 0.55;
		inventory.pickupmessage "$PICKUP_TROCAZ";
		hdweapon.barrelsize 26,0.5,1;
		hdweapon.refid HDLD_TROCAZ;
		tag "$TAG_TROCAZ";
		inventory.icon "SMGNA0";

		hdweapon.ammo1 "HD4mMag25",1;

		hdweapon.loadoutcodes "
			\cufiremode - 0-2, semi/burst/auto
			\cufireswitch - 0-4, default/semi/auto/full/all
			\cureflexsight - 0-1, no/yes
			\cudot - 0-5";
	}
	override bool AddSpareWeapon(actor newowner){return AddSpareWeaponRegular(newowner);}
	override hdweapon GetSpareWeapon(actor newowner,bool reverse,bool doselect){return GetSpareWeaponRegular(newowner,reverse,doselect);}
	override double gunmass(){
		return 5+((weaponstatus[TRCProp_MAG]<0)?-0.5:(weaponstatus[TRCProp_MAG]*0.05));
	}
	override double weaponbulk(){
		int mg=weaponstatus[TRCProp_MAG];
		if(mg<0)return 90;
		else return (90+ENC_9MAG30_LOADED)+mg*ENC_9_LOADED;
	}
	override void failedpickupunload(){
		failedpickupunloadmag(TRCProp_MAG,"HD4mMag25");
	}
	override void DropOneAmmo(int amt){
		if(owner){
			amt=clamp(amt,1,10);
			if(owner.countinv("FourMilAmmo"))owner.A_DropInventory("FourMilAmmo",amt*25);
			else owner.A_DropInventory("HD4mMag25",amt);
		}
	}
	override void ForceBasicAmmo(){
		owner.A_TakeInventory("FourMilAmmo");
		ForceOneBasicAmmo("HD4mMag25");
	}
	override string,double getpickupsprite(bool usespare){
        string spr;
        int wep0=GetSpareWeaponValue(0,usespare);
        spr="RIGL";
        //set to no-mag frame
        if(GetSpareWeaponValue(TRCProp_MAG,usespare)<0)spr=spr.."D";
        else spr=spr.."A";

        return spr.."0",1.;
    }
	override void DrawHUDStuff(HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl){
		if(sb.hudlevel==1){
			int nextmagloaded=sb.GetNextLoadMag(hdmagammo(hpl.findinventory("HD4mMag25")));
			if(nextmagloaded>=25){
				sb.drawimage("CLP3A0",(-46,-3),sb.DI_SCREEN_CENTER_BOTTOM,scale:(3,3));
			}else if(nextmagloaded<1){
				sb.drawimage("CLP3B0",(-46,-3),sb.DI_SCREEN_CENTER_BOTTOM,alpha:nextmagloaded?0.6:1.,scale:(3,3));
			}else sb.drawbar(
				"CLP3NORM","CLP3GREY",
				nextmagloaded,30,
				(-46,-3),-1,
				sb.SHADER_VERT,sb.DI_SCREEN_CENTER_BOTTOM
			);
			sb.drawnum(hpl.countinv("HD4mMag25"),-43,-8,sb.DI_SCREEN_CENTER_BOTTOM);
		}
		sb.drawwepnum(hdw.weaponstatus[TRCProp_MAG],25);
		if(hdw.weaponstatus[TRCProp_CHAMBER]==2)sb.drawrect(-19,-11,3,1);
	}
	override string gethelptext(){
		LocalizeHelp();
		return
		LWPHELP_FIRESHOOT
		..LWPHELP_RELOAD..StringTable.Localize("$SMGWH_FIRE")
		..LWPHELP_USE.."+"..LWPHELP_RELOAD..StringTable.Localize("$SMGWH_UPRELOAD")
		..LWPHELP_FIREMODE..StringTable.Localize("$SMGWH_FMODE")
		..LWPHELP_MAGMANAGER
		..LWPHELP_UNLOADUNLOAD
		;
	}
	override void DrawSightPicture(
		HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl,
		bool sightbob,vector2 bob,double fov,bool scopeview,actor hpc
	){
		vector2 bobb=bob*1.18;
		if(weaponstatus[0]&TRCProp_REFLEXSIGHT){
			double dotoff=max(abs(bob.x),abs(bob.y));
			if(dotoff<30){
				string whichdot=sb.ChooseReflexReticle(hdw.weaponstatus[TRCProp_DOT]);
				sb.drawimage(
					whichdot,(0,0)+bobb,sb.DI_SCREEN_CENTER|sb.DI_ITEM_CENTER,
					alpha:0.8-dotoff*0.01,scale:(1.6,1.6),
					col:0xFF000000|sb.crosshaircolor.GetInt()
				);
			}
			sb.drawimage(
				"smgrearsight",(0,0)+bob,sb.DI_SCREEN_CENTER|sb.DI_ITEM_CENTER
			);
		}else{
			int cx,cy,cw,ch;
			[cx,cy,cw,ch]=screen.GetClipRect();
			sb.SetClipRect(
				-16+bob.x,-4+bob.y,32,16,
				sb.DI_SCREEN_CENTER
			);
			sb.drawimage(
				"smgfrntsit",(0,0)+bobb,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP
			);
			sb.SetClipRect(cx,cy,cw,ch);
			sb.drawimage(
				"smgbaksit",(0,0)+bob,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP,
				alpha:0.9
			);
		}
	}
	override void SetReflexReticle(int which){weaponstatus[TRCProp_DOT]=which;}
	action void A_CheckReflexSight(){
		if(
			invoker.weaponstatus[0]&TRCProp_REFLEXSIGHT
		)Player.GetPSprite(PSP_WEAPON).sprite=getspriteindex("SMSGA0");
		else Player.GetPSprite(PSP_WEAPON).sprite=getspriteindex("SMGGA0");
	}
	states{
	select0:
		SMGG A 0 A_CheckDefaultReflexReticle(TRCProp_DOT);
		SMGG A 0 A_CheckReflexSight();
		goto select0small;
	deselect0:
		SMGG A 0 A_CheckReflexSight();
		goto deselect0small;
		SMGG AB 0;
		SMSG AB 0;

	ready:
		SMGG A 0 A_CheckReflexSight();
		#### A 1{
			A_SetCrosshair(21);
			A_WeaponReady(WRF_ALL);
		}
		goto readyend;
	user3:
		---- A 0 A_MagManager("HD4mMag25");
		goto ready;
	altfire:
		goto chamber_manual;
    hold:
	althold:
		goto nope;
	fire:
		#### A 0;
	fire2:
		#### B 1{
			if(invoker.weaponstatus[TRCProp_CHAMBER]==2)A_GunFlash();
			else setweaponstate("chamber_manual");
		}
		#### A 1;
		#### A 0{
			if(invoker.weaponstatus[TRCProp_MAG]>0){
				invoker.weaponstatus[TRCProp_MAG]--;
				invoker.weaponstatus[TRCProp_CHAMBER]=2;
			}

			//don't allow firing if supposed to be lowered
			A_WeaponReady(WRF_NOFIRE);
		}
		#### A 0 A_ReFire();
		goto ready;
	flash:
		#### B 0{
			let bbb=HDBulletActor.FireBullet(self,"HDB_426",speedfactor: 1.1);
			if(
				frandom(16,ceilingz-floorz)<bbb.speed*0.1
			)A_AlertMonsters(200);

			A_ZoomRecoil(0.995);
			A_StartSound("weapons/rifle",CHAN_WEAPON,volume:0.7);
			invoker.weaponstatus[TRCProp_CHAMBER]=1;
		}
		SMGF A 1 bright{
			HDFlashAlpha(-200);
			A_Light1();
		}
		TNT1 A 0 A_MuzzleClimb(-frandom(0.2,0.24),-frandom(0.3,0.36),-frandom(0.2,0.24),-frandom(0.3,0.36));
		goto lightdone;


	unloadchamber:
		#### B 1 A_JumpIf(invoker.weaponstatus[TRCProp_CHAMBER]<1,"nope");
		#### B 2 offset(3,32){
			class<actor>which=invoker.weaponstatus[TRCProp_CHAMBER]>1?"FourMilAmmo":"HDSpent9mm";
			invoker.weaponstatus[TRCProp_CHAMBER]=0;
			
			A_EjectCasing(which,frandom(-1,2),(frandom(0.2,0.3),-frandom(2,2.5),frandom(0,0.2)),(0,0,-2));
			A_StartSound("weapons/smgchamber2",8,CHANF_OVERLAP);
		}
		#### B 3 offset(5,35);
		#### A 1 offset(3,32);
		#### A 1 offset(2,31);
		goto readyend;
	loadchamber:
		---- A 0 A_JumpIf(invoker.weaponstatus[TRCProp_CHAMBER]>0,"nope");
		---- A 0 A_JumpIf(!countinv("FourMilAmmo"),"nope");
		---- A 1 offset(0,34) A_StartSound("weapons/pocket",9);
		---- A 1 offset(2,36);
		---- A 1 offset(2,44);
		#### B 1 offset(5,58);
		#### B 2 offset(7,70);
		#### B 6 offset(8,80);
		#### A 10 offset(8,87){
			if(countinv("FourMilAmmo")){
				A_TakeInventory("FourMilAmmo",1,TIF_NOTAKEINFINITE);
				invoker.weaponstatus[TRCProp_CHAMBER]=2;
				A_StartSound("weapons/smgchamber",8);
			}else A_SetTics(4);
		}
		#### A 3 offset(9,76);
		---- A 2 offset(5,70);
		---- A 1 offset(5,64);
		---- A 1 offset(5,52);
		---- A 1 offset(5,42);
		---- A 1 offset(2,36);
		---- A 2 offset(0,34);
		goto nope;
	user4:
	unload:
		#### A 0{
			invoker.weaponstatus[0]|=TRCProp_JUSTUNLOAD;
			if(
				invoker.weaponstatus[TRCProp_MAG]>=0
			)setweaponstate("unmag");
			else if(invoker.weaponstatus[TRCProp_CHAMBER]>0)setweaponstate("unloadchamber");
		}goto nope;
	reload:
		#### A 0{
			invoker.weaponstatus[0]&=~TRCProp_JUSTUNLOAD;
			bool nomags=HDMagAmmo.NothingLoaded(self,"HD4mMag25");
			if(invoker.weaponstatus[TRCProp_MAG]>=25)setweaponstate("nope");
			else if(
				invoker.weaponstatus[TRCProp_MAG]<1
				&&(
					pressinguse()
					||nomags
				)
			){
				if(
					countinv("FourMilAmmo")
				)setweaponstate("loadchamber");
				else setweaponstate("nope");
			}else if(nomags)setweaponstate("nope");
		}goto unmag;
	unmag:
		#### A 1 offset(0,34) A_SetCrosshair(21);
		#### A 1 offset(5,38);
		#### A 1 offset(10,42);
		#### B 2 offset(20,46) A_StartSound("weapons/smgmagclick",8);
		#### B 4 offset(30,52){
			A_MuzzleClimb(0.3,0.4,wepdot:false);
			A_StartSound("weapons/smgmagmove",8,CHANF_OVERLAP);
		}
		#### B 0{
			int magamt=invoker.weaponstatus[TRCProp_MAG];
			if(magamt<0){
				setweaponstate("magout");
				return;
			}
			invoker.weaponstatus[TRCProp_MAG]=-1;
			if(
				(!PressingUnload()&&!PressingReload())
				||A_JumpIfInventory("HD4mMag25",0,"null")
			){
				HDMagAmmo.SpawnMag(self,"HD4mMag25",magamt);
				setweaponstate("magout");
			}else{
				HDMagAmmo.GiveMag(self,"HD4mMag25",magamt);
				A_StartSound("weapons/pocket",9);
				setweaponstate("pocketmag");
			}
		}
	pocketmag:
		#### BB 7 offset(34,54) A_MuzzleClimb(frandom(0.2,-0.8),frandom(-0.2,0.4),wepdot:false);
	magout:
		#### B 0{
			if(invoker.weaponstatus[0]&TRCProp_JUSTUNLOAD)setweaponstate("reloadend");
			else setweaponstate("loadmag");
		}

	loadmag:
		#### B 0 A_StartSound("weapons/pocket",9);
		#### B 6 offset(34,54) A_MuzzleClimb(frandom(0.2,-0.8),frandom(-0.2,0.4),wepdot:false);
		#### B 7 offset(34,52) A_MuzzleClimb(frandom(0.2,-0.8),frandom(-0.2,0.4),wepdot:false);
		#### B 10 offset(32,50);
		#### B 3 offset(32,49){
			let mmm=hdmagammo(findinventory("HD4mMag25"));
			if(mmm){
				invoker.weaponstatus[TRCProp_MAG]=mmm.TakeMag(true);
				A_StartSound("weapons/smgmagclick",8,CHANF_OVERLAP);
			}
			if(
				invoker.weaponstatus[TRCProp_MAG]<1
				||invoker.weaponstatus[TRCProp_CHAMBER]>0
			)setweaponstate("reloadend");
		}
		goto reloadend;

	reloadend:
		#### B 3 offset(30,52);
		#### B 2 offset(20,46);
		#### A 1 offset(10,42);
		#### A 1 offset(5,38);
		#### A 1 offset(0,34);
		goto chamber_manual;

	chamber_manual:
		#### A 0 A_JumpIf(
			invoker.weaponstatus[TRCProp_MAG]<1
			||invoker.weaponstatus[TRCProp_CHAMBER]==2
		,"nope");
		#### B 2 offset(3,32){
			A_WeaponBusy();
			invoker.weaponstatus[TRCProp_MAG]--;
			invoker.weaponstatus[TRCProp_CHAMBER]=2;
		}
		#### B 3 offset(5,35) A_StartSound("weapons/smgchamber",8,CHANF_OVERLAP);
		#### A 1 offset(3,32);
		#### A 1 offset(2,31);
		goto nope;


	spawn:
		TNT1 A 1;
		SMGN A 1;
		stop;
	}
	override void initializewepstats(bool idfa){
		weaponstatus[TRCProp_MAG]=25;
		weaponstatus[TRCProp_CHAMBER]=2;
	}
}
enum smgstatus{
	TRCProp_JUSTUNLOAD=1,
	TRCProp_REFLEXSIGHT=2,

	TRCProp_FLAGS=0,
	TRCProp_MAG=1,
	TRCProp_CHAMBER=2, //0 empty, 1 spent, 2 loaded
	TRCProp_DOT=3,
};