// ------------------------------------------------------------
// SMG
// ------------------------------------------------------------
class HDTrocaz:HDWeapon{
	default{
		+hdweapon.fitsinbackpack
		obituary "$OB_SMG";
		weapon.selectionorder 69;
		weapon.slotnumber 4;
		weapon.slotpriority 1;
		weapon.kickback 30;
		weapon.bobrangex 0.2;
		weapon.bobrangey 0.6;
		weapon.bobspeed 1.5;
		scale 0.55;
		inventory.pickupmessage "$PICKUP_TROCAZ";
		hdweapon.barrelsize 36,1,1;
		hdweapon.refid HDLD_TROCAZ;
		tag "$TAG_TROCAZ";
		inventory.icon "SMGNA0";

		hdweapon.ammo1 "HD4mMag25",1;
	}
	int handrounds;
	override bool AddSpareWeapon(actor newowner){return AddSpareWeaponRegular(newowner);}
	override hdweapon GetSpareWeapon(actor newowner,bool reverse,bool doselect){return GetSpareWeaponRegular(newowner,reverse,doselect);}
	override double gunmass(){
		return 11+((weaponstatus[TRCProp_MAG]<0)?-0.5:(weaponstatus[TRCProp_MAG]*0.05));
	}
	override double weaponbulk(){
		int mg=weaponstatus[TRCProp_MAG];
		if(mg<0)return 66;
		else return (66+(ENC_426MAG_LOADED*0.82+mg*ENC_426_LOADED*0.93));
	}
	override void failedpickupunload(){
		failedpickupunloadmag(TRCProp_MAG,"HD4mMag25");
	}
	override void DropOneAmmo(int amt){
		if(owner){
			amt=clamp(amt,1,10);
			if(owner.countinv("FourMilAmmo"))owner.A_DropInventory("FourMilAmmo",amt*25);
			else owner.A_DropInventory("HD4mMag25",amt);
		}
	}
	override void ForceBasicAmmo(){
		owner.A_TakeInventory("FourMilAmmo");
		ForceOneBasicAmmo("HD4mMag25");
	}
	override string,double getpickupsprite(bool usespare){
        string spr;
        int wep0=GetSpareWeaponValue(0,usespare);
        spr="RIGL";
        //set to no-mag frame
        if(GetSpareWeaponValue(TRCProp_MAG,usespare)<0)spr=spr.."D";
        else spr=spr.."A";

        return spr.."0",1.;
    }
	override void DrawHUDStuff(HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl){
		if(sb.hudlevel==1){
			int nextmagloaded=sb.GetNextLoadMag(hdmagammo(hpl.findinventory("HD4mMag25")));
			if(nextmagloaded>=25){
				sb.drawimage("CLP3A0",(-46,-3),sb.DI_SCREEN_CENTER_BOTTOM,scale:(3,3));
			}else if(nextmagloaded<1){
				sb.drawimage("CLP3B0",(-46,-3),sb.DI_SCREEN_CENTER_BOTTOM,alpha:nextmagloaded?0.6:1.,scale:(3,3));
			}else sb.drawbar(
				"CLP3NORM","CLP3GREY",
				nextmagloaded,30,
				(-46,-3),-1,
				sb.SHADER_VERT,sb.DI_SCREEN_CENTER_BOTTOM
			);
			sb.drawnum(hpl.countinv("HD4mMag25"),-43,-8,sb.DI_SCREEN_CENTER_BOTTOM);
		}
		sb.drawwepnum(hdw.weaponstatus[TRCProp_MAG],25);
		if(hdw.weaponstatus[TRCProp_CHAMBER]==1)sb.drawrect(-19,-11,3,1);
	}
	override string gethelptext(){
		LocalizeHelp();
		return
		LWPHELP_FIRESHOOT
		..LWPHELP_RELOAD..StringTable.Localize("$SMGWH_FIRE")
		..LWPHELP_USE.."+"..LWPHELP_RELOAD..StringTable.Localize("$SMGWH_UPRELOAD")
		..LWPHELP_FIREMODE..StringTable.Localize("$SMGWH_FMODE")
		..LWPHELP_MAGMANAGER
		..LWPHELP_UNLOADUNLOAD;
	}
	override void DrawSightPicture(
		HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl,
		bool sightbob,vector2 bob,double fov,bool scopeview,actor hpc
	){
		vector2 bobb=bob*1.18;
		if(weaponstatus[0]&TRCProp_REFLEXSIGHT){
			double dotoff=max(abs(bob.x),abs(bob.y));
			if(dotoff<30){
				string whichdot=sb.ChooseReflexReticle(hdw.weaponstatus[TRCProp_DOT]);
				sb.drawimage(
					whichdot,(0,0)+bobb,sb.DI_SCREEN_CENTER|sb.DI_ITEM_CENTER,
					alpha:0.8-dotoff*0.01,scale:(1.6,1.6),
					col:0xFF000000|sb.crosshaircolor.GetInt()
				);
			}
			sb.drawimage(
				"smgrearsight",(0,0)+bob,sb.DI_SCREEN_CENTER|sb.DI_ITEM_CENTER
			);
		}else{
			int cx,cy,cw,ch;
			[cx,cy,cw,ch]=screen.GetClipRect();
			sb.SetClipRect(
				-16+bob.x,-4+bob.y,32,16,
				sb.DI_SCREEN_CENTER
			);
			sb.drawimage(
				"smgfrntsit",(0,0)+bobb,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP
			);
			sb.SetClipRect(cx,cy,cw,ch);
			sb.drawimage(
				"smgbaksit",(0,0)+bob,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP,
				alpha:0.9
			);
		}
	}
	override void SetReflexReticle(int which){weaponstatus[TRCProp_DOT]=which;}
	action void A_CheckReflexSight(){
		if(
			invoker.weaponstatus[0]&TRCProp_REFLEXSIGHT
		)Player.GetPSprite(PSP_WEAPON).sprite=getspriteindex("SMSGA0");
		else Player.GetPSprite(PSP_WEAPON).sprite=getspriteindex("SMGGA0");
	}
	states{
	select0:
		SMGG A 0 A_CheckDefaultReflexReticle(TRCProp_DOT);
		SMGG A 0 A_CheckReflexSight();
		goto select0small;
	deselect0:
		SMGG A 0 A_CheckReflexSight();
		goto deselect0small;
		SMGG AB 0;
		SMSG AB 0;

	ready:
		SMGG A 0 A_CheckReflexSight();
		#### A 1{
			A_SetCrosshair(21);
			A_WeaponReady(WRF_ALL);
		}
		goto readyend;
	user3:
		---- A 0 A_MagManager("HD4mMag25");
		goto ready;
	altfire:
		#### A 1 Offset(0, 34) A_WeaponBusy();
		#### B 2 Offset(1, 35);
		#### B 2 Offset (2, 36);
		#### B 1 Offset(3, 37) A_MuzzleClimb(-frandom(0.06,0.1),-frandom(0.3,0.5));
		#### B 1 Offset(4, 38);
		#### A 0 A_Refire("chamber");
		goto ready;

	AltHold:
		SMGG B 1 A_WeaponReady(WRF_NOFIRE);
		#### B 1{
			A_ClearRefire();
			bool ChamberEmpty = invoker.WeaponStatus[TRCProp_Chamber]<1;
			if (PressingUnload())
			{
				invoker.WeaponStatus[TRCProp_LoadType] = 0;
				return resolvestate("loadchamber");
			}
			else if(PressingReload())
			{
				if (CheckInventory("FourMilAmmo", 1))
				{
					invoker.WeaponStatus[TRCProp_LoadType] = 1;
					return resolvestate("loadchamber");
				}
			}
			if (PressingAltFire())
			{
				return ResolveState("AltHold");
			}
			return resolvestate("altholdend");
		}

	Chamber:
		#### B 3 Offset(6, 42)
		{
			A_StartSound("Weapons/TarongaBoltBack", 8);
			if (GunBraced())
			{
				A_MuzzleClimb(frandom(-0.1, 0.3), frandom(-0.1, 0.3));
			}
			else
			{
				A_MuzzleClimb(frandom(-0.2, 0.8), frandom(-0.4, 0.8));
			}
		}
		#### B 2 Offset(6, 42)
		{
            if(invoker.WeaponStatus[TRCProp_Chamber] == 1)
            {
                A_EjectCasing("FourMilAmmo",frandom(-1,2),(frandom(0.2,0.3),-frandom(7,7.5),frandom(0,0.2)),(0,0,-2));
                invoker.WeaponStatus[TRCProp_Chamber] = 0;
            }
            else
            {
                SetWeaponState("AltHold");
            }
		}
		#### B 2 Offset(7, 44);
		#### B 1 Offset(5, 42);
		#### B 1 Offset(1, 34);
		#### B 1 A_WeaponReady(WRF_NOFIRE);
		#### B 0 A_Refire("AltHold");
		Goto AltHoldEnd;

	LoadChamber:
		#### # 1 Offset(2, 36) A_ClearRefire();
		#### # 1 Offset(3, 38);
		#### # 1 Offset(5, 42);
		#### # 1 Offset(8, 48) A_StartSound("weapons/pocket", 9);
		#### # 1 Offset(9, 52) A_MuzzleClimb(frandom(-0.2, 0.2), 0.2, frandom(-0.2, 0.2),0.2, frandom(-0.2, 0.2), 0.2);
		#### # 1 Offset(8, 60);
		#### # 1 Offset(7, 72);
		#### # 1 Offset(6, 80);
		#### # 1 Offset(6, 88);
		TNT1 # 25;
		TNT1 # 4
		{
			A_StartSound("weapons/TarongaLoad", 8, volume: 0.7);
			switch (invoker.WeaponStatus[TRCProp_LoadType])
			{
				case 0:
					int Chamber = invoker.WeaponStatus[TRCProp_Chamber];
					invoker.WeaponStatus[TRCProp_Chamber] = 0;
					if (Chamber == 1 || A_JumpIfInventory("FourMilAmmo", 0, "null"))
					{
						Class<actor> EjectClass = Chamber == 2 ? "FourMilAmmo" : "null";
						actor rrr = Spawn(EjectClass, pos + (cos(angle) * 10, sin(angle) * 10,  height - 12), ALLOW_REPLACE);
						rrr.angle = angle;
						rrr.A_ChangeVelocity(1, 2, 1, CVF_RELATIVE);
					}
					else
					{
						HDF.Give(self, "FourMilAmmo", 1);
					}
					break;
				case 1:
					if (invoker.WeaponStatus[TRCProp_Chamber] == 0)
					{
						A_TakeInventory("FourMilAmmo", 1, TIF_NOTAKEINFINITE);
						invoker.WeaponStatus[TRCProp_Chamber] = 1;
					}
					else if (invoker.WeaponStatus[TRCProp_Chamber] == 1 && invoker.WeaponStatus[TRCProp_Mag] >= 0 && invoker.WeaponStatus[TRCProp_Mag] != 25)
					{
						SetWeaponState("loadchamberloop");
					}
					break;
			}
		} 
		SMGG # 2 Offset(6, 80);
		#### # 2 Offset(7, 72);
		#### # 2 Offset(8, 60);
		#### # 1 Offset(7, 52);
		#### # 1 Offset(5, 42);
		#### # 1 Offset(3, 38);
		#### # 1 Offset(3, 35);
		Goto AltHold;
	
	AltHoldEnd:
		#### B 0 A_StartSound("weapons/TarongaBoltFwd", 8);
		#### B 0 {
            if(invoker.WeaponStatus[TRCProp_Chamber] == 0)
            {
				if(invoker.weaponstatus[TRCProp_MAG]>0){
					invoker.weaponstatus[TRCProp_MAG]--;
					invoker.weaponstatus[TRCProp_CHAMBER]=1;
				}
            }
		}
        #### B 2 A_WeaponReady(WRF_NOFIRE);
        #### A 1 A_WeaponReady(WRF_NOFIRE);
		Goto Ready;

	loadchamberloop:
		SMGG # 4{
			int hnd=min(
				countinv("FourMilAmmo"),5,
				25-invoker.weaponstatus[TRCProp_Mag]
			);
			if(hnd<1 && !PressingAltFire()){
				setweaponstate("AltHoldEnd");
				return;
			}
			else if(hnd<1 && PressingAltFire()){
				setweaponstate("AltHold");
				return;
			}else{
				A_TakeInventory("FourMilAmmo",hnd,TIF_NOTAKEINFINITE);
				invoker.handrounds=hnd;
				A_StartSound("weapons/pocket",9);
			}
		}
	
	loadone:
		SMGG A 1 offset(16,50) A_JumpIf(invoker.handrounds<1 && PressingAltFire(),"AltHold");
		SMGG A 1 offset(16,50) A_JumpIf(invoker.handrounds<1 && !PressingAltFire(),"AltHoldEnd");
		SMGG A 4 offset(14,46){
			invoker.handrounds--;
			invoker.weaponstatus[TRCProp_Mag]++;
			A_StartSound("weapons/rifleclick2",8);
		}loop;

    hold:
		goto nope;
	fire:
		#### A 0;
	fire2:
		#### B 1{
			if(invoker.weaponstatus[TRCProp_CHAMBER]==1)A_GunFlash();
			else setweaponstate("nope");
		}
		#### A 1;
		#### A 0{
			if(invoker.weaponstatus[TRCProp_MAG]>0){
				invoker.weaponstatus[TRCProp_MAG]--;
				invoker.weaponstatus[TRCProp_CHAMBER]=1;
			}

			//don't allow firing if supposed to be lowered
			A_WeaponReady(WRF_NOFIRE);
		}
		// Mwahahahahahahahaha! - [Ted]
		#### A 2 A_ReFire();
		goto ready;
	flash:
		#### B 0{
			let bbb=HDBulletActor.FireBullet(self,"HDB_426",speedfactor: 1.1);
			if(
				frandom(16,ceilingz-floorz)<bbb.speed*0.1
			)A_AlertMonsters(200);

			A_ZoomRecoil(0.995);
			A_StartSound("weapons/rifle",CHAN_WEAPON,volume:0.7);
			invoker.weaponstatus[TRCProp_CHAMBER]=0;
		}
		SMGF A 1 bright{
			HDFlashAlpha(-200);
			A_Light1();
		}
		TNT1 A 0 A_MuzzleClimb(-frandom(0.2,0.24),-frandom(0.3,0.36),-frandom(0.2,0.24),-frandom(0.3,0.36));
		goto lightdone;

	user4:
	unload:
		#### A 0{
			invoker.weaponstatus[0]|=TRCProp_JUSTUNLOAD;
			if(
				invoker.weaponstatus[TRCProp_MAG]>=0
			)setweaponstate("unmag");
		}goto nope;
	reload:
		#### A 0{
			invoker.weaponstatus[0]&=~TRCProp_JUSTUNLOAD;
			bool nomags=HDMagAmmo.NothingLoaded(self,"HD4mMag25");
			if(invoker.weaponstatus[TRCProp_MAG]>=25)setweaponstate("nope");
			else if(
				invoker.weaponstatus[TRCProp_MAG]<1
				&&(
					pressinguse()
					||nomags
				)
			){
				setweaponstate("nope");
			}else if(nomags)setweaponstate("nope");
		}goto unmag;
	unmag:
		#### A 1 offset(0,34) A_SetCrosshair(21);
		#### A 2 offset(5,38);
		#### A 1 offset(10,42);
		#### B 3 offset(20,46) A_StartSound("weapons/smgmagclick",8);
		#### B 5 offset(30,52){
			A_MuzzleClimb(0.3,0.4,wepdot:false);
			A_StartSound("weapons/smgmagmove",8,CHANF_OVERLAP);
		}
		#### B 0{
			int magamt=invoker.weaponstatus[TRCProp_MAG];
			if(magamt<0){
				setweaponstate("magout");
				return;
			}
			invoker.weaponstatus[TRCProp_MAG]=-1;
			if(
				(!PressingUnload()&&!PressingReload())
				||A_JumpIfInventory("HD4mMag25",0,"null")
			){
				HDMagAmmo.SpawnMag(self,"HD4mMag25",magamt);
				setweaponstate("magout");
			}else{
				HDMagAmmo.GiveMag(self,"HD4mMag25",magamt);
				A_StartSound("weapons/pocket",9);
				setweaponstate("pocketmag");
			}
		}
	pocketmag:
		#### BB 7 offset(34,54) A_MuzzleClimb(frandom(0.2,-0.8),frandom(-0.2,0.4),wepdot:false);
	magout:
		#### B 0{
			if(invoker.weaponstatus[0]&TRCProp_JUSTUNLOAD)setweaponstate("reloadend");
			else setweaponstate("loadmag");
		}

	loadmag:
		#### B 0 A_StartSound("weapons/pocket",9);
		#### B 6 offset(34,54) A_MuzzleClimb(frandom(0.2,-0.8),frandom(-0.2,0.4),wepdot:false);
		#### B 9 offset(34,52) A_MuzzleClimb(frandom(0.2,-0.8),frandom(-0.2,0.4),wepdot:false);
		#### B 12 offset(32,50);
		#### B 4 offset(32,49){
			let mmm=hdmagammo(findinventory("HD4mMag25"));
			if(mmm){
				invoker.weaponstatus[TRCProp_MAG]=mmm.TakeMag(true);
				A_StartSound("weapons/smgmagclick",8,CHANF_OVERLAP);
			}
			if(
				invoker.weaponstatus[TRCProp_MAG]<1
				||invoker.weaponstatus[TRCProp_CHAMBER]>0
			)setweaponstate("reloadend");
		}
		goto reloadend;

	reloadend:
		#### B 5 offset(30,52);
		#### B 4 offset(20,46);
		#### A 3 offset(10,42);
		#### A 2 offset(5,38);
		#### A 1 offset(0,34);
		goto nope;

	spawn:
		TNT1 A 1;
		SMGN A 1;
		stop;
	}
	override void initializewepstats(bool idfa){
		weaponstatus[TRCProp_MAG]=25;
		weaponstatus[TRCProp_CHAMBER]=1;
	}
}
enum smgstatus{
	TRCProp_JUSTUNLOAD=1,
	TRCProp_REFLEXSIGHT=2,
	TRCProp_LoadType=3,

	TRCProp_FLAGS=0,
	TRCProp_MAG=1,
	TRCProp_CHAMBER=2, //0 empty, 1 loaded
	TRCProp_DOT=3,
};