class HDB_NDMw:HDB_NDM{
	default{
		pushfactor 0.4;
		mass 30;
		speed 1740;
		accuracy 450;
		stamina 762;
		woundhealth 10;
		hdbulletactor.hardness 5;
	}
}

class HD_Wigeon:HDWeapon{
    default{
        //$Category "Weapons/Hideous Destructor"
        //$Title "ZM66 Rifle (All)"
        //$Sprite "RIGLA0"

        +hdweapon.fitsinbackpack
        weapon.selectionorder 69;
        weapon.slotnumber 4;
        weapon.slotpriority 69;
        inventory.pickupsound "misc/w_pkup";
        inventory.pickupmessage "$PICKUP_WIGEON";
        scale 0.7;
        hdweapon.barrelsize 34,1,1.4;
        weapon.bobrangex 0.1;
        weapon.bobrangey 0.6;
        weapon.bobspeed 2.5;
        weapon.kickback 30;
        obituary "$OB_WIGEON";
        hdweapon.refid "wgn";
        tag "$TAG_WIGEON";
        inventory.icon "RIGLA0";

        hdweapon.ammo1 "HDNDMMag30",1;
        hdweapon.ammo2 "MM_4mmSealant",1;

        hdweapon.loadoutcodes "\n\cu   firemode - 0/1, automatic/burst fire \n\cu   semi - 0/1, semi-auto lock";
    }
    private transient CVar AHelpText;
    override void tick(){
        super.tick();
        drainheat(WGProp_Heat,frandom(1,3));
    }
    override bool AddSpareWeapon(actor newowner){return AddSpareWeaponRegular(newowner);}
    override hdweapon GetSpareWeapon(actor newowner,bool reverse,bool doselect){return GetSpareWeaponRegular(newowner,reverse,doselect);}
    override double gunmass(){
        return 5.3+weaponstatus[WGProp_Mag]*0.01;
    }
    override void GunBounce(){
        super.GunBounce();
        if(!random(0,5))weaponstatus[0]&=~WGF_ChamberBroken;
    }
    override string pickupmessage(){
        if(weaponstatus[0]&WGF_NoFireSelect)return Stringtable.Localize("$PICKUP_SEMIWIGEON");
        return super.pickupmessage();
    }
    override string,double getpickupsprite(bool usespare){
        string spr;
        int wep0=GetSpareWeaponValue(0,usespare);
        if(wep0&WGF_NoFireSelect)
            spr="RIGS";
        else spr="RIGL";
        //set to no-mag frame
        if(GetSpareWeaponValue(WGProp_Mag,usespare)<0)spr=spr.."D";
        else spr=spr.."A";

        return spr.."0",1.;
    }
    override void DrawHUDStuff(HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl){
        if(sb.hudlevel==1){
            int nextmagloaded=sb.GetNextLoadMag(hdmagammo(hpl.findinventory("HDNDMMag30")));
            if(nextmagloaded>30){
                sb.drawimage("ZMAGA0",(-46,-3),sb.DI_SCREEN_CENTER_BOTTOM,scale:(2,2));
            }else if(nextmagloaded<1){
                sb.drawimage("ZMAGC0",(-46,-3),sb.DI_SCREEN_CENTER_BOTTOM,alpha:nextmagloaded?0.6:1.,scale:(2,2));
            }else sb.drawbar(
                "ZMAGNORM","ZMAGGREY",
                nextmagloaded,30,
                (-46,-3),-1,
                sb.SHADER_VERT,sb.DI_SCREEN_CENTER_BOTTOM
            );
            sb.drawnum(hpl.countinv("HDNDMMag30"),-43,-8,sb.DI_SCREEN_CENTER_BOTTOM);
        }

        if(!(hdw.weaponstatus[0]&WGF_NoFireSelect))
        sb.drawwepcounter(hdw.weaponstatus[WGProp_Auto],
            -22,-10,"STFULAUT","STBURAUT"
        );
        int lod=clamp(hdw.weaponstatus[WGProp_Mag]%100,0,30);
        sb.drawwepnum(lod,30);
        if(hdw.weaponstatus[0]&WGF_Chamber){
            sb.drawrect(-19,-10,3,1);
            lod++;
        }
        if(hdw.weaponstatus[WGProp_Mag]>50)lod=random[shitgun](10,99);
        sb.drawnum(lod,-16,-22,sb.DI_SCREEN_CENTER_BOTTOM|sb.DI_TEXT_ALIGN_RIGHT,Font.CR_RED);

		if(hd_debug){
			sb.drawnum(hdw.weaponstatus[WGProp_Mag],-16,-32,
				basestatusbar.DI_SCREEN_CENTER_BOTTOM);
			sb.drawnum(hdw.weaponstatus[WGProp_Heat],-24,-32,
				basestatusbar.DI_SCREEN_CENTER_BOTTOM);
			sb.drawnum(hdw.weaponstatus[WGProp_Auto],-34,-32,
				basestatusbar.DI_SCREEN_CENTER_BOTTOM);
			sb.drawnum(hdw.weaponstatus[WGF_ChamberBroken],-46,-32,
				basestatusbar.DI_SCREEN_CENTER_BOTTOM);
		}
    }
    override string gethelptext(){
        LocalizeHelp();
        if(!AHelpText) AHelpText = CVar.GetCVar('mm_advanced_helptext', owner.player);
        return
        LWPHELP_FIRESHOOT
        ..LWPHELP_ALTFIRE..Stringtable.Localize("$JNK_SMACK")
        ..LWPHELP_RELOAD..StringTable.Localize("$ZMWH_RELOAD")
        ..LWPHELP_MAGMANAGER
        ..LWPHELP_UNLOADUNLOAD
        ..(AHelpText.GetBool() ? Stringtable.Localize("$WEPHELP_INFO") : "")
        ..(AHelpText.GetBool() ? Stringtable.Localize("$JNKWH_RTYPE") : "")
        ..(AHelpText.GetBool() ? Stringtable.Localize("$JNKWH_DTYPE") : "")
        ..(AHelpText.GetBool() ? Stringtable.Localize("$JNKWH_WTYPE") : "");
    }
    override void DrawSightPicture(
		HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl,
		bool sightbob,vector2 bob,double fov,bool scopeview,actor hpc
	){
		int cx,cy,cw,ch;
		[cx,cy,cw,ch]=screen.GetClipRect();
		vector2 scc;
		vector2 bobb=bob*1.3;

		//if slide is pushed back, throw sights off line
		if(hpl.player.getpsprite(PSP_WEAPON).frame>=2){
			sb.SetClipRect(
				-10+bob.x,-10+bob.y,20,19,
				sb.DI_SCREEN_CENTER
			);
			bobb.y-=2;
			scc=(0.7,0.8);
		}else{
			sb.SetClipRect(
				-8+bob.x,-9+bob.y,16,15,
				sb.DI_SCREEN_CENTER
			);
			scc=(0.6,0.6);
		}
		sb.drawimage(
			"frntsite",(0,0)+bobb,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP,
			scale:scc
		);
		sb.SetClipRect(cx,cy,cw,ch);
		sb.drawimage(
			"backsite",(0,0)+bob,sb.DI_SCREEN_CENTER|sb.DI_ITEM_TOP,
			alpha:0.9,
			scale:scc
		);
	}
    override double weaponbulk(){
        double blx=52;
        int mgg=weaponstatus[WGProp_Mag];
        return blx+(mgg<0?0:(ENC_426MAG_LOADED*0.82+mgg*ENC_426_LOADED*0.93));
    }
    override void failedpickupunload(){
        failedpickupunloadmag(WGProp_Mag,"HDNDMMag30");
    }
    override void DropOneAmmo(int amt){
        if(owner){
            amt=clamp(amt,1,10);
            if(owner.countinv("HDNDMLoose"))owner.A_DropInventory("HDNDMLoose",amt*30);
            else{
                double angchange=-10;
                if(angchange)owner.angle-=angchange;
                owner.A_DropInventory("HDNDMMag30",amt);
            }
        }
    }
    override void ForceBasicAmmo(){
        owner.A_TakeInventory("HDNDMLoose");
        ForceOneBasicAmmo("HDNDMMag30");
    }
    action bool brokenround(){
        if(!(invoker.weaponstatus[WGProp_Flags]&WGF_ChamberBroken)){
            int hht=invoker.weaponstatus[WGProp_Heat];
            if(hht>125)invoker.weaponstatus[WGProp_Broken]++;
            hht*=hht;hht>>=10;
            int rnd=
                (invoker.owner?1:10)
                +max(invoker.weaponstatus[WGProp_Auto],hht)
                +invoker.weaponstatus[WGProp_Broken]
                +(invoker.weaponstatus[WGProp_Mag]>100?10:0);
            if(random(0,250)<rnd){
                invoker.weaponstatus[WGProp_Flags]|=WGF_ChamberBroken;
            }
        }return invoker.weaponstatus[WGProp_Flags]&WGF_ChamberBroken;
    }
    states{
    ready:
        JNCO A 1{
            A_WeaponReady(WRF_ALL);
            if(invoker.weaponstatus[WGProp_Auto]>=2)invoker.weaponstatus[WGProp_Auto]=1;
        }goto readyend;
    firemode:
		JNCO A 1{
            A_StartSound("weapons/juncosafety");
            switch(invoker.WeaponStatus[WGProp_Auto])
            {
                case 0: invoker.WeaponStatus[WGProp_Auto]=1; return;
                case 1: invoker.WeaponStatus[WGProp_Auto]=0; return;
                default: invoker.WeaponStatus[WGProp_Auto]=0; return;
            }
			A_WeaponReady(WRF_NOFIRE);
		}goto nope;


    select0:
        JNCO A 0;
        goto select0big;
    deselect0:
        JNCO A 0;
        goto deselect0big;
    explode:
        TNT1 A 0
        {
            A_SpawnItemEx("HD_WigeonExplosion",0,0,0,
			0,0,2,
			0,SXF_NOCHECKPOSITION|SXF_TRANSFERPOINTERS
		    );
            A_TakeInventory("HD_Wigeon");
        }stop;
    flash:
        JNCO F 1 bright{
            int heat = min(50, invoker.weaponStatus[WGProp_Heat]);
            A_Light1();
            HDFlashAlpha(-16);
            A_StartSound("weapons/smg",CHAN_WEAPON);
            A_ZoomRecoil(max(0.95,1.-0.05*min(invoker.weaponstatus[WGProp_Auto],3)));

            //shoot the bullet
            //copypaste any changes to spawnshoot as well!
            double brnd=max(invoker.weaponstatus[WGProp_Heat],invoker.weaponstatus[WGProp_Broken])*0.01;
            HDBulletActor.FireBullet(self,"HDB_NDMw",spread:brnd>1.2?brnd:0,speedfactor: 1.1);

            A_MuzzleClimb(-frandom(1.45,2.3),-frandom(1.49,2.7));
            A_AlertMonsters(HDCONST_ONEMETRE * (9 + heat));

            invoker.weaponstatus[WGProp_Flags]&=~WGF_Chamber;
            invoker.weaponstatus[WGProp_Heat]+=random(5,7);
            if((invoker.weaponstatus[WGProp_Mag]>100) && random(0,4)==1) setweaponstate("explode");
        }
        goto lightdone;


    fire:
        JNCO A 3 {if(invoker.weaponstatus[0]&WGF_NoFireSelect)A_SetTics(1);}
        goto shootgun;
    hold:
        JNCO A 0 A_JumpIf(invoker.weaponstatus[0]&WGF_NoFireSelect,"nope");
        JNCO A 0 A_JumpIf(invoker.weaponstatus[WGProp_Auto]>3,"nope");
        goto shootgun;
    althold:
        ---- A 1{
            A_WeaponReady(WRF_NOFIRE);
        }
        ---- A 0 A_Refire();
        goto ready;
    jam:
        JNCO B 1 offset(-1,36){
            A_StartSound("weapons/juncojam",CHAN_WEAPON,CHANF_OVERLAP);
            invoker.weaponstatus[0]|=WGF_ChamberBroken;
            invoker.weaponstatus[WGProp_Flags]&=~WGF_Chamber;
        }
        JNCO B 1 offset(1,30) A_StartSound("weapons/juncojam",CHAN_WEAPON,CHANF_OVERLAP);
        goto nope;

    shootgun:
        JNCO A 1{
            if(
                //can neither shoot nor chamber
                invoker.weaponstatus[0]&WGF_ChamberBroken
                ||(
                    !(invoker.weaponstatus[WGProp_Flags]&WGF_Chamber)
                    &&invoker.weaponstatus[WGProp_Mag]<1
                )
            ){
                setweaponstate("nope");
            }else if(!(invoker.weaponstatus[WGProp_Flags]&WGF_Chamber)){
                //no shot but can chamber
                setweaponstate("chamber_manual");
            }else{
                A_GunFlash();
                A_WeaponReady(WRF_NOFIRE);
                if(invoker.weaponstatus[WGProp_Auto]>=1)invoker.weaponstatus[WGProp_Auto]++;
            }
        }
    chamber:
        JNCO B 0 offset(0,32){
            if(invoker.weaponstatus[WGProp_Mag]<1){
                setweaponstate("nope");
                return;
            }
            if(invoker.weaponstatus[WGProp_Mag]%100>0){
                if(invoker.weaponstatus[WGProp_Mag]==31)invoker.weaponstatus[WGProp_Mag]=30;
                invoker.weaponstatus[WGProp_Mag]--;
                invoker.weaponstatus[WGProp_Flags]|=WGF_Chamber;
            }else{
                invoker.weaponstatus[WGProp_Mag]=min(invoker.weaponstatus[WGProp_Mag],0);
                A_StartSound("weapons/juncobfwd",CHAN_WEAPON,CHANF_OVERLAP);
            }
            if(brokenround()){
                setweaponstate("jam");
                return;
            }
            A_WeaponReady(WRF_NONE);
        }
        JNCO B 0 A_JumpIf(invoker.weaponstatus[WGProp_Auto]>3,"nope");
        JNCO B 1 
        {
            if(invoker.weaponstatus[WGProp_Auto]>=1)
            {
                A_SetTics(4);
            }
        }
        JNCO B 0 A_Refire();
        goto ready;

    user3:
        JNCO A 0 A_MagManager("HDNDMMag30");
        goto ready;

    user4:
    unload:
        JNCO A 0{
            invoker.weaponstatus[WGProp_Flags]|=WGF_UnloadOnly;
            if(
                invoker.weaponstatus[WGProp_Mag]>=0
            ){
                setweaponstate("unloadmag");
            }else if(
                invoker.weaponstatus[WGProp_Flags]&WGF_Chamber
                ||invoker.weaponstatus[WGProp_Flags]&WGF_ChamberBroken
            ){
                setweaponstate("unloadchamber");
            }else{
                setweaponstate("unloadmag");
            }
        }
    reload:
        JNCO A 0{
            invoker.weaponstatus[WGProp_Flags]&=~WGF_UnloadOnly;
            if(	//full mag, no jam, not unload-only - why hit reload at all?
                !(invoker.weaponstatus[0]&WGF_ChamberBroken)
                &&invoker.weaponstatus[WGProp_Mag]%100>=30
                &&!(invoker.weaponstatus[WGProp_Flags]&WGF_UnloadOnly)
            ){
                setweaponstate("nope");
            }else if(	//if jammed, treat as unloading
                invoker.weaponstatus[WGProp_Mag]<0
                &&invoker.weaponstatus[0]&WGF_ChamberBroken
            ){
                invoker.weaponstatus[WGProp_Flags]|=WGF_UnloadOnly;
                setweaponstate("unloadchamber");
            }else if(!HDMagAmmo.NothingLoaded(self,"HDNDMMag30")){
                setweaponstate("unloadmag");
            }
        }goto nope;
    unloadmag:
        JNCO A 1 offset(0,33);
        JNCO A 1 offset(-3,34);
        JNCO A 1 offset(-8,37);
        JNCO B 2 offset(-11,39){
            if(	//no mag, skip unload
                invoker.weaponstatus[WGProp_Mag]<0
            ){
                setweaponstate("magout");
            }
            if(invoker.weaponstatus[0]&WGF_ChamberBroken)
                invoker.weaponstatus[WGProp_Flags]|=WGF_UnloadOnly;
            A_MuzzleClimb(-0.3,-0.3,wepdot:false);
            A_StartSound("weapons/juncobfwd2",CHAN_WEAPON,CHANF_OVERLAP);
        }
        JNCO B 4 offset(-12,40){
            A_MuzzleClimb(-0.3,-0.3,wepdot:false);
            invoker.drainheat(WGProp_Heat,15);
            A_StartSound("weapons/juncounload",CHAN_WEAPON);
        }
        JNCO B 20 offset(-14,44){
            int inmag=invoker.weaponstatus[WGProp_Mag];
            if(inmag>31)inmag=min(30,inmag%100);
            invoker.weaponstatus[WGProp_Mag]=-1;
            if(
                !PressingUnload()&&!PressingReload()
                ||A_JumpIfInventory("HDNDMMag30",0,"null")
            ){
                HDMagAmmo.SpawnMag(self,"HDNDMMag30",inmag);
                A_SetTics(1);
            }else{
                HDMagAmmo.GiveMag(self,"HDNDMMag30",inmag);
                A_StartSound("weapons/pocket",CHAN_WEAPON);
                if(inmag<31)A_Log(StringTable.Localize("$WGNMAGMSG"),true);
            }
        }
    magout:
        JNCO B 0{
            if(
                invoker.weaponstatus[WGProp_Flags]&WGF_UnloadOnly
                ||!countinv("HDNDMMag30")
            )setweaponstate("reloadend");
        } //fallthrough to loadmag
    loadmag:
        ---- A 12 offset(-15,44){
            let zmag=HDNDMMag30(findinventory("HDNDMMag30"));
            if(!zmag){setweaponstate("reloadend");return;}
            A_StartSound("weapons/pocket",CHAN_WEAPON);
            if(zmag.DirtyMagsOnly())invoker.weaponstatus[0]|=WGF_LoadingDirty;
            else{
                invoker.weaponstatus[0]&=~WGF_LoadingDirty;
                A_SetTics(10);
            }
        }
        ---- A 2 offset(-15,44) A_JumpIf(invoker.weaponstatus[0]&WGF_LoadingDirty,"loadmagdirty");
    loadmagclean:
        JNCO B 8 offset(-15,45)A_StartSound("weapons/juncoload",CHAN_WEAPON);
        JNCO B 1 offset(-14,44){
            let zmag=HDNDMMag30(findinventory("HDNDMMag30"));
            if(!zmag){setweaponstate("reloadend");return;}
            if(zmag.DirtyMagsOnly()){
                setweaponstate("loadmagdirty");
                return;
            }
            invoker.weaponstatus[WGProp_Mag]=zmag.TakeMag(true);
            A_StartSound("weapons/juncobfwd2",CHAN_WEAPON);
        }goto reloadend;
    loadmagdirty:
        JNCO B 0{
            if(PressingReload())invoker.weaponstatus[0]|=WGF_StillPressingReload;
            else invoker.weaponstatus[0]&=~WGF_StillPressingReload;
        }
        JNCO B 3 offset(-15,45)A_StartSound("weapons/juncoload",CHAN_WEAPON);
        JNCO B 1 offset(-15,42)A_WeaponMessage(StringTable.Localize("$WGNMAGMSG2"),70);
        JNCO BBBBBBBAAAA 1 offset(-15,41){
            bool prr=PressingReload();
            if(
                prr
                &&!(invoker.weaponstatus[0]&WGF_StillPressingReload)
            ){
                setweaponstate("reallyloadmagdirty");
            }
            else if(!PressingReload())invoker.weaponstatus[0]&=~WGF_StillPressingReload;
        }
        goto nope;
    reallyloadmagdirty:
        JNCO B 1 offset(-14,44)A_StartSound("weapons/juncobfwd2",CHAN_WEAPON);
        JNCO A 8 offset(-18,50){
            let zmag=HDNDMMag30(findinventory("HDNDMMag30"));
            if(!zmag){setweaponstate("reloadend");return;}
            invoker.weaponstatus[WGProp_Mag]=zmag.TakeMag(true)+100;
            A_MuzzleClimb(
                -frandom(0.4,0.6),frandom(2.,3.)
                -frandom(0.2,0.3),frandom(1.,1.6),
                wepdot:false
            );
            A_StartSound("weapons/juncobfwd2",CHAN_WEAPON,CHANF_OVERLAP);
            A_StartSound("weapons/smack",CHAN_WEAPON,CHANF_OVERLAP);

            string realmessage=StringTable.Localize("$WGNMAGMSG");
            realmessage=realmessage.left(random(13,20));
            realmessage.appendformat(StringTable.Localize("$WGNRELERROR")..random(0,9999)..StringTable.Localize("$WGNNOCARRIER"));
            A_WeaponMessage(realmessage,70);
        }
        JNCO A 4 offset(-17,49);
        goto chamber_manual;

    reloadend:
        JNCO B 2 offset(-11,39);
        JNCO A 1 offset(-8,37) A_MuzzleClimb(frandom(0.2,-2.4),frandom(0.2,-1.4),wepdot:false);
        JNCO A 1 offset(-3,34);
        goto chamber_manual;

    chamber_manual:
        JNCO A 0 A_JumpIf(invoker.weaponstatus[WGProp_Flags]&WGF_Chamber,"nope");
        JNCO A 3 offset(-1,36)A_WeaponBusy();
        JNCO B 4 offset(-3,42){
            if(!invoker.weaponstatus[WGProp_Mag]%100)invoker.weaponstatus[WGProp_Mag]=0;
            if(
                !(invoker.weaponstatus[WGProp_Flags]&WGF_Chamber)
                && !(invoker.weaponstatus[WGProp_Flags]&WGF_Chamber)
                && invoker.weaponstatus[WGProp_Mag]%100>0
            ){
                A_StartSound("weapons/juncobfwd",CHAN_WEAPON);
                if(invoker.weaponstatus[WGProp_Mag]==31)invoker.weaponstatus[WGProp_Mag]=29;
                else invoker.weaponstatus[WGProp_Mag]--;
                invoker.weaponstatus[WGProp_Flags]|=WGF_Chamber;
                brokenround();
            }else setweaponstate("nope");
        }
        JNCO A 2 offset(-1,36);
        JNCO A 0 offset(0,34);
        goto nope;


    
	altfire:
		#### A 1 Offset(0, 34) A_WeaponBusy();
		#### B 2 Offset(1, 35);
		#### B 2 Offset (2, 36);
		#### B 1 Offset(3, 37) A_MuzzleClimb(-frandom(0.06,0.1),-frandom(0.3,0.5));
		#### B 1 Offset(4, 38);
		#### A 0 A_Refire("chamber");
		goto ready;

	AltHold:
		TRCZ B 1 A_WeaponReady(WRF_NOFIRE);
		#### B 1{
			A_ClearRefire();
			bool ChamberEmpty = invoker.WeaponStatus[WGF_Chamber]<1;
			if (PressingAltFire())
			{
				return ResolveState("AltHold");
			}
			return resolvestate("altholdend");
		}

	Chamber:
		#### B 3 Offset(6, 42)
		{
			A_StartSound("Weapons/TrocazBoltBack", 8);
			if (GunBraced())
			{
				A_MuzzleClimb(frandom(-0.1, 0.3), frandom(-0.1, 0.3));
			}
			else
			{
				A_MuzzleClimb(frandom(-0.2, 0.8), frandom(-0.4, 0.8));
			}
		}
		#### B 2 Offset(6, 42)
		{
            if(invoker.WeaponStatus[WGF_Chamber] == 1)
            {
                A_EjectCasing("FourMilAmmo",frandom(-1,2),(frandom(0.2,0.3),-frandom(7,7.5),frandom(0,0.2)),(0,0,-2));
                invoker.WeaponStatus[WGF_Chamber] = 0;
            }
            else
            {
                SetWeaponState("AltHold");
            }
		}
		#### B 2 Offset(7, 44);
		#### B 1 Offset(5, 42);
		#### B 1 Offset(1, 34);
		#### B 1 A_WeaponReady(WRF_NOFIRE);
		#### B 0 A_Refire("AltHold");
		Goto AltHoldEnd;
	
	AltHoldEnd:
		#### B 0 A_StartSound("weapons/TrocazBoltFwd", 8);
		#### B 0 {
            if(invoker.WeaponStatus[WGF_Chamber] == 0)
            {
				if(invoker.weaponstatus[WGProp_Mag]>0){
					invoker.weaponstatus[WGProp_Mag]--;
					invoker.weaponstatus[WGF_Chamber]=1;
				}
            }
		}
        #### B 2 A_WeaponReady(WRF_NOFIRE);
        #### A 1 A_WeaponReady(WRF_NOFIRE);
		Goto Ready;

    unloadchamber:
        JNCO A 1 offset(-3,34);
        JNCO A 1 offset(-9,39);
        JNCO B 3 offset(-19,44) A_MuzzleClimb(frandom(-0.4,0.4),frandom(-0.4,0.4),wepdot:false);
        JNCO A 2 offset(-16,42){
            A_MuzzleClimb(frandom(-0.4,0.4),frandom(-0.4,0.4),wepdot:false);
            if(
                invoker.weaponstatus[WGProp_Flags]&WGF_Chamber
                &&!(invoker.weaponstatus[0]&WGF_ChamberBroken)
            ){
                A_SpawnItemEx("ZM66DroppedRound",0,0,20,
                    random(4,7),random(-2,2),random(-2,1),0,
                    SXF_NOCHECKPOSITION
                );
                invoker.weaponstatus[WGProp_Flags]&=~WGF_Chamber;
                A_StartSound("weapons/juncobfwd",CHAN_WEAPON,CHANF_OVERLAP);
            }else if(!random(0,4)){
                invoker.weaponstatus[0]&=~WGF_ChamberBroken;
                invoker.weaponstatus[WGProp_Flags]&=~WGF_Chamber;
                A_StartSound("weapons/juncobfwd2",CHAN_WEAPON,CHANF_OVERLAP);
                for(int i=0;i<5;i++)A_SpawnItemEx("FourMilChunk",0,0,20,
                    random(4,7),random(-2,2),random(-2,1),0,SXF_NOCHECKPOSITION
                );
                if(!random(0,5))A_SpawnItemEx("HDSmokeChunk",12,0,gunheight()-10,4,frandom(-2,2),frandom(2,4));
            }else if(invoker.weaponstatus[0]&WGF_ChamberBroken){
                A_StartSound("weapons/smack",CHAN_WEAPON,CHANF_OVERLAP);
            }
        }goto reloadend;

    spawn:
        RIFL DCBA 0;
        RIGL DCBA 0;
        RIFS DCBA 0;
        RIGS DA 0;
        ---- A 0{
            //don't jam just because
            if(
                !(invoker.weaponstatus[0]&WGF_Chamber)
                &&!(invoker.weaponstatus[0]&WGF_ChamberBroken)
                &&invoker.weaponstatus[WGProp_Mag]>0
                &&invoker.weaponstatus[WGProp_Mag]<31
            ){
                invoker.weaponstatus[WGProp_Mag]--;
                invoker.weaponstatus[0]|=WGF_Chamber;
                brokenround();
            }
        }
    spawn2:
        ---- A -1{
            //set sprite
            if(invoker.weaponstatus[0]&WGF_NoFireSelect)
                sprite=getspriteindex("RIGSA0");
            else sprite=getspriteindex("RIGLA0");

            //set to no-mag frame
            if(invoker.weaponstatus[WGProp_Mag]<0){
                frame=3;
            }
        }
    }

    override inventory CreateTossable(int amt){
        let owner=self.owner;
        let zzz=HD_Wigeon(super.createtossable());
        if(!zzz)return null;
        zzz.target=owner;
        return zzz;
    }

    override void InitializeWepStats(bool idfa){
        weaponstatus[WGProp_Mag]=31;
        if(!idfa && !owner){
            weaponstatus[WGProp_Auto]=0;
            weaponstatus[WGProp_Heat]=0;
        }
        if(idfa)weaponstatus[0]&=~WGF_ChamberBroken;
    }
    override void loadoutconfigure(string input){
        int semi=getloadoutvar(input,"semi",1);
		if(semi>0){
			weaponstatus[WGProp_Auto]=-1;
			weaponstatus[0]|=WGF_NoFireSelect;
		}else{
			int firemode=getloadoutvar(input,"firemode",1);
			if(firemode>=0){
				weaponstatus[0]&=~WGF_NoFireSelect;
				weaponstatus[WGProp_Auto]=clamp(firemode,0,1);
			}
		}
        if(
            !(weaponstatus[0]&WGF_Chamber)
            &&weaponstatus[WGProp_Mag]>0
        ){
            weaponstatus[0]|=WGF_Chamber;
            if(weaponstatus[WGProp_Mag]==31)weaponstatus[WGProp_Mag]=29;
            else weaponstatus[WGProp_Mag]--;
        }
    }
}
enum wigeonstatus{
    WGF_Chamber=1,
    WGF_ChamberBroken=2,
    WGF_DirtyMag=4,
    WGF_UnloadOnly=8,
    WGF_StillPressingReload=16,
    WGF_LoadingDirty=32,
    WGF_NoFireSelect=64,

    WGProp_Flags=0,
    WGProp_Mag=1, //-1 is empty
    WGProp_Auto=2, //2 is burst, 2-5 counts ratchet
    WGProp_Heat=3,
    WGProp_Broken=4
};

class HDWigeonRandom:IdleDummy{
	states{
	spawn:
		TNT1 A 0 nodelay{
			let zzz=HD_Wigeon(spawn("HD_Wigeon",pos,ALLOW_REPLACE));
			if(!zzz)return;
			zzz.special=special;
			for(int i=0;i<5;i++)zzz.args[i]=args[i];
            if(!random(0,3))zzz.weaponstatus[0]|=WGF_NoFireSelect;
			spawn("HDNDMMag30",pos+(7,0,0),ALLOW_REPLACE);
			spawn("HDNDMMag30",pos+(5,0,0),ALLOW_REPLACE);
		}stop;
	}
}

class HDNDMMag30:HDMagAmmo{
    default{
        //$Category "Ammo/Hideous Destructor/"
        //$Title "4.26mm UAC Standard Mag"
        //$Sprite "CLIPB0"

        hdmagammo.maxperunit 31;  //NOTE: *only* the guns do the "+100 for dirty mag" thing
        hdmagammo.roundtype "HDNDMLoose";
        hdmagammo.roundbulk ENC_426_LOADED*0.93;
        hdmagammo.magbulk ENC_426MAG_EMPTY*0.82;
        hdmagammo.extracttime 8;

        tag "$TAG_NDM30MAG";
        hdpickup.refid "n30";
        inventory.pickupmessage "$PICKUP_NDM30MAG";
        Scale 0.65;
    }
    override void postbeginplay(){
        super.postbeginplay();
        sealtimer=0;
        breakchance=0;
    }
    int breakchance;
    int sealtimer;
    bool reseal;
    override void doeffect(){
        if(sealtimer>0)sealtimer--;
        if(breakchance>0)breakchance--;
        super.doeffect();
        reseal = owner && owner.player && owner.player.cmd.buttons&BT_USE;
    }
    override string pickupmessage(){
        string pms=super.pickupmessage();
        if(mags[0]<31)pms.appendformat(" %s",StringTable.Localize("$WGNMAGMSG"));
        return pms;
    }
    override string,string,name,double getmagsprite(int thismagamt){
        string magsprite;
        if(thismagamt>=31)magsprite="ZMAGA0";
        else if(thismagamt>0)magsprite="ZMAGB0";
        else magsprite="ZMAGC0";
        return magsprite,"PBRSA0","HDNDMLoose",0.6;
    }
    override int GetMagHudCount(int input){
        if(input==31)return 30;
        return input;
    }
    bool DirtyMagsOnly(){
        if(mags.size()!=amount)return false;
        for(int i=0;i<amount;i++){
            if(mags[i]>=31)return false;
        }
        return true;
    }
    override void DrawRoundCount(HDStatusBar sb,HDPlayerPawn hpl,name roundsprite,double scl,int offx,int offy,MagManager magman){
		offx+=40;
		scl=1.6;
		sb.drawstring(
			sb.pSmallFont,sb.FormatNumber(hpl.countinv(roundtype)),
			(offx+2,offy),sb.DI_SCREEN_CENTER|sb.DI_TEXT_ALIGN_LEFT,
			font.CR_BROWN
		);


		if(!!magman){
			int rounddir=magman.weaponstatus[MMSS_ROUNDDIR];
			if(rounddir!=0){
				int broffx=offx;
				int broffy=offy;
				if(rounddir<0)broffx+=rounddir;
				else broffx=rounddir+offx-40;
				if(bseesdaggers){
					broffy+=20;
					if(
						rounddir<-20
						||(
							rounddir>0
							&&rounddir<20
						)
					){
						broffy+=((broffx-offx)>>1);
					}
				}
				broffy+=abs(abs(rounddir)-20)-20;
				sb.drawimage(roundsprite,(broffx,broffy),
					sb.DI_SCREEN_CENTER|sb.DI_ITEM_RIGHT_TOP,
					scale:(scl,scl)
				);
			}
		}

		sb.drawimage(roundsprite,(offx,offy),
			sb.DI_SCREEN_CENTER|sb.DI_ITEM_RIGHT_TOP,
			scale:(scl,scl)
		);
		if(!!hpl.countinv("MM_4mmSealant")){
			offy+=14;
			sb.drawstring(
				sb.pSmallFont,sb.FormatNumber(hpl.countinv("MM_4mmSealant")).." \cu[Use] Reseal Full Mag",
				(offx+2,offy),sb.DI_SCREEN_CENTER|sb.DI_TEXT_ALIGN_LEFT,
				font.CR_BROWN,
                scale:(0.6,0.6)
			);
			sb.drawimage("SEALA0",(offx,offy),
				sb.DI_SCREEN_CENTER|sb.DI_ITEM_RIGHT_TOP,
				scale:(0.8,0.8)
			);
		}
	}
    override bool Extract(){
        SyncAmount();
        int mindex=mags.size()-1;
        if(
            mags.size()<1
            ||mags[mindex]<1
            ||owner.A_JumpIfInventory(roundtype,0,"null")
        )return false;
        if(mags[mindex]==31){
            if(sealtimer<1){
                owner.A_Log(string.format(StringTable.Localize("$WGNMAGREALLY"),StringTable.Localize("$WGNMAGMSG")),true);
                sealtimer=10;
                extracttime=9;
                return false;
            }else{
                mags[mindex]=30;
                extracttime=12;
                owner.A_StartSound("magmanager/426open",CHAN_WEAPON,CHANF_OVERLAP);
                return false;
            }
        }else extracttime=default.extracttime;
        int totake=min(random(1,9),mags[mindex]);
        if(totake<HDPickup.MaxGive(owner,roundtype,roundbulk))HDF.Give(owner,roundtype,totake);
        else HDPickup.DropItem(owner,roundtype,totake);
        owner.A_StartSound("magmanager/extract",CHAN_WEAPON);
        owner.A_StartSound("magmanager/extract426",CHAN_WEAPON,CHANF_OVERLAP,0.4);
        mags[mindex]-=totake;
        return true;
    }
    override bool Insert(){
        SyncAmount();
        if(reseal && mags[mags.size()-1]==30 && owner.countinv("MM_4mmSealant"))
        {
            mags[mags.size()-1]++;
            owner.A_StartSound("magmanager/insert",16);
            owner.A_TakeInventory("MM_4mmSealant",1,TIF_NOTAKEINFINITE);
        }
        if(
            mags.size()<1
            ||mags[mags.size()-1]>=30
            ||!owner.countinv(roundtype)
        )return false;
        owner.A_TakeInventory(roundtype,1,TIF_NOTAKEINFINITE);
        owner.A_StartSound("magmanager/insert",8);
        if(random(0,80)<=breakchance){
            owner.A_StartSound("magmanager/426shatter",8,CHANF_OVERLAP);
            owner.A_SpawnItemEx("HDSmokeChunk",12,0,owner.height-12,4,frandom(-2,2),frandom(2,4));
            owner.damagemobj(self,owner,1,"hot",DMG_NO_ARMOR);
            breakchance=min(breakchance+25,80);
            return false;
        }
        breakchance=max(breakchance,24);
        owner.A_StartSound("weapons/pocket",9,volume:frandom(0.1,0.6));
        mags[mags.size()-1]++;
        return true;
    }
    override void Consolidate(){
        SyncAmount();
        if(amount<2)return;
        int totalrounds=0;
        int howmanymags=0;
        for(int i=0;i<amount;i++){
            int thismag=mags[i];
            if(
                !thismag
                ||thismag>=30
            )continue;
            howmanymags++;
            totalrounds+=mags[i]%25;
            mags[i]=0; //keep the empties, do NOT call clear()!
        }
        if(howmanymags>1)totalrounds=int(totalrounds*frandom(0.9,1.));
        for(int i=0;i<amount;i++){
            if(mags[i]>=30)continue;
            int toinsert=clamp(totalrounds,mags[i],30);
            mags[i]=toinsert;
            totalrounds-=toinsert;
            if(totalrounds<1)break;
        }
    }
    states(actor){
    spawn:
        ZMAG AB -1 nodelay{
            if(!mags.size()){destroy();return;}
            int mmm=mags[0];
            if(mmm>31)mags[0]=min(30,mmm%100);
            if(mmm<31)frame=1;
        }stop;
    spawnempty:
        ZMAG C -1 A_SpawnEmpty();
        stop;
    }
}

class HD_WigeonExplosion : HDActor
{
    Default
    {
		projectile; -nogravity -noteleport +bounceonactors
		-noblockmap -grenadetrail -floorclip +forcexybillboard
		+nodamagethrust +noblood
		bouncetype "doom"; decal "none";
		mass 30; pushfactor 3.4; bouncefactor 0.3; gravity 1;
		deathsound "misc/fragknock";
		bouncesound "misc/fragknock";
		wallbouncesound "misc/fragknock";
		obituary "$OB_WIGEONSKILLISSUE";
		//hdupk.pickupmessage "picked up (and defused) a rocket grenade.";
		damagefactor(0);
		radius 1.5; height 1.5; scale 0.26;
	}
    States{ 
    spawn:
		TNT1 A 1;
		---- A 0{
			A_SprayDecal("Scorch",8);
			A_HDBlast(
				blastradius:128,blastdamage:random(24,48),fullblastradius:48,
				pushradius:128,pushamount:64,fullpushradius:48,
				fragradius:HDCONST_ONEMETRE*(0.19*stamina),fragtype:"HDB_frag",
				immolateradius:48,immolateamount:random(3,30),
				immolatechance:10
			);
			actor xpl=spawn("WAN_20mmsploder",pos-(0,0,1),ALLOW_REPLACE);
			xpl.target=target;xpl.master=master;xpl.stamina=stamina;
			A_SpawnChunksFrags("HDB_frag",10,1);
		}stop;
    }
}