version "4.14"

#include "zscript/EventHandlers.zsc"
#include "zscript/Taronga.zsc"
#include "zscript/Currawong.zsc"
#include "zscript/ShotPistol.zsc"
#include "zscript/Junco.zsc"
#include "zscript/Kakapo.zsc"
#include "zscript/Trocaz.zsc"
#include "zscript/Misc.zsc"
#include "zscript/Pochard.zsc"
//#include "zscript/Wigeon.zsc"
//#include "zscript/ColdCalculus.zsc"

const ENC_10MAG_EMPTY = ENC_9MAG_EMPTY * 1.1;
const ENC_10MAG_LOADED = ENC_10MAG_EMPTY * 0.8;