version "4.14"

#include "zscript/Taronga.zsc"
#include "zscript/Currawong.zsc"
#include "zscript/ShotPistol.zsc"
#include "zscript/Junco.zsc"
#include "zscript/Kakapo.zsc"
#include "zscript/Trocaz.zsc"
#include "zscript/Misc.zsc"
#include "zscript/Pochard.zsc"

const HDLD_TARONGA = "trn";
const HDLD_SHTPSTL = "6ps";
const HDLD_CURRAWONG = "cwn";
const HDLD_JUNCO = "jnk";
const HDLD_KAKAPO = "kpo";
const HDLD_TROCAZ = "tcz";
const HDLD_POCHARD = "prd";

const HDLD_SEALANT = "sel";
const HDLD_CURRAWONGMAG = "c30";
const HDLD_066MAG10 = "6m1";
const HDLD_4M25 = "425";
const HDLD_8M100 = "108";

const ENC_10MAG_EMPTY = ENC_9MAG_EMPTY * 1.1;
const ENC_10MAG_LOADED = ENC_10MAG_EMPTY * 0.8;